import test from "node:test";
import assert from "node:assert/strict";
import { listKnownReviewRoutingRecoveries,recoverKnownReviewRouting } from "./merchantAttendanceReviewRoutingRecovery";
import { listKnownAttendanceRecoveries,recoverKnownAttendance } from "./merchantAttendanceRecovery";
import { reviewRoutingPendingKey } from "./merchantAttendanceReviewRoutingClient";
import { routingId,routingSite,routingOwner,routingDetail,routingCommand,routingCommandHash,routingReceipt,routingResult } from "../../scripts/fixtures/attendance-review-routing-model";
function setup(){const values=new Map<string,string>(),key=reviewRoutingPendingKey(routingSite,routingOwner),query=routingDetail().query,command=routingCommand();const raw=JSON.stringify({protocol:"attendance-review-routing-pending-v1",version:1,actorId:routingOwner,query,command,commandFingerprint:routingCommandHash(query,command)});values.set(key,raw);
  const storage={get length(){return values.size;},key:(n:number)=>[...values.keys()][n]??null,getItem:(k:string)=>values.get(k)??null,setItem:(k:string,v:string)=>{values.set(k,v);},removeItem:(k:string)=>{values.delete(k);}};return{values,key,raw,query,command,storage};}
const json=(v:unknown)=>new Response(JSON.stringify(v),{headers:{"content-type":"application/json"}});
test("198 recovery inventory is local, actor-specific and part of shared global inventory",async()=>{const s=setup();const own=await listKnownReviewRoutingRecoveries(s.storage,routingOwner,()=>true);assert.equal(own.entries.length,1);assert.equal(own.invalid,false);assert.equal((await listKnownReviewRoutingRecoveries(s.storage,routingId(99),()=>true)).entries.length,0);const all=await listKnownAttendanceRecoveries(s.storage,routingOwner,()=>true);assert.equal(all.entries.length,1);assert.equal(all.entries[0].kind,"review-routing");assert.equal(s.values.get(s.key),s.raw);});
test("198 lost owner authorization still uses only true Auth and minimal original receipt GET",async()=>{const s=setup(),entry=(await listKnownReviewRoutingRecoveries(s.storage,routingOwner,()=>true)).entries[0],calls:string[]=[];
  const receipt=await recoverKnownAttendance(entry,{authenticatedUserId:routingOwner,storage:s.storage,signal:new AbortController().signal,isCurrentAuth:()=>true,apiFetch:async(path,init)=>{assert.equal(init?.method,"GET");assert.equal(init?.body,undefined);calls.push(path);assert.match(path,/mode=recover/);assert.doesNotMatch(path,/mode=(detail|list|history|grants)/);return json({ok:true,data:routingResult({kind:"receipt"},routingReceipt(s.query,s.command))});}});assert.equal(receipt?.kind,"review-routing");assert.equal(calls.length,1);assert.equal(s.values.size,0);});
test("198 null/foreign/full-command-mismatch receipts retain original bytes",async()=>{for(const kind of["null","command","actor"]as const){const s=setup(),entry=(await listKnownReviewRoutingRecoveries(s.storage,routingOwner,()=>true)).entries[0];const receipt=await recoverKnownReviewRouting(entry,{authenticatedUserId:routingOwner,storage:s.storage,signal:new AbortController().signal,isCurrentAuth:()=>true,apiFetch:async()=>json({ok:true,data:routingResult({kind:"receipt"},kind==="null"?null:routingReceipt(s.query,kind==="command"?{...s.command,reason:"其他意图"}:s.command,kind==="actor"?routingId(99):routingOwner))})});assert.equal(receipt,null);assert.equal(s.values.get(s.key),s.raw);}});
test("198 another writer replacement or changed Auth cannot remove the pending record",async()=>{const s=setup(),entry=(await listKnownReviewRoutingRecoveries(s.storage,routingOwner,()=>true)).entries[0];let current=true;const receipt=await recoverKnownReviewRouting(entry,{authenticatedUserId:routingOwner,storage:s.storage,signal:new AbortController().signal,isCurrentAuth:()=>current,apiFetch:async()=>{s.values.set(s.key,"replacement");return json({ok:true,data:routingResult({kind:"receipt"},routingReceipt(s.query,s.command))});}});assert.equal(receipt,null);assert.equal(s.values.get(s.key),"replacement");current=false;await assert.rejects(recoverKnownReviewRouting(entry,{authenticatedUserId:routingOwner,storage:s.storage,signal:new AbortController().signal,isCurrentAuth:()=>current,apiFetch:async()=>assert.fail()}));});
test("198 malformed matching storage is preserved and combined 65-slot inventory is refused",async()=>{const s=setup();s.values.set(s.key,"not-json");assert.equal((await listKnownAttendanceRecoveries(s.storage,routingOwner,()=>true)).invalid,true);assert.equal(s.values.get(s.key),"not-json");for(let n=0;n<65;n++)s.values.set(`faolla:attendance:review-routing:v1:${String(90000000+n)}:${routingOwner}`,s.raw);await assert.rejects(listKnownAttendanceRecoveries(s.storage,routingOwner,()=>true),/recovery_storage_limit/);});
