import assert from "node:assert/strict";
import test from "node:test";
import {
  buildPlatformMerchantSnapshotBlocks,
  buildPlatformMerchantSnapshotPayloadFromState,
  readPlatformMerchantSnapshotFromBlocks,
} from "./platformMerchantSnapshot";

test("buildPlatformMerchantSnapshotPayloadFromState keeps merchant info and card settings", () => {
  const payload = buildPlatformMerchantSnapshotPayloadFromState({
    sites: [
      {
        id: "10000000",
        tenantId: "tenant-1",
        merchantName: "fafona",
        domainPrefix: "fafona",
        domainSuffix: "fafona",
        contactAddress: "",
        contactName: "",
        contactPhone: "",
        contactEmail: "",
        name: "fafona",
        domain: "fafona",
        categoryId: "category-1",
        category: "品牌官网",
        industry: "娱乐",
        status: "online",
        publishedVersion: 1,
        lastPublishedAt: null,
        features: {
          multi_page_editor: false,
          schedule_publish: false,
          ai_copywriting: false,
          custom_domain: false,
          member_center: false,
          ab_test: false,
          api_access: false,
          advanced_analytics: false,
        },
        location: {
          countryCode: "ES",
          country: "Spain",
          provinceCode: "AN",
          province: "Sevilla",
          city: "Sevilla",
        },
        merchantCardImageUrl: "https://example.com/card.webp",
        merchantCardImageOpacity: 0.45,
        status: "maintenance",
        serviceExpiresAt: "2026-04-30T00:00:00.000Z",
        sortConfig: {
          recommendedCountryRank: 2,
          recommendedProvinceRank: null,
          recommendedCityRank: null,
          industryCountryRank: 1,
          industryProvinceRank: null,
          industryCityRank: null,
        },
        configHistory: [
          {
            id: "cfg-1",
            at: "2026-04-10T10:00:00.000Z",
            operator: "super-admin",
            summary: "配置更新",
            changes: ["到期时间：未设置 -> 2026-04-30"],
            before: {
              serviceExpiresAt: null,
              permissionConfig: {
                planLimit: 1,
                pageLimit: 10,
                businessCardLimit: 1,
                allowBusinessCardLinkMode: false,
                allowBookingEmailPrefill: false,
                allowBookingAutoEmail: false,
                businessCardBackgroundImageLimitKb: 200,
                businessCardContactImageLimitKb: 200,
                businessCardExportImageLimitKb: 400,
                commonBlockImageLimitKb: 300,
                galleryBlockImageLimitKb: 300,
                allowInsertBackground: false,
                allowThemeEffects: false,
                allowButtonBlock: false,
                allowGalleryBlock: false,
                allowMusicBlock: false,
                allowProductBlock: false,
                allowBookingBlock: false,
                publishSizeLimitMb: 1,
              },
              merchantCardImageUrl: "",
              merchantCardImageOpacity: 1,
              chatAvatarImageUrl: "",
              contactVisibility: {
                phoneHidden: false,
                emailHidden: false,
                businessCardHidden: false,
              },
              sortConfig: {
                recommendedCountryRank: null,
                recommendedProvinceRank: null,
                recommendedCityRank: null,
                industryCountryRank: null,
                industryProvinceRank: null,
                industryCityRank: null,
              },
            },
            after: {
              serviceExpiresAt: "2026-04-30T00:00:00.000Z",
              permissionConfig: {
                planLimit: 1,
                pageLimit: 10,
                businessCardLimit: 1,
                allowBusinessCardLinkMode: false,
                allowBookingEmailPrefill: false,
                allowBookingAutoEmail: false,
                businessCardBackgroundImageLimitKb: 200,
                businessCardContactImageLimitKb: 200,
                businessCardExportImageLimitKb: 400,
                commonBlockImageLimitKb: 300,
                galleryBlockImageLimitKb: 300,
                allowInsertBackground: false,
                allowThemeEffects: false,
                allowButtonBlock: false,
                allowGalleryBlock: false,
                allowMusicBlock: false,
                allowProductBlock: false,
                allowBookingBlock: false,
                publishSizeLimitMb: 1,
              },
              merchantCardImageUrl: "",
              merchantCardImageOpacity: 1,
              chatAvatarImageUrl: "",
              contactVisibility: {
                phoneHidden: false,
                emailHidden: false,
                businessCardHidden: false,
              },
              sortConfig: {
                recommendedCountryRank: 2,
                recommendedProvinceRank: null,
                recommendedCityRank: null,
                industryCountryRank: 1,
                industryProvinceRank: null,
                industryCityRank: null,
              },
            },
          },
        ],
        businessCards: [
          {
            id: "card-1",
            createdAt: "2026-03-29T12:00:00.000Z",
            mode: "link",
            name: "fafona",
            title: "Contact",
            width: 640,
            height: 360,
            showQr: true,
            contacts: {
              contactName: "fafona",
              phone: "633130577",
              phones: ["633130577"],
              email: "caimin00x@gmail.com",
              address: "Sevilla",
              wechat: "",
              whatsapp: "",
              twitter: "",
              weibo: "",
              telegram: "",
              linkedin: "",
              discord: "",
              facebook: "",
              instagram: "",
              tiktok: "",
              douyin: "",
              xiaohongshu: "",
            },
            imageUrl: "data:image/png;base64,aaa",
            shareKey: "share-card-1",
            ratioMode: "16:9",
            targetUrl: "https://fafona.faolla.com",
            showInChat: true,
            textLayout: {
              merchantName: { x: 0, y: 0 },
              title: { x: 0, y: 0 },
              website: { x: 0, y: 0 },
              contactName: { x: 0, y: 0 },
              phone: { x: 0, y: 0 },
              email: { x: 0, y: 0 },
              address: { x: 0, y: 0 },
              wechat: { x: 0, y: 0 },
              whatsapp: { x: 0, y: 0 },
              twitter: { x: 0, y: 0 },
              weibo: { x: 0, y: 0 },
              telegram: { x: 0, y: 0 },
              linkedin: { x: 0, y: 0 },
              discord: { x: 0, y: 0 },
              facebook: { x: 0, y: 0 },
              instagram: { x: 0, y: 0 },
              tiktok: { x: 0, y: 0 },
              douyin: { x: 0, y: 0 },
              xiaohongshu: { x: 0, y: 0 },
            },
            typography: {
              name: { color: "#000000", fontSize: 16, fontWeight: 600 },
              title: { color: "#000000", fontSize: 14, fontWeight: 500 },
              website: { color: "#000000", fontSize: 12, fontWeight: 400 },
              info: { color: "#000000", fontSize: 12, fontWeight: 400 },
            },
            customTexts: [],
            websiteLabel: "",
            shareImageUrl: "https://example.com/share-card.webp",
            showWebsiteUrl: true,
            backgroundColor: "#ffffff",
            fieldTypography: {
              merchantName: { color: "#000000", fontSize: 16, fontWeight: 600 },
              title: { color: "#000000", fontSize: 14, fontWeight: 500 },
              website: { color: "#000000", fontSize: 12, fontWeight: 400 },
              contactName: { color: "#000000", fontSize: 12, fontWeight: 400 },
              phone: { color: "#000000", fontSize: 12, fontWeight: 400 },
              email: { color: "#000000", fontSize: 12, fontWeight: 400 },
              address: { color: "#000000", fontSize: 12, fontWeight: 400 },
              wechat: { color: "#000000", fontSize: 12, fontWeight: 400 },
              whatsapp: { color: "#000000", fontSize: 12, fontWeight: 400 },
              twitter: { color: "#000000", fontSize: 12, fontWeight: 400 },
              weibo: { color: "#000000", fontSize: 12, fontWeight: 400 },
              telegram: { color: "#000000", fontSize: 12, fontWeight: 400 },
              linkedin: { color: "#000000", fontSize: 12, fontWeight: 400 },
              discord: { color: "#000000", fontSize: 12, fontWeight: 400 },
              facebook: { color: "#000000", fontSize: 12, fontWeight: 400 },
              instagram: { color: "#000000", fontSize: 12, fontWeight: 400 },
              tiktok: { color: "#000000", fontSize: 12, fontWeight: 400 },
              douyin: { color: "#000000", fontSize: 12, fontWeight: 400 },
              xiaohongshu: { color: "#000000", fontSize: 12, fontWeight: 400 },
            },
            contactFieldOrder: [
              "contactName",
              "phone",
              "email",
              "address",
              "wechat",
              "whatsapp",
              "twitter",
              "weibo",
              "facebook",
              "instagram",
              "tiktok",
              "xiaohongshu",
              "douyin",
              "telegram",
              "linkedin",
              "discord",
            ],
            contactOnlyFields: {
              contactName: false,
              phone: false,
              email: false,
              address: false,
              wechat: false,
              whatsapp: false,
              twitter: false,
              weibo: false,
              telegram: false,
              linkedin: false,
              discord: false,
              facebook: false,
              instagram: false,
              tiktok: false,
              douyin: false,
              xiaohongshu: false,
            },
            backgroundImageUrl: "data:image/png;base64,bbb",
            chatDisplayDisabled: false,
            contactPageImageUrl: "data:image/png;base64,ccc",
            backgroundColorOpacity: 1,
            backgroundImageOpacity: 1,
            contactPageImageHeight: 480,
            contactPagePublicImageUrl: "https://example.com/contact-card.webp",
          },
        ],
        createdAt: "2026-03-29T12:00:00.000Z",
        updatedAt: "2026-03-29T12:00:00.000Z",
      },
    ],
    homeLayout: {
      heroTitle: "",
      heroSubtitle: "",
      featuredCategoryIds: [],
      merchantDefaultSortRule: "name_desc",
      sections: [],
    },
  });

  assert.equal(payload.defaultSortRule, "name_desc");
  assert.equal(payload.snapshot.length, 1);
  assert.equal(payload.snapshot[0]?.industry, "娱乐");
  assert.equal(payload.snapshot[0]?.location.country, "Spain");
  assert.equal(payload.snapshot[0]?.merchantCardImageUrl, "https://example.com/card.webp");
  assert.equal(payload.snapshot[0]?.merchantCardImageOpacity, 0.45);
  assert.equal(payload.snapshot[0]?.status, "maintenance");
  assert.equal(payload.snapshot[0]?.serviceExpiresAt, "2026-04-30T00:00:00.000Z");
  assert.equal(payload.snapshot[0]?.chatBusinessCard?.imageUrl, "https://example.com/share-card.webp");
  assert.equal(payload.snapshot[0]?.chatBusinessCard?.backgroundImageUrl, "");
  assert.equal(payload.snapshot[0]?.chatBusinessCard?.contactPageImageUrl, "");
  assert.equal(payload.snapshot[0]?.chatBusinessCard?.contactPagePublicImageUrl, "https://example.com/contact-card.webp");
  assert.equal(payload.merchantConfigHistoryBySiteId["10000000"]?.length, 1);
  assert.equal(payload.merchantConfigHistoryBySiteId["10000000"]?.[0]?.operator, "super-admin");
});

test("platform merchant snapshot blocks round-trip through storage payload", () => {
  const stored = buildPlatformMerchantSnapshotBlocks({
    snapshot: [
      {
        id: "10000000",
        merchantName: "fafona",
        domainPrefix: "fafona",
        domainSuffix: "fafona",
        name: "fafona",
        domain: "fafona",
        category: "品牌官网",
        industry: "娱乐",
        location: {
          countryCode: "ES",
          country: "Spain",
          provinceCode: "AN",
          province: "Sevilla",
          city: "Sevilla",
        },
        merchantCardImageUrl: "https://example.com/card.webp",
        merchantCardImageOpacity: 0.45,
        status: "maintenance",
        serviceExpiresAt: "2026-04-30T00:00:00.000Z",
        sortConfig: {
          recommendedCountryRank: 2,
          recommendedProvinceRank: null,
          recommendedCityRank: null,
          industryCountryRank: 1,
          industryProvinceRank: null,
          industryCityRank: null,
        },
        createdAt: "2026-03-29T12:00:00.000Z",
      },
    ],
    defaultSortRule: "monthly_views_desc",
    merchantConfigHistoryBySiteId: {
      "10000000": [
        {
          id: "cfg-1",
          at: "2026-04-10T10:00:00.000Z",
          operator: "super-admin",
          summary: "配置更新",
          changes: ["到期时间：未设置 -> 2026-04-30"],
          before: {
            serviceExpiresAt: null,
            permissionConfig: {
              planLimit: 1,
              pageLimit: 10,
              businessCardLimit: 1,
              allowBusinessCardLinkMode: false,
              allowBookingEmailPrefill: false,
              allowBookingAutoEmail: false,
              businessCardBackgroundImageLimitKb: 200,
              businessCardContactImageLimitKb: 200,
              businessCardExportImageLimitKb: 400,
              commonBlockImageLimitKb: 300,
              galleryBlockImageLimitKb: 300,
              allowInsertBackground: false,
              allowThemeEffects: false,
              allowButtonBlock: false,
              allowGalleryBlock: false,
              allowMusicBlock: false,
              allowProductBlock: false,
              allowBookingBlock: false,
              publishSizeLimitMb: 1,
            },
            merchantCardImageUrl: "",
            merchantCardImageOpacity: 1,
            chatAvatarImageUrl: "",
            contactVisibility: {
              phoneHidden: false,
              emailHidden: false,
              businessCardHidden: false,
            },
            sortConfig: {
              recommendedCountryRank: null,
              recommendedProvinceRank: null,
              recommendedCityRank: null,
              industryCountryRank: null,
              industryProvinceRank: null,
              industryCityRank: null,
            },
          },
          after: {
            serviceExpiresAt: "2026-04-30T00:00:00.000Z",
            permissionConfig: {
              planLimit: 1,
              pageLimit: 10,
              businessCardLimit: 1,
              allowBusinessCardLinkMode: false,
              allowBookingEmailPrefill: false,
              allowBookingAutoEmail: false,
              businessCardBackgroundImageLimitKb: 200,
              businessCardContactImageLimitKb: 200,
              businessCardExportImageLimitKb: 400,
              commonBlockImageLimitKb: 300,
              galleryBlockImageLimitKb: 300,
              allowInsertBackground: false,
              allowThemeEffects: false,
              allowButtonBlock: false,
              allowGalleryBlock: false,
              allowMusicBlock: false,
              allowProductBlock: false,
              allowBookingBlock: false,
              publishSizeLimitMb: 1,
            },
            merchantCardImageUrl: "",
            merchantCardImageOpacity: 1,
            chatAvatarImageUrl: "",
            contactVisibility: {
              phoneHidden: false,
              emailHidden: false,
              businessCardHidden: false,
            },
            sortConfig: {
              recommendedCountryRank: 2,
              recommendedProvinceRank: null,
              recommendedCityRank: null,
              industryCountryRank: 1,
              industryProvinceRank: null,
              industryCityRank: null,
            },
          },
        },
      ],
    },
  });

  const payload = readPlatformMerchantSnapshotFromBlocks(stored);
  assert.ok(payload);
  assert.equal(payload?.defaultSortRule, "monthly_views_desc");
  assert.equal(payload?.snapshot[0]?.location.city, "Sevilla");
  assert.equal(payload?.snapshot[0]?.merchantCardImageUrl, "https://example.com/card.webp");
  assert.equal(payload?.snapshot[0]?.merchantCardImageOpacity, 0.45);
  assert.equal(payload?.snapshot[0]?.status, "maintenance");
  assert.equal(payload?.snapshot[0]?.serviceExpiresAt, "2026-04-30T00:00:00.000Z");
  assert.equal(payload?.merchantConfigHistoryBySiteId["10000000"]?.length, 1);
  assert.equal(payload?.merchantConfigHistoryBySiteId["10000000"]?.[0]?.summary, "配置更新");
});
