import { resolveSupportedLocale } from "@/lib/i18n";

export const UI_GLOSSARY_TRANSLATIONS = {
  "先生": {
    "en": "Sir",
    "es": "Señor",
    "fr": "Monsieur",
    "de": "Herr",
    "it": "Signore",
    "pt": "Senhor",
    "ru": "сэр",
    "uk": "сер",
    "pl": "Panie",
    "tr": "Efendim",
    "nl": "Mijnheer",
    "ro": "domnule",
    "cs": "pane",
    "sv": "Sir",
    "hu": "uram",
    "da": "Sir",
    "fi": "Sir",
    "no": "Sir",
    "sk": "pane",
    "hr": "gospodine",
    "bs": "Gospodine",
    "sr": "господине",
    "bg": "господине",
    "el": "Κύριε",
    "sq": "zotëri",
    "lt": "pone",
    "sl": "gospod",
    "lv": "kungs",
    "et": "Sir",
    "mk": "Господине",
    "ca": "Senyor",
    "eu": "Jauna",
    "gl": "señor",
    "cy": "Syr",
    "is": "Herra",
    "ga": "A dhuine uasail",
    "mt": "Sinjur",
    "lb": "Här",
    "ja": "先生",
    "ko": "선생님",
    "zh-tw": "先生"
  },
  "女士": {
    "en": "lady",
    "es": "señora",
    "fr": "dame",
    "de": "Dame",
    "it": "signora",
    "pt": "senhora",
    "ru": "леди",
    "uk": "леді",
    "pl": "pani",
    "tr": "bayan",
    "nl": "dame",
    "ro": "doamna",
    "cs": "paní",
    "sv": "dam",
    "hu": "hölgy",
    "da": "dame",
    "fi": "rouva",
    "no": "dame",
    "sk": "pani",
    "hr": "dama",
    "bs": "lady",
    "sr": "дама",
    "bg": "дама",
    "el": "κυρία",
    "sq": "zonja",
    "lt": "ponia",
    "sl": "gospa",
    "lv": "dāma",
    "et": "daam",
    "mk": "дама",
    "ca": "senyora",
    "eu": "andrea",
    "gl": "señora",
    "cy": "foneddiges",
    "is": "frú",
    "ga": "bhean",
    "mt": "mara",
    "lb": "frou",
    "ja": "女性",
    "ko": "아가씨",
    "zh-tw": "女士"
  },
  "邮箱": {
    "en": "Email",
    "es": "Correo electrónico",
    "fr": "Courriel",
    "de": "E-Mail",
    "it": "E-mail",
    "pt": "E-mail",
    "ru": "электронная почта",
    "uk": "Електронна пошта",
    "pl": "E-mail",
    "tr": "E-posta",
    "nl": "E-mail",
    "ro": "E-mail",
    "cs": "Email",
    "sv": "E-post",
    "hu": "E-mail",
    "da": "E-mail",
    "fi": "Sähköposti",
    "no": "E-post",
    "sk": "Email",
    "hr": "E-mail",
    "bs": "Email",
    "sr": "Емаил",
    "bg": "Имейл",
    "el": "Email",
    "sq": "Email",
    "lt": "El. paštas",
    "sl": "E-pošta",
    "lv": "E-pasts",
    "et": "Meil",
    "mk": "Е-пошта",
    "ca": "Correu electrònic",
    "eu": "Posta elektronikoa",
    "gl": "Correo electrónico",
    "cy": "Ebost",
    "is": "Tölvupóstur",
    "ga": "Ríomhphost",
    "mt": "Email",
    "lb": "E-Mail",
    "ja": "電子メール",
    "ko": "이메일",
    "zh-tw": "信箱"
  },
  "电话": {
    "en": "phone",
    "es": "telefono",
    "fr": "téléphone",
    "de": "Telefon",
    "it": "telefono",
    "pt": "telefone",
    "ru": "телефон",
    "uk": "телефон",
    "pl": "telefon",
    "tr": "telefon",
    "nl": "telefoon",
    "ro": "telefon",
    "cs": "telefon",
    "sv": "telefon",
    "hu": "telefon",
    "da": "telefon",
    "fi": "puhelin",
    "no": "telefon",
    "sk": "telefón",
    "hr": "telefon",
    "bs": "telefon",
    "sr": "телефон",
    "bg": "телефон",
    "el": "τηλέφωνο",
    "sq": "telefon",
    "lt": "telefonas",
    "sl": "telefon",
    "lv": "tālrunis",
    "et": "telefon",
    "mk": "телефон",
    "ca": "telèfon",
    "eu": "telefonoa",
    "gl": "teléfono",
    "cy": "ffôn",
    "is": "síma",
    "ga": "fón",
    "mt": "telefon",
    "lb": "Telefon",
    "ja": "電話",
    "ko": "전화",
    "zh-tw": "電話"
  },
  "姓名": {
    "en": "name",
    "es": "nombre",
    "fr": "nom",
    "de": "Namen",
    "it": "nome",
    "pt": "nome",
    "ru": "имя",
    "uk": "назва",
    "pl": "imię",
    "tr": "isim",
    "nl": "naam",
    "ro": "nume",
    "cs": "jméno",
    "sv": "namn",
    "hu": "nevet",
    "da": "navn",
    "fi": "nimi",
    "no": "navn",
    "sk": "meno",
    "hr": "ime",
    "bs": "ime",
    "sr": "име",
    "bg": "име",
    "el": "όνομα",
    "sq": "emri",
    "lt": "pavadinimas",
    "sl": "ime",
    "lv": "nosaukums",
    "et": "nimi",
    "mk": "име",
    "ca": "nom",
    "eu": "izena",
    "gl": "nome",
    "cy": "enw",
    "is": "nafn",
    "ga": "ainm",
    "mt": "isem",
    "lb": "Numm",
    "ja": "名前",
    "ko": "이름",
    "zh-tw": "姓名"
  },
  "名称": {
    "en": "Name",
    "es": "Nombre",
    "fr": "Nom",
    "de": "Name",
    "it": "Nome",
    "pt": "Nome",
    "ru": "Имя",
    "uk": "Ім'я",
    "pl": "Imię",
    "tr": "İsim",
    "nl": "Naam",
    "ro": "Nume",
    "cs": "Jméno",
    "sv": "Namn",
    "hu": "Név",
    "da": "Navn",
    "fi": "Nimi",
    "no": "Navn",
    "sk": "Meno",
    "hr": "Ime",
    "bs": "Ime",
    "sr": "Име",
    "bg": "Име",
    "el": "Όνομα",
    "sq": "Emri",
    "lt": "Vardas",
    "sl": "Ime",
    "lv": "Vārds",
    "et": "Nimi",
    "mk": "Име",
    "ca": "Nom",
    "eu": "Izena",
    "gl": "Nome",
    "cy": "Enw",
    "is": "Nafn",
    "ga": "Ainm",
    "mt": "Isem",
    "lb": "Numm",
    "ja": "名前",
    "ko": "이름",
    "zh-tw": "名稱"
  },
  "备注": {
    "en": "Remarks",
    "es": "Observaciones",
    "fr": "Remarques",
    "de": "Bemerkungen",
    "it": "Osservazioni",
    "pt": "Observações",
    "ru": "Примечания",
    "uk": "Зауваження",
    "pl": "Uwagi",
    "tr": "Açıklamalar",
    "nl": "Opmerkingen",
    "ro": "Remarci",
    "cs": "Poznámky",
    "sv": "Anmärkningar",
    "hu": "Megjegyzések",
    "da": "Bemærkninger",
    "fi": "Huomautuksia",
    "no": "Merknader",
    "sk": "Poznámky",
    "hr": "Primjedbe",
    "bs": "Napomene",
    "sr": "Примедбе",
    "bg": "Забележки",
    "el": "Παρατηρήσεις",
    "sq": "Vërejtje",
    "lt": "Pastabos",
    "sl": "Opombe",
    "lv": "Piezīmes",
    "et": "Märkused",
    "mk": "Забелешки",
    "ca": "Observacions",
    "eu": "Oharrak",
    "gl": "Observacións",
    "cy": "Sylwadau",
    "is": "Athugasemdir",
    "ga": "Nótaí",
    "mt": "Rimarki",
    "lb": "Remarquen",
    "ja": "備考",
    "ko": "비고",
    "zh-tw": "備註"
  },
  "店铺": {
    "en": "shop",
    "es": "tienda",
    "fr": "boutique",
    "de": "Shop",
    "it": "negozio",
    "pt": "fazer compras",
    "ru": "магазин",
    "uk": "магазин",
    "pl": "sklep",
    "tr": "dükkan",
    "nl": "winkel",
    "ro": "magazin",
    "cs": "obchod",
    "sv": "butik",
    "hu": "bolt",
    "da": "butik",
    "fi": "kauppa",
    "no": "butikk",
    "sk": "obchod",
    "hr": "trgovina",
    "bs": "shop",
    "sr": "продавница",
    "bg": "магазин",
    "el": "κατάστημα",
    "sq": "dyqan",
    "lt": "parduotuvė",
    "sl": "trgovina",
    "lv": "veikals",
    "et": "pood",
    "mk": "продавница",
    "ca": "botiga",
    "eu": "denda",
    "gl": "tenda",
    "cy": "siop",
    "is": "búð",
    "ga": "siopa",
    "mt": "ħanut",
    "lb": "Buttek",
    "ja": "ショップ",
    "ko": "가게",
    "zh-tw": "店舖"
  },
  "项目": {
    "en": "Project",
    "es": "Proyecto",
    "fr": "Projet",
    "de": "Projekt",
    "it": "Progetto",
    "pt": "Projeto",
    "ru": "Проект",
    "uk": "Проект",
    "pl": "Projekt",
    "tr": "Proje",
    "nl": "Project",
    "ro": "Proiect",
    "cs": "Projekt",
    "sv": "Projekt",
    "hu": "Projekt",
    "da": "Projekt",
    "fi": "Projekti",
    "no": "Prosjekt",
    "sk": "Projekt",
    "hr": "Projekt",
    "bs": "Projekt",
    "sr": "Пројекат",
    "bg": "Проект",
    "el": "Έργο",
    "sq": "Projekti",
    "lt": "Projektas",
    "sl": "Projekt",
    "lv": "Projekts",
    "et": "Projekt",
    "mk": "Проект",
    "ca": "Projecte",
    "eu": "Proiektua",
    "gl": "Proxecto",
    "cy": "Prosiect",
    "is": "Verkefni",
    "ga": "Tionscadal",
    "mt": "Proġett",
    "lb": "Projet",
    "ja": "プロジェクト",
    "ko": "프로젝트",
    "zh-tw": "項目"
  },
  "预约时间": {
    "en": "Appointment time",
    "es": "hora de la cita",
    "fr": "Heure de rendez-vous",
    "de": "Terminvereinbarung",
    "it": "Orario dell'appuntamento",
    "pt": "Hora da consulta",
    "ru": "Время встречи",
    "uk": "Час призначення",
    "pl": "Termin spotkania",
    "tr": "Randevu zamanı",
    "nl": "Afspraak tijd",
    "ro": "Ora programare",
    "cs": "Čas schůzky",
    "sv": "Tid för möte",
    "hu": "Időpont egyeztetés",
    "da": "Aftaletidspunkt",
    "fi": "Ajanvaraus",
    "no": "Avtaletid",
    "sk": "Čas stretnutia",
    "hr": "Vrijeme zakazivanja",
    "bs": "Zakazano vrijeme",
    "sr": "Заказано време",
    "bg": "Време за уговорка",
    "el": "Ώρα ραντεβού",
    "sq": "Koha e takimit",
    "lt": "Susitikimo laikas",
    "sl": "Čas za sestanek",
    "lv": "Tikšanās laiks",
    "et": "Kohtumise aeg",
    "mk": "Време на закажување",
    "ca": "Hora de cita",
    "eu": "Hitzorduaren ordua",
    "gl": "Hora da cita",
    "cy": "Amser apwyntiad",
    "is": "Viðtalstími",
    "ga": "Am coinne",
    "mt": "Ħin tal-appuntament",
    "lb": "Rendez-vous Zäit",
    "ja": "予約時間",
    "ko": "약속시간",
    "zh-tw": "預約時間"
  },
  "预约编号": {
    "en": "Appointment number",
    "es": "Número de cita",
    "fr": "Numéro de rendez-vous",
    "de": "Terminnummer",
    "it": "Numero dell'appuntamento",
    "pt": "Número do agendamento",
    "ru": "Номер записи",
    "uk": "Номер запису",
    "pl": "Numer spotkania",
    "tr": "Randevu numarası",
    "nl": "Afspraaknummer",
    "ro": "Numărul de programare",
    "cs": "Číslo schůzky",
    "sv": "Utnämningsnummer",
    "hu": "Időpontszám",
    "da": "Aftalenummer",
    "fi": "Tapaaminen numero",
    "no": "Avtalenummer",
    "sk": "Číslo stretnutia",
    "hr": "Broj termina",
    "bs": "Broj termina",
    "sr": "Број термина",
    "bg": "Номер на срещата",
    "el": "Αριθμός ραντεβού",
    "sq": "Numri i takimit",
    "lt": "Paskyrimo numeris",
    "sl": "Številka termina",
    "lv": "Tikšanās numurs",
    "et": "Kohtumise number",
    "mk": "Број за закажување",
    "ca": "Número de cita",
    "eu": "Hitzorduaren zenbakia",
    "gl": "Número de cita",
    "cy": "Rhif apwyntiad",
    "is": "Tímatalsnúmer",
    "ga": "Uimhir an cheapacháin",
    "mt": "Numru tal-appuntament",
    "lb": "Rendez-vous Zuel",
    "ja": "予約番号",
    "ko": "예약번호",
    "zh-tw": "預約編號"
  },
  "创建时间": {
    "en": "creation time",
    "es": "tiempo de creación",
    "fr": "temps de création",
    "de": "Schöpfungszeit",
    "it": "tempo di creazione",
    "pt": "hora de criação",
    "ru": "время создания",
    "uk": "час створення",
    "pl": "czas stworzenia",
    "tr": "yaratılış zamanı",
    "nl": "creatie tijd",
    "ro": "timpul de creație",
    "cs": "čas tvorby",
    "sv": "skapande tid",
    "hu": "teremtési idő",
    "da": "skabelsestid",
    "fi": "luomisaika",
    "no": "opprettelsestid",
    "sk": "čas tvorby",
    "hr": "vrijeme stvaranja",
    "bs": "vrijeme stvaranja",
    "sr": "време стварања",
    "bg": "време на създаване",
    "el": "χρόνος δημιουργίας",
    "sq": "koha e krijimit",
    "lt": "kūrimo laikas",
    "sl": "čas ustvarjanja",
    "lv": "radīšanas laiks",
    "et": "loomise aeg",
    "mk": "време на создавање",
    "ca": "temps de creació",
    "eu": "sorkuntza garaia",
    "gl": "tempo de creación",
    "cy": "amser creu",
    "is": "sköpunartími",
    "ga": "am cruthú",
    "mt": "ħin tal-ħolqien",
    "lb": "Kreatioun Zäit",
    "ja": "作成時間",
    "ko": "생성 시간",
    "zh-tw": "建立時間"
  },
  "提交时间": {
    "en": "Submission time",
    "es": "tiempo de envío",
    "fr": "Heure de soumission",
    "de": "Einreichungszeitpunkt",
    "it": "Orario di invio",
    "pt": "Hora de envio",
    "ru": "Время подачи",
    "uk": "Час подання",
    "pl": "Czas złożenia",
    "tr": "Gönderim zamanı",
    "nl": "Tijd voor indiening",
    "ro": "Timp de depunere",
    "cs": "Čas odevzdání",
    "sv": "Inlämningstid",
    "hu": "Beküldési idő",
    "da": "Indleveringstid",
    "fi": "Lähetysaika",
    "no": "Innleveringstid",
    "sk": "Čas odovzdania",
    "hr": "Vrijeme predaje",
    "bs": "Vrijeme predaje",
    "sr": "Време предаје",
    "bg": "Време за подаване",
    "el": "Χρόνος υποβολής",
    "sq": "Koha e dorëzimit",
    "lt": "Pateikimo laikas",
    "sl": "Čas oddaje",
    "lv": "Iesniegšanas laiks",
    "et": "Esitamise aeg",
    "mk": "Време на поднесување",
    "ca": "Temps de presentació",
    "eu": "Aurkezteko denbora",
    "gl": "Tempo de envío",
    "cy": "Amser cyflwyno",
    "is": "Skilatími",
    "ga": "Am aighneachta",
    "mt": "Ħin ta' sottomissjoni",
    "lb": "Soumissioun Zäit",
    "ja": "提出時間",
    "ko": "제출 시간",
    "zh-tw": "提交時間"
  },
  "待确认": {
    "en": "To be confirmed",
    "es": "Por confirmar",
    "fr": "A confirmer",
    "de": "Wird noch bestätigt",
    "it": "Da confermare",
    "pt": "A confirmar",
    "ru": "Подлежит подтверждению",
    "uk": "Буде підтверджено",
    "pl": "Do potwierdzenia",
    "tr": "Onaylanacak",
    "nl": "Te bevestigen",
    "ro": "De confirmat",
    "cs": "K potvrzení",
    "sv": "Ska bekräftas",
    "hu": "Megerősítendő",
    "da": "Skal bekræftes",
    "fi": "Vahvistettava",
    "no": "Skal bekreftes",
    "sk": "Na potvrdenie",
    "hr": "Bit će potvrđeno",
    "bs": "Za potvrdu",
    "sr": "Да се потврди",
    "bg": "Предстои потвърждение",
    "el": "Να επιβεβαιωθεί",
    "sq": "Për tu konfirmuar",
    "lt": "Turi būti patvirtinta",
    "sl": "Bo še potrjeno",
    "lv": "Jāapstiprina",
    "et": "Tuleb kinnitada",
    "mk": "Да се потврди",
    "ca": "To be confirmed",
    "eu": "Baieztatzeko",
    "gl": "Por confirmar",
    "cy": "I'w gadarnhau",
    "is": "Til staðfestingar",
    "ga": "Le deimhniú",
    "mt": "Għandu jiġi kkonfermat",
    "lb": "Fir ze bestätegt",
    "ja": "確認中",
    "ko": "확인 예정",
    "zh-tw": "待確認"
  },
  "已确认": {
    "en": "Confirmed",
    "es": "Confirmado",
    "fr": "Confirmé",
    "de": "Bestätigt",
    "it": "Confermato",
    "pt": "Confirmado",
    "ru": "Подтверждено",
    "uk": "Підтверджено",
    "pl": "Potwierdzone",
    "tr": "Onaylandı",
    "nl": "Bevestigd",
    "ro": "Confirmat",
    "cs": "Potvrzeno",
    "sv": "Bekräftad",
    "hu": "Megerősítve",
    "da": "Bekræftet",
    "fi": "Vahvistettu",
    "no": "Bekreftet",
    "sk": "Potvrdené",
    "hr": "Potvrđeno",
    "bs": "Potvrđeno",
    "sr": "Потврђено",
    "bg": "Потвърдено",
    "el": "Επιβεβαιώθηκε",
    "sq": "E konfirmuar",
    "lt": "Patvirtinta",
    "sl": "Potrjeno",
    "lv": "Apstiprināts",
    "et": "Kinnitatud",
    "mk": "Потврдено",
    "ca": "Confirmat",
    "eu": "Baieztatuta",
    "gl": "Confirmado",
    "cy": "Cadarnhawyd",
    "is": "Staðfest",
    "ga": "Deimhnithe",
    "mt": "Ikkonfermat",
    "lb": "Confirméiert",
    "ja": "確認済み",
    "ko": "확인됨",
    "zh-tw": "已確認"
  },
  "已完成": {
    "en": "Completed",
    "es": "Completado",
    "fr": "Terminé",
    "de": "Abgeschlossen",
    "it": "Completato",
    "pt": "Concluído",
    "ru": "Завершено",
    "uk": "Виконано",
    "pl": "Ukończono",
    "tr": "Tamamlandı",
    "nl": "Voltooid",
    "ro": "Terminat",
    "cs": "Dokončeno",
    "sv": "Avslutad",
    "hu": "Befejezve",
    "da": "Afsluttet",
    "fi": "Valmis",
    "no": "Fullført",
    "sk": "Dokončené",
    "hr": "Završeno",
    "bs": "Završeno",
    "sr": "Завршено",
    "bg": "Завършено",
    "el": "Ολοκληρώθηκε",
    "sq": "E përfunduar",
    "lt": "Baigta",
    "sl": "Dokončano",
    "lv": "Pabeigts",
    "et": "Lõpetatud",
    "mk": "Завршено",
    "ca": "Completat",
    "eu": "Osatua",
    "gl": "Completado",
    "cy": "Cwblhawyd",
    "is": "Lokið",
    "ga": "Críochnaithe",
    "mt": "Imlesta",
    "lb": "Ofgeschloss",
    "ja": "完了",
    "ko": "완료됨",
    "zh-tw": "已完成"
  },
  "已取消": {
    "en": "Canceled",
    "es": "Cancelado",
    "fr": "Annulé",
    "de": "Abgesagt",
    "it": "Annullato",
    "pt": "Cancelado",
    "ru": "Отменено",
    "uk": "Скасовано",
    "pl": "Anulowano",
    "tr": "İptal edildi",
    "nl": "Geannuleerd",
    "ro": "Anulat",
    "cs": "Zrušeno",
    "sv": "Avbruten",
    "hu": "Törölve",
    "da": "Annulleret",
    "fi": "Peruutettu",
    "no": "Kansellert",
    "sk": "Zrušené",
    "hr": "Otkazano",
    "bs": "Otkazano",
    "sr": "Отказано",
    "bg": "Отменено",
    "el": "Ακυρώθηκε",
    "sq": "Anuluar",
    "lt": "Atšaukta",
    "sl": "Preklicano",
    "lv": "Atcelts",
    "et": "Tühistatud",
    "mk": "Откажано",
    "ca": "Cancel·lat",
    "eu": "Bertan behera utzita",
    "gl": "Cancelado",
    "cy": "Wedi'i ganslo",
    "is": "Hætt við",
    "ga": "Ar ceal",
    "mt": "Ikkanċellat",
    "lb": "Annuléiert",
    "ja": "キャンセルされました",
    "ko": "취소됨",
    "zh-tw": "已取消"
  },
  "全部": {
    "en": "All",
    "es": "Todos",
    "fr": "Tout",
    "de": "Alle",
    "it": "Tutto",
    "pt": "Todos",
    "ru": "Все",
    "uk": "все",
    "pl": "Wszystko",
    "tr": "Hepsi",
    "nl": "Allemaal",
    "ro": "Toate",
    "cs": "všechny",
    "sv": "Alla",
    "hu": "Mind",
    "da": "Alle",
    "fi": "Kaikki",
    "no": "Alle",
    "sk": "Všetky",
    "hr": "sve",
    "bs": "Sve",
    "sr": "Све",
    "bg": "Всички",
    "el": "Όλα",
    "sq": "Të gjitha",
    "lt": "Visi",
    "sl": "Vse",
    "lv": "Visi",
    "et": "Kõik",
    "mk": "Сите",
    "ca": "Tots",
    "eu": "Denak",
    "gl": "Todos",
    "cy": "Pawb",
    "is": "Allt",
    "ga": "Gach",
    "mt": "Kollha",
    "lb": "All",
    "ja": "すべて",
    "ko": "모두",
    "zh-tw": "全部"
  },
  "确认预约": {
    "en": "Confirm reservation",
    "es": "Confirmar reserva",
    "fr": "Confirmer la réservation",
    "de": "Reservierung bestätigen",
    "it": "Conferma la prenotazione",
    "pt": "Confirmar reserva",
    "ru": "Подтвердить бронирование",
    "uk": "Підтвердити бронювання",
    "pl": "Potwierdź rezerwację",
    "tr": "Rezervasyonu onayla",
    "nl": "Bevestig reservering",
    "ro": "Confirmați rezervarea",
    "cs": "Potvrďte rezervaci",
    "sv": "Bekräfta bokningen",
    "hu": "Foglalás megerősítése",
    "da": "Bekræft reservation",
    "fi": "Vahvista varaus",
    "no": "Bekreft reservasjon",
    "sk": "Potvrďte rezerváciu",
    "hr": "Potvrdite rezervaciju",
    "bs": "Potvrdite rezervaciju",
    "sr": "Потврдите резервацију",
    "bg": "Потвърдете резервацията",
    "el": "Επιβεβαίωση κράτησης",
    "sq": "Konfirmo rezervimin",
    "lt": "Patvirtinti rezervaciją",
    "sl": "Potrdite rezervacijo",
    "lv": "Apstipriniet rezervāciju",
    "et": "Kinnitage broneering",
    "mk": "Потврдете ја резервацијата",
    "ca": "Confirmeu la reserva",
    "eu": "Berretsi erreserba",
    "gl": "Confirmar reserva",
    "cy": "Cadarnhewch yr archeb",
    "is": "Staðfestu pöntun",
    "ga": "Deimhnigh an áirithint",
    "mt": "Ikkonferma r-riżerva",
    "lb": "Confirméieren Reservatioun",
    "ja": "予約を確認する",
    "ko": "예약 확인",
    "zh-tw": "確認預約"
  },
  "完成预约": {
    "en": "Complete the appointment",
    "es": "Completa la cita",
    "fr": "Compléter le rendez-vous",
    "de": "Schließen Sie den Termin ab",
    "it": "Completa l'appuntamento",
    "pt": "Conclua o compromisso",
    "ru": "Завершить встречу",
    "uk": "Завершити зустріч",
    "pl": "Dokończ spotkanie",
    "tr": "Randevuyu tamamla",
    "nl": "Maak de afspraak af",
    "ro": "Finalizați programarea",
    "cs": "Dokončete schůzku",
    "sv": "Slutför mötet",
    "hu": "Töltse ki a találkozót",
    "da": "Gennemfør aftalen",
    "fi": "Suorita tapaaminen loppuun",
    "no": "Fullfør avtalen",
    "sk": "Dokončite stretnutie",
    "hr": "Završite termin",
    "bs": "Završite termin",
    "sr": "Завршите термин",
    "bg": "Завършете срещата",
    "el": "Ολοκληρώστε το ραντεβού",
    "sq": "Plotësoni takimin",
    "lt": "Užbaikite susitikimą",
    "sl": "Dokončajte sestanek",
    "lv": "Pabeidziet tikšanos",
    "et": "Viige kohtumine lõpule",
    "mk": "Завршете го состанокот",
    "ca": "Completa la cita",
    "eu": "Osatu hitzordua",
    "gl": "Completa a cita",
    "cy": "Cwblhewch yr apwyntiad",
    "is": "Ljúktu við skipunina",
    "ga": "Críochnaigh an coinne",
    "mt": "Imla l-appuntament",
    "lb": "Fëllt de Rendez-vous aus",
    "ja": "予定を完了する",
    "ko": "약속을 완료하세요",
    "zh-tw": "完成預約"
  },
  "取消预约": {
    "en": "Cancel reservation",
    "es": "Cancelar reserva",
    "fr": "Annuler la réservation",
    "de": "Reservierung stornieren",
    "it": "Cancella la prenotazione",
    "pt": "Cancelar reserva",
    "ru": "Отменить бронирование",
    "uk": "Скасувати бронювання",
    "pl": "Anuluj rezerwację",
    "tr": "Rezervasyonu iptal et",
    "nl": "Reservering annuleren",
    "ro": "Anulați rezervarea",
    "cs": "Zrušit rezervaci",
    "sv": "Avboka bokning",
    "hu": "Foglalás lemondása",
    "da": "Annuller reservation",
    "fi": "Peruuta varaus",
    "no": "Kanseller reservasjon",
    "sk": "Zrušiť rezerváciu",
    "hr": "Otkaži rezervaciju",
    "bs": "Otkažite rezervaciju",
    "sr": "Откажите резервацију",
    "bg": "Отмени резервация",
    "el": "Ακύρωση κράτησης",
    "sq": "Anuloni rezervimin",
    "lt": "Atšaukti rezervaciją",
    "sl": "Prekliči rezervacijo",
    "lv": "Atcelt rezervāciju",
    "et": "Tühista broneering",
    "mk": "Откажете ја резервацијата",
    "ca": "Cancel·la la reserva",
    "eu": "Erreserba bertan behera utzi",
    "gl": "Cancelar reserva",
    "cy": "Canslo archeb",
    "is": "Hætta við pöntun",
    "ga": "Cealaigh áirithint",
    "mt": "Ikkanċella riżervazzjoni",
    "lb": "Reservatioun annuléieren",
    "ja": "予約をキャンセルする",
    "ko": "예약 취소",
    "zh-tw": "取消預約"
  },
  "恢复预约": {
    "en": "Resume appointment",
    "es": "Reanudar cita",
    "fr": "Reprendre rendez-vous",
    "de": "Termin fortsetzen",
    "it": "Riprendere l'appuntamento",
    "pt": "Retomar compromisso",
    "ru": "Возобновить встречу",
    "uk": "Відновити зустріч",
    "pl": "Wznów spotkanie",
    "tr": "Randevuyu devam ettir",
    "nl": "Afspraak hervatten",
    "ro": "Reluați programarea",
    "cs": "Obnovit schůzku",
    "sv": "Återuppta mötet",
    "hu": "Találkozó folytatása",
    "da": "Genoptag aftalen",
    "fi": "Jatka tapaamista",
    "no": "Gjenoppta avtalen",
    "sk": "Obnoviť schôdzku",
    "hr": "Nastavi termin",
    "bs": "Nastavi zakazivanje",
    "sr": "Настави заказивање",
    "bg": "Възобновете срещата",
    "el": "Συνέχιση ραντεβού",
    "sq": "Rifilloni takimin",
    "lt": "Tęsti susitikimą",
    "sl": "Nadaljuj sestanek",
    "lv": "Atsākt tikšanos",
    "et": "Jätka kohtumist",
    "mk": "Продолжете со состанокот",
    "ca": "Reprendre la cita",
    "eu": "Hitzordua berrekin",
    "gl": "Retomar cita",
    "cy": "Ailddechrau apwyntiad",
    "is": "Halda aftur skipun",
    "ga": "Lean coinne",
    "mt": "Ibda l-appuntament",
    "lb": "Rendez-vous weider",
    "ja": "予約を再開する",
    "ko": "약속 재개",
    "zh-tw": "恢复預約"
  },
  "取消确认": {
    "en": "Cancel confirmation",
    "es": "Cancelar confirmación",
    "fr": "Annuler la confirmation",
    "de": "Bestätigung abbrechen",
    "it": "Annulla conferma",
    "pt": "Cancelar confirmação",
    "ru": "Отменить подтверждение",
    "uk": "Скасувати підтвердження",
    "pl": "Anuluj potwierdzenie",
    "tr": "Onayı iptal et",
    "nl": "Bevestiging annuleren",
    "ro": "Anulați confirmarea",
    "cs": "Zrušit potvrzení",
    "sv": "Avbryt bekräftelse",
    "hu": "A megerősítés visszavonása",
    "da": "Annuller bekræftelse",
    "fi": "Peruuta vahvistus",
    "no": "Avbryt bekreftelsen",
    "sk": "Zrušiť potvrdenie",
    "hr": "Odustani od potvrde",
    "bs": "Otkažite potvrdu",
    "sr": "Откажите потврду",
    "bg": "Отказ от потвърждението",
    "el": "Ακύρωση επιβεβαίωσης",
    "sq": "Anulo konfirmimin",
    "lt": "Atšaukti patvirtinimą",
    "sl": "Prekliči potrditev",
    "lv": "Atcelt apstiprinājumu",
    "et": "Tühista kinnitus",
    "mk": "Откажете ја потврдата",
    "ca": "Cancel·la la confirmació",
    "eu": "Berrespena bertan behera utzi",
    "gl": "Cancelar a confirmación",
    "cy": "Canslo cadarnhad",
    "is": "Hætta við staðfestingu",
    "ga": "Cealaigh deimhniú",
    "mt": "Ikkanċella l-konferma",
    "lb": "Ofbriechen Confirmatiouns",
    "ja": "キャンセル確認",
    "ko": "취소 확인",
    "zh-tw": "取消確認"
  },
  "取消完成": {
    "en": "Cancellation completed",
    "es": "Cancelación completada",
    "fr": "Annulation terminée",
    "de": "Stornierung abgeschlossen",
    "it": "Cancellazione completata",
    "pt": "Cancelamento concluído",
    "ru": "Отмена завершена",
    "uk": "Скасування завершено",
    "pl": "Anulowanie zakończone",
    "tr": "İptal tamamlandı",
    "nl": "Annulering voltooid",
    "ro": "Anularea a fost finalizată",
    "cs": "Zrušení dokončeno",
    "sv": "Avbokningen slutförd",
    "hu": "A törlés befejeződött",
    "da": "Annullering gennemført",
    "fi": "Peruutus suoritettu",
    "no": "Avbestilling fullført",
    "sk": "Zrušenie dokončené",
    "hr": "Otkazivanje dovršeno",
    "bs": "Otkazivanje je završeno",
    "sr": "Отказивање је завршено",
    "bg": "Анулирането е завършено",
    "el": "Η ακύρωση ολοκληρώθηκε",
    "sq": "Anulimi përfundoi",
    "lt": "Atšaukimas baigtas",
    "sl": "Preklic končan",
    "lv": "Atcelšana pabeigta",
    "et": "Tühistamine lõpetatud",
    "mk": "Откажувањето е завршено",
    "ca": "Cancel·lació completada",
    "eu": "Ezeztapena amaitu da",
    "gl": "Cancelación completada",
    "cy": "Canslo wedi'i gwblhau",
    "is": "Afpöntun lokið",
    "ga": "Cealú curtha i gcrích",
    "mt": "Kanċellazzjoni tlestiet",
    "lb": "Annulatioun fäerdeg",
    "ja": "キャンセル完了",
    "ko": "취소 완료",
    "zh-tw": "取消完成"
  },
  "详情": {
    "en": "Details",
    "es": "Detalles",
    "fr": "Détails",
    "de": "Details",
    "it": "Dettagli",
    "pt": "Detalhes",
    "ru": "Подробности",
    "uk": "Подробиці",
    "pl": "Szczegóły",
    "tr": "Ayrıntılar",
    "nl": "Details",
    "ro": "Detalii",
    "cs": "Podrobnosti",
    "sv": "Detaljer",
    "hu": "Részletek",
    "da": "Detaljer",
    "fi": "Yksityiskohdat",
    "no": "Detaljer",
    "sk": "Podrobnosti",
    "hr": "pojedinosti",
    "bs": "Detalji",
    "sr": "Детаљи",
    "bg": "Подробности",
    "el": "Λεπτομέρειες",
    "sq": "Detajet",
    "lt": "Detalės",
    "sl": "Podrobnosti",
    "lv": "Sīkāka informācija",
    "et": "Üksikasjad",
    "mk": "Детали",
    "ca": "Detalls",
    "eu": "Xehetasunak",
    "gl": "Detalles",
    "cy": "Manylion",
    "is": "Upplýsingar",
    "ga": "Sonraí",
    "mt": "Dettalji",
    "lb": "Detailer",
    "ja": "詳細",
    "ko": "세부정보",
    "zh-tw": "詳情"
  },
  "关闭": {
    "en": "close",
    "es": "cerrar",
    "fr": "fermer",
    "de": "schließen",
    "it": "chiudere",
    "pt": "fechar",
    "ru": "закрыть",
    "uk": "закрити",
    "pl": "blisko",
    "tr": "kapat",
    "nl": "dichtbij",
    "ro": "aproape",
    "cs": "zavřít",
    "sv": "nära",
    "hu": "bezárni",
    "da": "tæt på",
    "fi": "sulje",
    "no": "lukke",
    "sk": "zavrieť",
    "hr": "zatvoriti",
    "bs": "zatvori",
    "sr": "затворити",
    "bg": "близо",
    "el": "κλείσιμο",
    "sq": "mbyll",
    "lt": "uždaryti",
    "sl": "blizu",
    "lv": "aizveriet",
    "et": "sulgeda",
    "mk": "затвори",
    "ca": "tancar",
    "eu": "itxi",
    "gl": "pechar",
    "cy": "cau",
    "is": "loka",
    "ga": "dhúnadh",
    "mt": "qrib",
    "lb": "zoumaachen",
    "ja": "閉じる",
    "ko": "닫기",
    "zh-tw": "關閉"
  },
  "保存": {
    "en": "save",
    "es": "guardar",
    "fr": "enregistrer",
    "de": "sparen",
    "it": "salvare",
    "pt": "salvar",
    "ru": "сохранить",
    "uk": "зберегти",
    "pl": "zapisz",
    "tr": "kaydet",
    "nl": "opslaan",
    "ro": "salva",
    "cs": "uložit",
    "sv": "spara",
    "hu": "menteni",
    "da": "gem",
    "fi": "tallenna",
    "no": "lagre",
    "sk": "uložiť",
    "hr": "spasiti",
    "bs": "spasiti",
    "sr": "сачувати",
    "bg": "спаси",
    "el": "αποθηκεύσετε",
    "sq": "kurseni",
    "lt": "išsaugoti",
    "sl": "shraniti",
    "lv": "saglabāt",
    "et": "salvestada",
    "mk": "спаси",
    "ca": "guardar",
    "eu": "gorde",
    "gl": "gardar",
    "cy": "arbed",
    "is": "vista",
    "ga": "shábháil",
    "mt": "ħlief",
    "lb": "späicheren",
    "ja": "保存する",
    "ko": "저장",
    "zh-tw": "保存"
  },
  "会话": {
    "en": "session",
    "es": "sesión",
    "fr": "séance",
    "de": "Sitzung",
    "it": "sessione",
    "pt": "sessão",
    "ru": "сессия",
    "uk": "сесії",
    "pl": "sesja",
    "tr": "oturum",
    "nl": "sessie",
    "ro": "sesiune",
    "cs": "zasedání",
    "sv": "session",
    "hu": "ülésén",
    "da": "session",
    "fi": "istunto",
    "no": "økt",
    "sk": "relácie",
    "hr": "sjednica",
    "bs": "sjednici",
    "sr": "седници",
    "bg": "сесия",
    "el": "συνεδρία",
    "sq": "sesioni",
    "lt": "sesija",
    "sl": "sejo",
    "lv": "sesija",
    "et": "istungil",
    "mk": "сесија",
    "ca": "sessió",
    "eu": "saioa",
    "gl": "sesión",
    "cy": "sesiwn",
    "is": "fundur",
    "ga": "seisiún",
    "mt": "sessjoni",
    "lb": "Sëtzung",
    "ja": "セッション",
    "ko": "세션",
    "zh-tw": "會話"
  },
  "会话，有新消息": {
    "en": "Conversation, new message",
    "es": "Conversación, nuevo mensaje.",
    "fr": "Conversation, nouveau message",
    "de": "Gespräch, neue Nachricht",
    "it": "Conversazione, nuovo messaggio",
    "pt": "Conversa, nova mensagem",
    "ru": "Разговор, новое сообщение",
    "uk": "Розмова, нове повідомлення",
    "pl": "Rozmowa, nowa wiadomość",
    "tr": "Konuşma, yeni mesaj",
    "nl": "Gesprek, nieuw bericht",
    "ro": "Conversație, mesaj nou",
    "cs": "Konverzace, nová zpráva",
    "sv": "Konversation, nytt meddelande",
    "hu": "Beszélgetés, új üzenet",
    "da": "Samtale, ny besked",
    "fi": "Keskustelu, uusi viesti",
    "no": "Samtale, ny melding",
    "sk": "Rozhovor, nová správa",
    "hr": "Razgovor, nova poruka",
    "bs": "Razgovor, nova poruka",
    "sr": "Разговор, нова порука",
    "bg": "Разговор, ново съобщение",
    "el": "Συζήτηση, νέο μήνυμα",
    "sq": "Bisedë, mesazh i ri",
    "lt": "Pokalbis, nauja žinutė",
    "sl": "Pogovor, novo sporočilo",
    "lv": "Saruna, jauna ziņa",
    "et": "Vestlus, uus sõnum",
    "mk": "Разговор, нова порака",
    "ca": "Conversa, missatge nou",
    "eu": "Elkarrizketa, mezu berria",
    "gl": "Conversa, nova mensaxe",
    "cy": "Sgwrs, neges newydd",
    "is": "Samtal, ný skilaboð",
    "ga": "Comhrá, teachtaireacht nua",
    "mt": "Konversazzjoni, messaġġ ġdid",
    "lb": "Gespréich, neie Message",
    "ja": "会話、新しいメッセージ",
    "ko": "대화, 새 메시지",
    "zh-tw": "會話，有新消息"
  },
  "名片夹": {
    "en": "business card holder",
    "es": "titular de la tarjeta de visita",
    "fr": "titulaire de la carte de visite",
    "de": "Visitenkartenhalter",
    "it": "porta biglietti da visita",
    "pt": "titular do cartão de visita",
    "ru": "держатель визитной карточки",
    "uk": "візитниця",
    "pl": "posiadacz wizytówki",
    "tr": "kartvizitlik",
    "nl": "houder voor visitekaartjes",
    "ro": "suport card de vizita",
    "cs": "držák na vizitky",
    "sv": "visitkortshållare",
    "hu": "névjegykártya tartó",
    "da": "visitkortholder",
    "fi": "käyntikortin pidike",
    "no": "visittkortholder",
    "sk": "držiak na vizitky",
    "hr": "držač posjetnice",
    "bs": "držač za vizit karte",
    "sr": "држач визиткарте",
    "bg": "държач за визитка",
    "el": "κάτοχος επαγγελματικής κάρτας",
    "sq": "mbajtës i kartës së biznesit",
    "lt": "vizitinės kortelės laikiklis",
    "sl": "držalo za vizitke",
    "lv": "vizītkaršu turētājs",
    "et": "visiitkaardi hoidja",
    "mk": "држач за визит-картичка",
    "ca": "titular de la targeta de visita",
    "eu": "bisita txartelaren titularra",
    "gl": "porta tarxetas de visita",
    "cy": "deiliad cerdyn busnes",
    "is": "nafnspjaldahafa",
    "ga": "sealbhóir cárta gnó",
    "mt": "detentur ta' karta tan-negozju",
    "lb": "Visittekaart Titulaire",
    "ja": "名刺ホルダー",
    "ko": "명함 홀더",
    "zh-tw": "名片夹"
  },
  "我的名片夹": {
    "en": "my business card holder",
    "es": "mi tarjetero",
    "fr": "mon porte-carte de visite",
    "de": "mein Visitenkartenhalter",
    "it": "il mio porta biglietti da visita",
    "pt": "titular do meu cartão de visita",
    "ru": "моя визитница",
    "uk": "моя візитниця",
    "pl": "mój wizytownik",
    "tr": "kartvizitliğim",
    "nl": "mijn visitekaartjehouder",
    "ro": "suportul meu de carte de vizită",
    "cs": "držitel mé vizitky",
    "sv": "min visitkortshållare",
    "hu": "névjegykártya-tartóm",
    "da": "min visitkortholder",
    "fi": "käyntikorttini haltija",
    "no": "visittkortholderen min",
    "sk": "držiak mojej vizitky",
    "hr": "držač moje posjetnice",
    "bs": "držač moje vizit karte",
    "sr": "држач моје визит карте",
    "bg": "моя визитка",
    "el": "κάτοχος της επαγγελματικής μου κάρτας",
    "sq": "mbajtësi i kartës time të biznesit",
    "lt": "mano vizitinės kortelės laikiklis",
    "sl": "imetnik moje vizitke",
    "lv": "mans vizītkartes turētājs",
    "et": "minu visiitkaardi omanik",
    "mk": "мојот држач за визит-картичка",
    "ca": "el meu titular de la targeta de visita",
    "eu": "nire bisita txartelaren titularra",
    "gl": "a miña tarxeta de visita",
    "cy": "deiliad fy ngherdyn busnes",
    "is": "nafnspjaldahafann minn",
    "ga": "sealbhóir mo chárta gnó",
    "mt": "id-detentur tal-karta tan-negozju tiegħi",
    "lb": "meng Visittekaart Titulaire",
    "ja": "私の名刺ホルダー",
    "ko": "내 명함 지갑",
    "zh-tw": "我的名片夹"
  },
  "数据统计": {
    "en": "Statistics",
    "es": "Estadísticas",
    "fr": "Statistiques",
    "de": "Statistiken",
    "it": "Statistiche",
    "pt": "Estatísticas",
    "ru": "Статистика",
    "uk": "Статистика",
    "pl": "Statystyki",
    "tr": "İstatistikler",
    "nl": "Statistieken",
    "ro": "Statistici",
    "cs": "Statistiky",
    "sv": "Statistik",
    "hu": "Statisztika",
    "da": "Statistik",
    "fi": "Tilastot",
    "no": "Statistikk",
    "sk": "Štatistiky",
    "hr": "Statistika",
    "bs": "Statistika",
    "sr": "Статистика",
    "bg": "Статистика",
    "el": "Στατιστικά στοιχεία",
    "sq": "Statistikat",
    "lt": "Statistika",
    "sl": "Statistika",
    "lv": "Statistika",
    "et": "Statistika",
    "mk": "Статистика",
    "ca": "Estadístiques",
    "eu": "Estatistika",
    "gl": "Estatísticas",
    "cy": "Ystadegau",
    "is": "Tölfræði",
    "ga": "Staitisticí",
    "mt": "Statistika",
    "lb": "Statistiken",
    "ja": "統計",
    "ko": "통계",
    "zh-tw": "數據统计"
  },
  "预约管理": {
    "en": "Appointment management",
    "es": "Gestión de citas",
    "fr": "Gestion des rendez-vous",
    "de": "Terminverwaltung",
    "it": "Gestione degli appuntamenti",
    "pt": "Gerenciamento de compromissos",
    "ru": "Управление назначениями",
    "uk": "Управління призначеннями",
    "pl": "Zarządzanie spotkaniami",
    "tr": "Randevu yönetimi",
    "nl": "Afsprakenbeheer",
    "ro": "Managementul numirilor",
    "cs": "Řízení schůzek",
    "sv": "Utnämningshantering",
    "hu": "Időpontkezelés",
    "da": "Udnævnelseshåndtering",
    "fi": "Tapaamisten hallinta",
    "no": "Avtalebehandling",
    "sk": "Manažment vymenovania",
    "hr": "Upravljanje terminima",
    "bs": "Upravljanje terminima",
    "sr": "Управљање именовањем",
    "bg": "Управление на срещи",
    "el": "Διαχείριση ραντεβού",
    "sq": "Menaxhimi i takimeve",
    "lt": "Paskyrimų valdymas",
    "sl": "Upravljanje sestankov",
    "lv": "Tikšanās vadība",
    "et": "Kohtumiste juhtimine",
    "mk": "Управување со состаноци",
    "ca": "Gestió de cites",
    "eu": "Hitzorduen kudeaketa",
    "gl": "Xestión de citas",
    "cy": "Rheoli apwyntiadau",
    "is": "Skipunarstjórnun",
    "ga": "Bainistíocht ceapacháin",
    "mt": "Ġestjoni tal-ħatra",
    "lb": "Rendez-vous Gestioun",
    "ja": "予約管理",
    "ko": "약속관리",
    "zh-tw": "預約管理"
  },
  "生意": {
    "en": "business",
    "es": "negocio",
    "fr": "entreprise",
    "de": "Geschäft",
    "it": "affari",
    "pt": "negócio",
    "ru": "бизнес",
    "uk": "бізнес",
    "pl": "biznes",
    "tr": "iş",
    "nl": "zaken",
    "ro": "afaceri",
    "cs": "podnikání",
    "sv": "företag",
    "hu": "üzlet",
    "da": "forretning",
    "fi": "liiketoimintaa",
    "no": "virksomhet",
    "sk": "podnikania",
    "hr": "poslovanje",
    "bs": "posao",
    "sr": "посао",
    "bg": "бизнес",
    "el": "επιχείρηση",
    "sq": "biznesi",
    "lt": "verslui",
    "sl": "poslovanje",
    "lv": "bizness",
    "et": "äri",
    "mk": "бизнис",
    "ca": "negoci",
    "eu": "negozioa",
    "gl": "negocio",
    "cy": "busnes",
    "is": "viðskipti",
    "ga": "gnó",
    "mt": "negozju",
    "lb": "Geschäft",
    "ja": "ビジネス",
    "ko": "사업",
    "zh-tw": "生意"
  },
  "自己": {
    "en": "myself",
    "es": "yo mismo",
    "fr": "moi-même",
    "de": "ich selbst",
    "it": "me stesso",
    "pt": "eu mesmo",
    "ru": "я сам",
    "uk": "себе",
    "pl": "ja",
    "tr": "kendim",
    "nl": "ikzelf",
    "ro": "eu însumi",
    "cs": "já sám",
    "sv": "mig själv",
    "hu": "magamat",
    "da": "mig selv",
    "fi": "itseäni",
    "no": "meg selv",
    "sk": "ja",
    "hr": "sebe",
    "bs": "sebe",
    "sr": "себе",
    "bg": "себе си",
    "el": "τον εαυτό μου",
    "sq": "veten time",
    "lt": "aš pats",
    "sl": "sebe",
    "lv": "sevi",
    "et": "mina ise",
    "mk": "себеси",
    "ca": "jo mateix",
    "eu": "neure burua",
    "gl": "eu mesmo",
    "cy": "fy hun",
    "is": "sjálfan mig",
    "ga": "mé féin",
    "mt": "jien stess",
    "lb": "selwer",
    "ja": "私自身",
    "ko": "나 자신",
    "zh-tw": "自己"
  },
  "聊天列表": {
    "en": "chat list",
    "es": "lista de chat",
    "fr": "liste de discussion",
    "de": "Chat-Liste",
    "it": "elenco chat",
    "pt": "lista de bate-papo",
    "ru": "список чатов",
    "uk": "список чату",
    "pl": "lista czatów",
    "tr": "sohbet listesi",
    "nl": "chatlijst",
    "ro": "lista de chat",
    "cs": "seznam chatu",
    "sv": "chattlista",
    "hu": "chat lista",
    "da": "chat liste",
    "fi": "chat-lista",
    "no": "chatteliste",
    "sk": "zoznam chatov",
    "hr": "lista za razgovor",
    "bs": "chat lista",
    "sr": "листа за ћаскање",
    "bg": "списък за чат",
    "el": "λίστα συνομιλιών",
    "sq": "lista e bisedave",
    "lt": "pokalbių sąrašas",
    "sl": "seznam klepetalnic",
    "lv": "tērzēšanas saraksts",
    "et": "vestlusloend",
    "mk": "листа на разговори",
    "ca": "llista de xat",
    "eu": "txat-zerrenda",
    "gl": "lista de chat",
    "cy": "rhestr sgwrsio",
    "is": "spjalllista",
    "ga": "liosta comhrá",
    "mt": "lista taċ-chat",
    "lb": "Chat Lëscht",
    "ja": "チャットリスト",
    "ko": "채팅 목록",
    "zh-tw": "聊天列表"
  },
  "预约详情": {
    "en": "Appointment details",
    "es": "Detalles de la cita",
    "fr": "Détails du rendez-vous",
    "de": "Termindetails",
    "it": "Dettagli dell'appuntamento",
    "pt": "Detalhes do compromisso",
    "ru": "Детали встречи",
    "uk": "Деталі призначення",
    "pl": "Szczegóły spotkania",
    "tr": "Randevu ayrıntıları",
    "nl": "Afspraakdetails",
    "ro": "Detalii programare",
    "cs": "Podrobnosti o schůzce",
    "sv": "Utnämningsdetaljer",
    "hu": "Időpont egyeztetés részletei",
    "da": "Detaljer om aftale",
    "fi": "Ajanvaraustiedot",
    "no": "Avtaledetaljer",
    "sk": "Podrobnosti o stretnutí",
    "hr": "Detalji termina",
    "bs": "Detalji termina",
    "sr": "Детаљи термина",
    "bg": "Подробности за срещата",
    "el": "Λεπτομέρειες ραντεβού",
    "sq": "Detajet e takimit",
    "lt": "Išsami susitikimo informacija",
    "sl": "Podrobnosti o terminu",
    "lv": "Tikšanās informācija",
    "et": "Kohtumise üksikasjad",
    "mk": "Детали за закажување",
    "ca": "Detalls de la cita",
    "eu": "Hitzorduaren xehetasunak",
    "gl": "Detalles da cita",
    "cy": "Manylion yr apwyntiad",
    "is": "Upplýsingar um stefnumót",
    "ga": "Sonraí an cheapacháin",
    "mt": "Dettalji tal-ħatra",
    "lb": "Rendez-vous Detailer",
    "ja": "予約の詳細",
    "ko": "약속 세부정보",
    "zh-tw": "預約詳情"
  },
  "还没有匹配到预约记录。": {
    "en": "No appointment record has been matched yet.",
    "es": "Aún no se ha coincidido ningún registro de citas.",
    "fr": "Aucun enregistrement de rendez-vous n'a encore été associé.",
    "de": "Es wurde noch kein Termindatensatz abgeglichen.",
    "it": "Nessun record di appuntamento è stato ancora abbinato.",
    "pt": "Nenhum registro de compromisso foi correspondido ainda.",
    "ru": "Запись о назначении пока не найдена.",
    "uk": "Жодного запису про зустрічі ще не зіставлено.",
    "pl": "Żaden rekord spotkań nie został jeszcze dopasowany.",
    "tr": "Henüz randevu kaydı eşleşmedi.",
    "nl": "Er is nog geen afspraakrecord gematcht.",
    "ro": "Nicio înregistrare nu a fost egalată încă.",
    "cs": "Dosud nebyl nalezen žádný záznam schůzky.",
    "sv": "Inget mötesrekord har matchats ännu.",
    "hu": "Még nem egyeztetett időpontot.",
    "da": "Ingen aftalerekord er blevet matchet endnu.",
    "fi": "Tapaamistaietuetta ei ole vielä löydetty.",
    "no": "Ingen avtalepost har blitt matchet ennå.",
    "sk": "Zatiaľ nebol nájdený žiadny záznam stretnutia.",
    "hr": "Nijedan zapis o terminima još nije usklađen.",
    "bs": "Još nije pronađen nijedan zapis o terminima.",
    "sr": "Још увек није пронађен ниједан запис о терминима.",
    "bg": "Все още няма съответстващ запис на срещи.",
    "el": "Κανένα ραντεβού δεν έχει αντιστοιχιστεί ακόμα.",
    "sq": "Asnjë rekord takimi nuk është përputhur ende.",
    "lt": "Dar nebuvo suderintas joks susitikimo įrašas.",
    "sl": "Noben zapis o terminih se še ni ujemal.",
    "lv": "Vēl nav atrasts neviens tikšanās ieraksts.",
    "et": "Ühtegi kohtumise rekordit pole veel leitud.",
    "mk": "Сè уште не е усогласен записот за состаноци.",
    "ca": "Encara no s'ha coincidit cap registre de cites.",
    "eu": "Oraindik ez da hitzorduen erregistrorik bat etorri.",
    "gl": "Aínda non se coincidiu ningún rexistro de citas.",
    "cy": "Nid oes unrhyw gofnod apwyntiad wedi'i baru eto.",
    "is": "Engin stefnumótaskrá hefur enn náðst.",
    "ga": "Níor mheaitseáil aon taifead coinní fós.",
    "mt": "L-ebda rekord ta' appuntamenti ma ġie mqabbel.",
    "lb": "Kee Rendez-vous Rekord gouf nach gepasst.",
    "ja": "一致する予定記録はまだありません。",
    "ko": "아직 일치하는 약속 기록이 없습니다.",
    "zh-tw": "还没有匹配到預約记录。"
  },
  "正在读取预约记录...": {
    "en": "Reading reservation records...",
    "es": "Leyendo registros de reserva...",
    "fr": "Lecture des dossiers de réservation...",
    "de": "Reservierungsdatensätze werden gelesen...",
    "it": "Lettura dei record delle prenotazioni...",
    "pt": "Lendo registros de reserva...",
    "ru": "Чтение записей резервирования...",
    "uk": "Читання записів бронювання...",
    "pl": "Odczytywanie zapisów rezerwacji...",
    "tr": "Rezervasyon kayıtları okunuyor...",
    "nl": "Reserveringsgegevens lezen...",
    "ro": "Se citesc înregistrările rezervărilor...",
    "cs": "Čtení rezervačních záznamů...",
    "sv": "Läser bokningsuppgifter...",
    "hu": "Foglalási rekordok olvasása...",
    "da": "Læser reservationsoptegnelser...",
    "fi": "Luetaan varaustietueita...",
    "no": "Leser reservasjonsposter...",
    "sk": "Čítanie záznamov o rezerváciách...",
    "hr": "Čitanje zapisa o rezervacijama...",
    "bs": "Čitanje evidencije rezervacija...",
    "sr": "Читање записа о резервацијама...",
    "bg": "Записите за резервации се четат...",
    "el": "Ανάγνωση αρχείων κρατήσεων...",
    "sq": "Leximi i të dhënave të rezervimeve...",
    "lt": "Skaitomi rezervavimo įrašai...",
    "sl": "Branje evidence rezervacij ...",
    "lv": "Notiek rezervāciju ierakstu lasīšana...",
    "et": "Broneeringukirjete lugemine...",
    "mk": "Читање евиденција за резервации...",
    "ca": "Llegint els registres de la reserva...",
    "eu": "Erreserben erregistroak irakurtzen...",
    "gl": "Lendo rexistros de reserva...",
    "cy": "Darllen cofnodion cadw...",
    "is": "Les bókunarfærslur...",
    "ga": "Taifid áirithinte á léamh...",
    "mt": "Qari tar-rekords tar-riżerva...",
    "lb": "Liesen Reservatioun records ...",
    "ja": "予約記録を読み込んでいます...",
    "ko": "예약 기록을 읽는 중...",
    "zh-tw": "正在读取預約记录..."
  },
  "当前商户信息未准备好，暂时无法读取预约管理。": {
    "en": "The current merchant information is not ready and the reservation management cannot be read at the moment.",
    "es": "La información actual del comerciante no está lista y la gestión de reservas no se puede leer en este momento.",
    "fr": "Les informations actuelles du commerçant ne sont pas prêtes et la gestion des réservations n'est pas lisible pour le moment.",
    "de": "Die aktuellen Händlerinformationen sind noch nicht verfügbar und die Reservierungsverwaltung kann derzeit nicht gelesen werden.",
    "it": "Le attuali informazioni sul commerciante non sono pronte e la gestione delle prenotazioni non può essere letta al momento.",
    "pt": "As informações atuais do comerciante não estão prontas e o gerenciamento de reservas não pode ser lido no momento.",
    "ru": "Текущая информация о продавце не готова, и в данный момент невозможно прочитать управление резервированием.",
    "uk": "Поточна інформація про продавця не готова, і керування бронюванням наразі неможливо прочитати.",
    "pl": "Aktualne informacje o sprzedawcy nie są gotowe i w tej chwili nie można odczytać zarządzania rezerwacjami.",
    "tr": "Güncel üye işyeri bilgileri hazır değildir ve rezervasyon yönetimi şu anda okunamamaktadır.",
    "nl": "De actuele handelaarsinformatie is nog niet gereed en het reserveringsbeheer is momenteel niet in te lezen.",
    "ro": "Informațiile curente ale comerciantului nu sunt gata și gestionarea rezervării nu poate fi citită momentan.",
    "cs": "Aktuální informace o obchodníkovi nejsou připraveny a správu rezervací v tuto chvíli nelze přečíst.",
    "sv": "Den aktuella handlarinformationen är inte klar och bokningshanteringen kan inte läsas för tillfället.",
    "hu": "A jelenlegi kereskedői információk nem állnak rendelkezésre, és a foglaláskezelés jelenleg nem olvasható.",
    "da": "Den aktuelle købmandsinformation er ikke klar, og reservationsstyringen kan ikke læses i øjeblikket.",
    "fi": "Nykyiset kauppiastiedot eivät ole valmiita, eikä varaushallintaa voida tällä hetkellä lukea.",
    "no": "Den gjeldende selgerinformasjonen er ikke klar og reservasjonsadministrasjonen kan ikke leses for øyeblikket.",
    "sk": "Aktuálne informácie o obchodníkovi nie sú pripravené a správu rezervácií momentálne nie je možné prečítať.",
    "hr": "Trenutačni podaci o trgovcu nisu spremni i trenutno se ne može pročitati upravljanje rezervacijama.",
    "bs": "Trenutne informacije o trgovcu nisu spremne i upravljanje rezervacijama trenutno nije moguće pročitati.",
    "sr": "Тренутне информације о трговцу нису спремне и управљање резервацијама тренутно није могуће прочитати.",
    "bg": "Текущата информация за търговеца не е готова и управлението на резервациите не може да бъде прочетено в момента.",
    "el": "Οι τρέχουσες πληροφορίες εμπόρου δεν είναι έτοιμες και δεν είναι δυνατή η ανάγνωση της διαχείρισης κράτησης αυτήν τη στιγμή.",
    "sq": "Informacioni aktual i tregtarit nuk është gati dhe menaxhimi i rezervimit nuk mund të lexohet për momentin.",
    "lt": "Dabartinė prekybininko informacija neparengta ir šiuo metu negalima nuskaityti rezervavimo valdymo.",
    "sl": "Trenutni podatki o trgovcu niso pripravljeni in upravljanja rezervacij trenutno ni mogoče brati.",
    "lv": "Pašreizējā tirgotāja informācija nav gatava, un šobrīd nevar nolasīt rezervācijas vadību.",
    "et": "Praegune kaupmehe info pole valmis ja broneeringuhaldust ei saa hetkel lugeda.",
    "mk": "Тековните информации за трговецот не се подготвени и управувањето со резервациите не може да се прочита во моментов.",
    "ca": "La informació actual del comerciant no està preparada i la gestió de reserves no es pot llegir en aquest moment.",
    "eu": "Merkatariaren uneko informazioa ez dago prest eta momentuz ezin da erreserben kudeaketa irakurri.",
    "gl": "A información actual do comerciante non está lista e a xestión das reservas non se pode ler polo momento.",
    "cy": "Nid yw'r wybodaeth gyfredol am fasnachwr yn barod ac ni ellir darllen y drefn cadw lle ar hyn o bryd.",
    "is": "Núverandi söluaðilaupplýsingar eru ekki tilbúnar og ekki er hægt að lesa bókunarstjórnunina í augnablikinu.",
    "ga": "Níl an fhaisnéis trádálaí reatha réidh agus ní féidir an bhainistíocht áirithinte a léamh faoi láthair.",
    "mt": "L-informazzjoni kurrenti tan-negozjant mhix lesta u l-ġestjoni tar-riżervazzjoni ma tistax tinqara bħalissa.",
    "lb": "Déi aktuell Händlerinformatioun ass net fäerdeg an d'Reservatiounsmanagement kann am Moment net gelies ginn.",
    "ja": "現在加盟店情報が整っておらず、予約管理が閲覧できない状況となっております。",
    "ko": "현재 가맹점 정보가 준비되어 있지 않아 현재 예약관리를 읽을 수 없습니다.",
    "zh-tw": "当前商户信息未准备好，暂时无法读取預約管理。"
  },
  "搜索预约编号 / 店铺 / 项目 / 姓名 / 邮箱 / 电话 / 备注": {
    "en": "Search reservation number/store/item/name/email/phone/notes",
    "es": "Buscar número de reserva/tienda/artículo/nombre/correo electrónico/teléfono/notas",
    "fr": "Rechercher un numéro de réservation/magasin/article/nom/e-mail/téléphone/notes",
    "de": "Suchen Sie nach Reservierungsnummer/Geschäft/Artikel/Name/E-Mail/Telefon/Notizen",
    "it": "Cerca numero di prenotazione/negozio/articolo/nome/e-mail/telefono/note",
    "pt": "Pesquisar número de reserva/loja/item/nome/e-mail/telefone/notas",
    "ru": "Поиск по номеру бронирования/магазину/предмету/имени/электронной почте/телефону/заметкам",
    "uk": "Шукайте номер бронювання/магазин/товар/ім’я/електронну адресу/телефон/примітки",
    "pl": "Wyszukaj numer rezerwacji/sklep/przedmiot/nazwę/e-mail/telefon/notatki",
    "tr": "Rezervasyon numarası/mağaza/ürün/ad/e-posta/telefon/notlarda arama yapın",
    "nl": "Zoek reserveringsnummer/winkel/item/naam/e-mail/telefoon/notities",
    "ro": "Căutați numărul de rezervare/magazin/articol/nume/e-mail/telefon/note",
    "cs": "Vyhledejte číslo rezervace/obchod/položku/jméno/e-mail/telefon/poznámky",
    "sv": "Sök bokningsnummer/butik/vara/namn/e-post/telefon/anteckningar",
    "hu": "A foglalási szám/üzlet/cikk/név/e-mail/telefon/jegyzetek keresése",
    "da": "Søg reservationsnummer/butik/vare/navn/e-mail/telefon/noter",
    "fi": "Hae varausnumero/myymälä/tuote/nimi/sähköposti/puhelin/muistiinpanot",
    "no": "Søk reservasjonsnummer/butikk/vare/navn/e-post/telefon/notater",
    "sk": "Vyhľadajte číslo rezervácie/obchod/položku/meno/e-mail/telefón/poznámky",
    "hr": "Pretražite broj rezervacije/trgovinu/predmet/ime/e-mail/telefon/bilješke",
    "bs": "Pretražite broj rezervacije/trgovinu/stavku/ime/e-mail/telefon/napomene",
    "sr": "Претражите број резервације/продавницу/ставку/име/е-маил/телефон/напомене",
    "bg": "Търсете номер на резервация/магазин/артикул/име/имейл/телефон/бележки",
    "el": "Αναζήτηση αριθμού κράτησης/καταστήματος/αντικείμενο/όνομα/email/τηλέφωνο/σημειώσεις",
    "sq": "Kërkoni numrin e rezervimit/dyqan/artikull/emër/email/telefon/shënime",
    "lt": "Ieškokite rezervacijos numerio/parduotuvės/prekės/vardo/el.pašto/telefono/pastabų",
    "sl": "Poiščite številko rezervacije/trgovino/predmet/ime/e-pošto/telefon/opombe",
    "lv": "Meklēt rezervācijas numuru/veikalu/preces/nosaukumu/e-pastu/tālruni/piezīmes",
    "et": "Otsige broneeringu numbrit/poodi/kaupa/nime/e-posti/telefoni/märkmeid",
    "mk": "Пребарајте број за резервација/продавница/артикал/име/е-пошта/телефон/белешки",
    "ca": "Cerca el número de reserva/botiga/element/nom/correu electrònic/telèfon/notes",
    "eu": "Bilatu erreserba-zenbakia/denda/elementua/izena/posta elektronikoa/telefonoa/oharrak",
    "gl": "Busca número de reserva/tenda/elemento/nome/correo electrónico/teléfono/notas",
    "cy": "Chwilio rhif archeb / storfa / eitem / enw / e-bost / ffôn / nodiadau",
    "is": "Leitaðu að pöntunarnúmeri/verslun/vöru/nafni/netfangi/sími/glósum",
    "ga": "Cuardaigh uimhir áirithinte/siopa/mír/ainm/ríomhphost/guthán/nótaí",
    "mt": "Fittex in-numru tar-riservazzjoni/maħżen/oġġett/isem/email/telefon/noti",
    "lb": "Sich Reservatioun Zuel / Buttek / Artikel / Numm / E-Mail / Telefon / Notizen",
    "ja": "予約番号/店舗/商品/名前/メールアドレス/電話番号/メモを検索",
    "ko": "예약번호/매장/상품/이름/이메일/전화번호/메모사항 검색",
    "zh-tw": "搜尋預約編號 / 店舖 / 項目 / 姓名 / 信箱 / 電話 / 備註"
  },
  "搜索预约号 / 姓名 / 邮箱 / 电话": {
    "en": "Search appointment number / name / email / phone number",
    "es": "Buscar número de cita / nombre / correo electrónico / número de teléfono",
    "fr": "Rechercher numéro de rendez-vous / nom / email / numéro de téléphone",
    "de": "Suchen Sie nach Terminnummer / Name / E-Mail / Telefonnummer",
    "it": "Cerca numero appuntamento/nome/e-mail/numero di telefono",
    "pt": "Pesquisar número / nome / e-mail / número de telefone do agendamento",
    "ru": "Поиск номера встречи / имени / электронной почты / номера телефона",
    "uk": "Шукайте номер зустрічі / ім’я / електронну адресу / номер телефону",
    "pl": "Wyszukaj numer spotkania / imię i nazwisko / adres e-mail / numer telefonu",
    "tr": "Randevu numarasını / adını / e-postasını / telefon numarasını arayın",
    "nl": "Zoek afspraaknummer / naam / e-mail / telefoonnummer",
    "ro": "Căutați numărul de întâlnire / nume / e-mail / număr de telefon",
    "cs": "Vyhledejte číslo schůzky / jméno / e-mail / telefonní číslo",
    "sv": "Sök mötesnummer / namn / e-post / telefonnummer",
    "hu": "Találkozószám / név / e-mail / telefonszám keresése",
    "da": "Søg aftalenummer / navn / email / telefonnummer",
    "fi": "Hae tapaamisnumero / nimi / sähköposti / puhelinnumero",
    "no": "Søk etter avtalenummer / navn / e-post / telefonnummer",
    "sk": "Vyhľadajte číslo stretnutia / meno / e-mail / telefónne číslo",
    "hr": "Pretražite broj termina / ime / e-poštu / broj telefona",
    "bs": "Pretražite broj termina / ime / email / broj telefona",
    "sr": "Претражите број термина / име / имејл / број телефона",
    "bg": "Търсете номер на среща / име / имейл / телефонен номер",
    "el": "Αναζήτηση αριθμού συνάντησης / όνομα / email / αριθμό τηλεφώνου",
    "sq": "Kërkoni numrin e takimit / emrin / emailin / numrin e telefonit",
    "lt": "Ieškokite susitikimo numerio / vardo / el. pašto / telefono numerio",
    "sl": "Poiščite številko sestanka / ime / e-pošto / telefonsko številko",
    "lv": "Meklēt tikšanās numuru / vārdu / e-pastu / tālruņa numuru",
    "et": "Otsige kohtumise numbrit / nime / e-posti / telefoninumbrit",
    "mk": "Пребарајте број на состанок / име / е-пошта / телефонски број",
    "ca": "Cerca número de cita / nom / correu electrònic / número de telèfon",
    "eu": "Bilatu hitzorduaren zenbakia / izena / helbide elektronikoa / telefono zenbakia",
    "gl": "Buscar número de cita / nome / correo electrónico / número de teléfono",
    "cy": "Chwilio rhif apwyntiad / enw / e-bost / rhif ffôn",
    "is": "Leitaðu að tímanúmeri / nafni / netfangi / símanúmeri",
    "ga": "Cuardaigh uimhir coinne / ainm / ríomhphost / uimhir theileafóin",
    "mt": "Fittex in-numru tal-appuntament / isem / email / numru tat-telefon",
    "lb": "Sich Rendez Nummer / Numm / Email / Telefonsnummer",
    "ja": "予約番号/名前/メールアドレス/電話番号を検索",
    "ko": "예약번호/이름/이메일/전화번호 검색",
    "zh-tw": "搜尋預約号 / 姓名 / 信箱 / 電話"
  },
  "未命名预约": {
    "en": "Unnamed appointment",
    "es": "Cita sin nombre",
    "fr": "Rendez-vous sans nom",
    "de": "Unbenannter Termin",
    "it": "Appuntamento senza nome",
    "pt": "Nomeação sem nome",
    "ru": "Неназванное назначение",
    "uk": "Безіменна зустріч",
    "pl": "Nienazwane spotkanie",
    "tr": "İsimsiz randevu",
    "nl": "Naamloze afspraak",
    "ro": "Numire fără nume",
    "cs": "Nejmenovaná schůzka",
    "sv": "Namnlös utnämning",
    "hu": "Névtelen találkozó",
    "da": "Unavngivet udnævnelse",
    "fi": "Nimetön tapaaminen",
    "no": "Ukjent avtale",
    "sk": "Nemenované stretnutie",
    "hr": "Neimenovani termin",
    "bs": "Neimenovani termin",
    "sr": "Неименовани термин",
    "bg": "Неназована среща",
    "el": "Ραντεβού χωρίς όνομα",
    "sq": "Takimi pa emër",
    "lt": "Neįvardytas susitikimas",
    "sl": "Neimenovani termin",
    "lv": "Nenosaukta tikšanās",
    "et": "Nimetu kohtumine",
    "mk": "Неименуван состанок",
    "ca": "Cita sense nom",
    "eu": "Izendapenik gabeko hitzordua",
    "gl": "Cita sen nome",
    "cy": "Apwyntiad dienw",
    "is": "Ónefnd skipun",
    "ga": "Coinne gan ainm",
    "mt": "Ħatra bla isem",
    "lb": "Onbekannt Rendez-vous",
    "ja": "名前のない予定",
    "ko": "이름 없는 약속",
    "zh-tw": "未命名預約"
  },
  "回复邮箱": {
    "en": "Reply to email",
    "es": "Responder al correo electrónico",
    "fr": "Répondre à l'e-mail",
    "de": "Auf E-Mail antworten",
    "it": "Rispondi all'e-mail",
    "pt": "Responder ao e-mail",
    "ru": "Ответ на электронное письмо",
    "uk": "Відповідь на електронну пошту",
    "pl": "Odpowiedz na e-mail",
    "tr": "E-postayı yanıtla",
    "nl": "E-mail beantwoorden",
    "ro": "Răspunde la e-mail",
    "cs": "Odpověď na email",
    "sv": "Svara på mejl",
    "hu": "Válasz e-mailre",
    "da": "Svar på e-mail",
    "fi": "Vastaa sähköpostiin",
    "no": "Svar på e-post",
    "sk": "Odpovedať na email",
    "hr": "Odgovor na email",
    "bs": "Odgovorite na email",
    "sr": "Одговорите на е-пошту",
    "bg": "Отговор на имейл",
    "el": "Απάντηση στο email",
    "sq": "Përgjigju emailit",
    "lt": "Atsakyti į el",
    "sl": "Odgovor na e-pošto",
    "lv": "Atbildēt uz e-pastu",
    "et": "Vasta meilile",
    "mk": "Одговори на е-пошта",
    "ca": "Respon al correu electrònic",
    "eu": "Erantzun mezu elektronikoari",
    "gl": "Responder ao correo electrónico",
    "cy": "Ymateb i e-bost",
    "is": "Svaraðu tölvupósti",
    "ga": "Freagair ríomhphost",
    "mt": "Irrispondi għall-email",
    "lb": "Äntwert op E-Mail",
    "ja": "メールに返信する",
    "ko": "이메일에 답장하기",
    "zh-tw": "回复信箱"
  },
  "拨打电话": {
    "en": "Make a call",
    "es": "hacer una llamada",
    "fr": "Passer un appel",
    "de": "Rufen Sie an",
    "it": "Fai una chiamata",
    "pt": "Faça uma chamada",
    "ru": "Позвонить",
    "uk": "Зробіть дзвінок",
    "pl": "Zadzwoń",
    "tr": "Arama yap",
    "nl": "Bel",
    "ro": "Efectuați un apel",
    "cs": "Zavolejte",
    "sv": "Ring ett samtal",
    "hu": "Hívjon",
    "da": "Foretag et opkald",
    "fi": "Soita puhelu",
    "no": "Ring",
    "sk": "Zavolajte",
    "hr": "Nazovite",
    "bs": "Pozovi",
    "sr": "Позовите",
    "bg": "Обадете се",
    "el": "Κάνε μια κλήση",
    "sq": "Bëj një telefonatë",
    "lt": "Paskambink",
    "sl": "Pokliči",
    "lv": "Zvanīt",
    "et": "Helistage",
    "mk": "Направете повик",
    "ca": "Fes una trucada",
    "eu": "Egin dei bat",
    "gl": "Fai unha chamada",
    "cy": "Gwnewch alwad",
    "is": "Hringdu",
    "ga": "Déan glaoch",
    "mt": "Agħmel sejħa",
    "lb": "Maacht en Uruff",
    "ja": "電話をかける",
    "ko": "전화 걸기",
    "zh-tw": "拨打電話"
  },
  "有备注": {
    "en": "There are notes",
    "es": "hay notas",
    "fr": "Il y a des notes",
    "de": "Es gibt Notizen",
    "it": "Ci sono delle note",
    "pt": "Existem notas",
    "ru": "Есть заметки",
    "uk": "Є примітки",
    "pl": "Są notatki",
    "tr": "notlar var",
    "nl": "Er zijn aantekeningen",
    "ro": "Sunt note",
    "cs": "Jsou tam poznámky",
    "sv": "Det finns anteckningar",
    "hu": "Vannak jegyzetek",
    "da": "Der er noter",
    "fi": "On muistiinpanoja",
    "no": "Det er notater",
    "sk": "Sú tam poznámky",
    "hr": "Postoje bilješke",
    "bs": "Postoje bilješke",
    "sr": "Постоје белешке",
    "bg": "Има бележки",
    "el": "Υπάρχουν σημειώσεις",
    "sq": "Ka shënime",
    "lt": "Yra užrašai",
    "sl": "Obstajajo opombe",
    "lv": "Ir piezīmes",
    "et": "On märkmeid",
    "mk": "Има белешки",
    "ca": "Hi ha notes",
    "eu": "Notak daude",
    "gl": "Hai notas",
    "cy": "Mae nodiadau",
    "is": "Það eru aths",
    "ga": "Tá nótaí ann",
    "mt": "Hemm noti",
    "lb": "Et ginn Noten",
    "ja": "メモがあります",
    "ko": "메모가 있습니다",
    "zh-tw": "有備註"
  },
  "处理中...": {
    "en": "Processing...",
    "es": "Procesando...",
    "fr": "Traitement...",
    "de": "Verarbeitung...",
    "it": "Elaborazione...",
    "pt": "Processando...",
    "ru": "Обработка...",
    "uk": "Обробка...",
    "pl": "Przetwarzanie...",
    "tr": "İşleniyor...",
    "nl": "Verwerken...",
    "ro": "Se procesează...",
    "cs": "Zpracovává se...",
    "sv": "Bearbetar...",
    "hu": "Feldolgozás...",
    "da": "Behandler...",
    "fi": "Käsitellään...",
    "no": "Behandler...",
    "sk": "Spracováva sa...",
    "hr": "Obrada...",
    "bs": "Obrada...",
    "sr": "Обрада...",
    "bg": "Обработва се...",
    "el": "Επεξεργασία...",
    "sq": "Po përpunohet...",
    "lt": "Apdorojama...",
    "sl": "Obdelava ...",
    "lv": "Notiek apstrāde...",
    "et": "Töötlemine...",
    "mk": "Се обработува...",
    "ca": "S'està processant...",
    "eu": "Prozesatzen...",
    "gl": "Procesando...",
    "cy": "Wrthi'n prosesu...",
    "is": "Vinnur...",
    "ga": "Próiseáil...",
    "mt": "Ipproċessar...",
    "lb": "Veraarbechtung...",
    "ja": "処理中...",
    "ko": "처리 중...",
    "zh-tw": "處理中..."
  },
  "下拉刷新": {
    "en": "Pull down to refresh",
    "es": "Tira hacia abajo para actualizar",
    "fr": "Déroulez pour actualiser",
    "de": "Zum Aktualisieren nach unten ziehen",
    "it": "Tirare verso il basso per rinfrescare",
    "pt": "Puxe para baixo para atualizar",
    "ru": "Потяните вниз, чтобы обновить",
    "uk": "Потягніть вниз, щоб оновити",
    "pl": "Pociągnij w dół, aby odświeżyć",
    "tr": "Yenilemek için aşağı çekin",
    "nl": "Trek omlaag om te vernieuwen",
    "ro": "Trageți în jos pentru a reîmprospăta",
    "cs": "Zatažením dolů obnovte",
    "sv": "Dra ned för att uppdatera",
    "hu": "Húzza le a frissítéshez",
    "da": "Træk ned for at opdatere",
    "fi": "Vedä alas päivittääksesi",
    "no": "Trekk ned for å oppdatere",
    "sk": "Potiahnutím nadol obnovíte",
    "hr": "Povucite prema dolje za osvježavanje",
    "bs": "Povucite prema dolje da osvježite",
    "sr": "Повуците надоле да бисте освежили",
    "bg": "Издърпайте надолу за опресняване",
    "el": "Τραβήξτε προς τα κάτω για ανανέωση",
    "sq": "Tërhiqeni poshtë për të rifreskuar",
    "lt": "Norėdami atnaujinti, patraukite žemyn",
    "sl": "Povlecite navzdol za osvežitev",
    "lv": "Velciet uz leju, lai atsvaidzinātu",
    "et": "Värskendamiseks tõmmake alla",
    "mk": "Повлечете надолу за да се освежите",
    "ca": "Tireu cap avall per actualitzar",
    "eu": "Tira behera freskatzeko",
    "gl": "Tire cara abaixo para actualizar",
    "cy": "Tynnwch i lawr i adnewyddu",
    "is": "Dragðu niður til að endurnýja",
    "ga": "Tarraing anuas chun athnuachan",
    "mt": "Iġbed 'l isfel biex taġġorna",
    "lb": "Pull erof fir ze erfrëschen",
    "ja": "プルダウンして更新します",
    "ko": "아래로 당겨 새로고침하세요.",
    "zh-tw": "下拉重新整理"
  },
  "松开刷新": {
    "en": "Release refresh",
    "es": "Actualización de lanzamiento",
    "fr": "Actualisation de la version",
    "de": "Release-Aktualisierung",
    "it": "Aggiornamento del rilascio",
    "pt": "Atualização de versão",
    "ru": "Обновление выпуска",
    "uk": "Випуск оновлення",
    "pl": "Zwolnij odświeżanie",
    "tr": "Sürüm yenileme",
    "nl": "Laat vernieuwen los",
    "ro": "Eliberați reîmprospătarea",
    "cs": "Uvolněte aktualizaci",
    "sv": "Släpp uppdateringen",
    "hu": "Engedje el a frissítést",
    "da": "Slip opdatering",
    "fi": "Vapauta päivitys",
    "no": "Slipp oppdateringen",
    "sk": "Uvoľnite obnovenie",
    "hr": "Pusti osvježi",
    "bs": "Otpustite osvježenje",
    "sr": "Релеасе рефресх",
    "bg": "Пуснете опресняване",
    "el": "Απελευθερώστε την ανανέωση",
    "sq": "Lësho rifreskimin",
    "lt": "Atleiskite atnaujinimą",
    "sl": "Sprostite osvežitev",
    "lv": "Atlaidiet atsvaidzināšanu",
    "et": "Vabastage värskendus",
    "mk": "Ослободете го освежувањето",
    "ca": "Allibera l'actualització",
    "eu": "Askatu freskatzea",
    "gl": "Liberar actualización",
    "cy": "Rhyddhau adnewyddu",
    "is": "Slepptu endurnýjun",
    "ga": "Scaoileadh athnuachan",
    "mt": "Rilaxx aġġornament",
    "lb": "Fräisetzung Erfrëschung",
    "ja": "リリースリフレッシュ",
    "ko": "릴리스 새로 고침",
    "zh-tw": "放開重新整理"
  },
  "刷新中...": {
    "en": "Refreshing...",
    "es": "Refrescante...",
    "fr": "Rafraîchissant...",
    "de": "Erfrischend...",
    "it": "Rinfrescante...",
    "pt": "Refrescante...",
    "ru": "Освежающий...",
    "uk": "Оновлення...",
    "pl": "Orzeźwiający...",
    "tr": "Yenileniyor...",
    "nl": "Verfrissend...",
    "ro": "Înviorare...",
    "cs": "Obnovování...",
    "sv": "Uppfriskande...",
    "hu": "Frissítés...",
    "da": "Forfriskende...",
    "fi": "Virkistävää...",
    "no": "Oppdaterer...",
    "sk": "Obnovuje sa...",
    "hr": "Osvježavanje...",
    "bs": "Osvježavanje...",
    "sr": "Освежавање...",
    "bg": "Опресняване...",
    "el": "Αναζωογονητικό...",
    "sq": "Po freskohet...",
    "lt": "Atnaujinama...",
    "sl": "Osvežitev ...",
    "lv": "Notiek atsvaidzināšana...",
    "et": "Värskendamine...",
    "mk": "Се освежува...",
    "ca": "Refrescant...",
    "eu": "Freskatzen...",
    "gl": "Refrescando...",
    "cy": "Wrthi'n adnewyddu...",
    "is": "Hressandi...",
    "ga": "Á athnuachan...",
    "mt": "Aġġorna...",
    "lb": "Erfrëschend ...",
    "ja": "爽やかな...",
    "ko": "상쾌하다...",
    "zh-tw": "重新整理中..."
  },
  "查看并管理 {site} 收到的预约记录。": {
    "en": "View and manage appointments received by {site}.",
    "es": "Ver y administrar citas recibidas por {sitio}.",
    "fr": "Afficher et gérer les rendez-vous reçus par {site}.",
    "de": "Von {site} erhaltene Termine anzeigen und verwalten.",
    "it": "Visualizza e gestisci gli appuntamenti ricevuti da {site}.",
    "pt": "Visualize e gerencie compromissos recebidos por {site}.",
    "ru": "Просматривайте встречи, полученные на {site}, и управляйте ими.",
    "uk": "Перегляд зустрічей, отриманих {site}, і керування ними.",
    "pl": "Przeglądaj i zarządzaj spotkaniami otrzymanymi przez {site}.",
    "tr": "{site} tarafından alınan randevuları görüntüleyin ve yönetin.",
    "nl": "Bekijk en beheer afspraken ontvangen door {site}.",
    "ro": "Vizualizați și gestionați întâlnirile primite de {site}.",
    "cs": "Zobrazení a správa schůzek přijatých webem {site}.",
    "sv": "Visa och hantera möten som tagits emot av {site}.",
    "hu": "Megtekintheti és kezelheti a(z) {site} által kapott találkozókat.",
    "da": "Se og administrer aftaler modtaget af {site}.",
    "fi": "Tarkastele ja hallinnoi sivuston {site} vastaanottamia tapaamisia.",
    "no": "Se og administrer avtaler mottatt av {site}.",
    "sk": "Zobrazenie a správa stretnutí prijatých na stránke {site}.",
    "hr": "Pregledajte sastanke koje je primila {site} i upravljajte njima.",
    "bs": "Pregledajte i upravljajte terminima koje prima {site}.",
    "sr": "Прегледајте састанке које прима {сите} и управљајте њима.",
    "bg": "Преглеждайте и управлявайте срещите, получени от {site}.",
    "el": "Προβολή και διαχείριση συναντήσεων που λαμβάνονται από τον ιστότοπο {site}.",
    "sq": "Shikoni dhe menaxhoni takimet e marra nga {site}.",
    "lt": "Peržiūrėkite ir valdykite {site} gautus susitikimus.",
    "sl": "Ogled in upravljanje sestankov, ki jih prejme {site}.",
    "lv": "Skatiet un pārvaldiet vietnes {site} saņemtās tikšanās.",
    "et": "Vaadake ja hallake saidi {site} vastuvõetud kohtumisi.",
    "mk": "Приказ и управување со состаноци добиени од {site}.",
    "ca": "Consulta i gestiona les cites rebudes per {site}.",
    "eu": "Ikusi eta kudeatu {site}-k jasotako hitzorduak.",
    "gl": "Consulta e xestiona as citas recibidas por {site}.",
    "cy": "Gweld a rheoli apwyntiadau a dderbyniwyd gan {site}.",
    "is": "Skoðaðu og stjórnaðu stefnumótum sem {site} berst.",
    "ga": "Féach ar agus bainistigh coinní a fhaigheann {site}.",
    "mt": "Ara u mmaniġġja l-ħatriet riċevuti minn {sit}.",
    "lb": "Kuckt a verwalten Rendez-vousen, déi vum {Site} kritt goufen.",
    "ja": "{site} が受信した予約を表示および管理します。",
    "ko": "{site}에서 받은 약속을 보고 관리합니다.",
    "zh-tw": "查看并管理 {site} 收到的預約记录。"
  },
  "今天": {
    "en": "today",
    "es": "hoy",
    "fr": "aujourd'hui",
    "de": "heute",
    "it": "oggi",
    "pt": "hoje",
    "ru": "сегодня",
    "uk": "сьогодні",
    "pl": "dzisiaj",
    "tr": "bugün",
    "nl": "vandaag",
    "ro": "azi",
    "cs": "dnes",
    "sv": "idag",
    "hu": "ma",
    "da": "i dag",
    "fi": "tänään",
    "no": "i dag",
    "sk": "dnes",
    "hr": "danas",
    "bs": "danas",
    "sr": "данас",
    "bg": "днес",
    "el": "σήμερα",
    "sq": "sot",
    "lt": "šiandien",
    "sl": "danes",
    "lv": "šodien",
    "et": "täna",
    "mk": "денес",
    "ca": "avui",
    "eu": "gaur",
    "gl": "hoxe",
    "cy": "heddiw",
    "is": "í dag",
    "ga": "inniu",
    "mt": "illum",
    "lb": "haut",
    "ja": "今日",
    "ko": "오늘",
    "zh-tw": "今天"
  },
  "搜索": {
    "en": "Search",
    "es": "Buscar",
    "fr": "Rechercher",
    "de": "Suchen",
    "it": "Cerca",
    "pt": "Pesquisar",
    "ru": "Поиск",
    "uk": "Пошук",
    "pl": "Szukaj",
    "tr": "Ara",
    "nl": "Zoeken",
    "ro": "Caută",
    "cs": "Hledat",
    "sv": "Sök",
    "hu": "Keresés",
    "da": "Søg",
    "fi": "Etsi",
    "no": "Søk",
    "sk": "Hľadať",
    "hr": "Traži",
    "bs": "Traži",
    "sr": "Тражи",
    "bg": "Търсене",
    "el": "Αναζήτηση",
    "sq": "Kërko",
    "lt": "Ieškoti",
    "sl": "Iskanje",
    "lv": "Meklēt",
    "et": "Otsi",
    "mk": "Пребарување",
    "ca": "Cerca",
    "eu": "Bilatu",
    "gl": "Busca",
    "cy": "Chwiliwch",
    "is": "Leita",
    "ga": "Cuardach",
    "mt": "Fittex",
    "lb": "Sichen",
    "ja": "検索",
    "ko": "검색",
    "zh-tw": "搜尋"
  },
  "搜索中": {
    "en": "Searching",
    "es": "Buscando",
    "fr": "Recherche",
    "de": "Suchen",
    "it": "Ricerca",
    "pt": "Procurando",
    "ru": "Поиск",
    "uk": "Пошук",
    "pl": "Wyszukiwanie",
    "tr": "Aranıyor",
    "nl": "Zoeken",
    "ro": "Căutând",
    "cs": "Hledání",
    "sv": "Söker",
    "hu": "Keresés",
    "da": "Søger",
    "fi": "Etsitään",
    "no": "Søker",
    "sk": "Hľadá sa",
    "hr": "Traženje",
    "bs": "Tražim",
    "sr": "Тражим",
    "bg": "Търсене",
    "el": "Ψάχνοντας",
    "sq": "Duke kërkuar",
    "lt": "Ieškoma",
    "sl": "Iskanje",
    "lv": "Meklēšana",
    "et": "Otsimine",
    "mk": "Пребарување",
    "ca": "Buscant",
    "eu": "Bilatzen",
    "gl": "Buscando",
    "cy": "Chwilio",
    "is": "Leitar",
    "ga": "Cuardach",
    "mt": "Tiftix",
    "lb": "Sichen",
    "ja": "検索中",
    "ko": "검색 중",
    "zh-tw": "搜尋中"
  },
  "商户ID / 邮箱": {
    "en": "Merchant ID / Email",
    "es": "ID de comerciante/correo electrónico",
    "fr": "Identifiant du commerçant/e-mail",
    "de": "Händler-ID/E-Mail",
    "it": "ID commerciante/e-mail",
    "pt": "ID/e-mail do comerciante",
    "ru": "Идентификатор продавца / адрес электронной почты",
    "uk": "Ідентифікатор продавця / електронна адреса",
    "pl": "Identyfikator sprzedawcy / adres e-mail",
    "tr": "Satıcı Kimliği / E-postası",
    "nl": "Verkoper-ID/e-mailadres",
    "ro": "ID comerciant / e-mail",
    "cs": "ID obchodníka / e-mail",
    "sv": "Säljar-ID/e-post",
    "hu": "Kereskedőazonosító / E-mail",
    "da": "Sælger-id / e-mail",
    "fi": "Kauppiaan tunnus/sähköposti",
    "no": "Selger-ID / e-post",
    "sk": "ID obchodníka / e-mail",
    "hr": "ID trgovca/e-pošta",
    "bs": "ID trgovca / e-pošta",
    "sr": "ИД продавца/е-пошта",
    "bg": "ИД на търговец/имейл",
    "el": "Ταυτότητα εμπόρου / Email",
    "sq": "ID e tregtarit / Email",
    "lt": "Prekybininko ID / el",
    "sl": "ID trgovca/e-pošta",
    "lv": "Tirgotāja ID/e-pasts",
    "et": "Kaupmehe ID / e-post",
    "mk": "ИД/Е-пошта на трговец",
    "ca": "Identificador de comerciant / correu electrònic",
    "eu": "Merkatari IDa / Posta elektronikoa",
    "gl": "ID do comerciante / correo electrónico",
    "cy": "ID Masnachwr / E-bost",
    "is": "Söluauðkenni / tölvupóstur",
    "ga": "ID Ceannaí / Ríomhphost",
    "mt": "ID tan-negozjant / Email",
    "lb": "Händler ID / Email",
    "ja": "販売者 ID / メールアドレス",
    "ko": "판매자 ID / 이메일",
    "zh-tw": "商户ID / 信箱"
  }
} as const;

export type UiGlossarySource = keyof typeof UI_GLOSSARY_TRANSLATIONS;

const UI_GLOSSARY_OVERRIDES: Partial<Record<UiGlossarySource | string, Partial<Record<string, string>>>> = {
  "先生": {
    en: "Mr.",
    es: "Sr.",
    fr: "M.",
    de: "Herr",
    it: "Sig.",
    pt: "Sr.",
    ru: "Г-н",
    uk: "Пан",
    pl: "Pan",
    tr: "Bey",
    nl: "Dhr.",
    ro: "Dl.",
    cs: "Pan",
    sv: "Herr",
    hu: "Úr",
    da: "Hr.",
    fi: "Herra",
    no: "Herr",
    sk: "Pán",
    hr: "G.",
    bs: "G.",
    sr: "G.",
    bg: "Г-н",
    el: "Κος",
    sq: "Z.",
    lt: "P.",
    sl: "G.",
    lv: "Kgs.",
    et: "Hr.",
    mk: "Г-дин",
    ca: "Sr.",
    eu: "Jn.",
    gl: "Sr.",
    cy: "Mr.",
    is: "Herra",
    ga: "Uas.",
    mt: "Sur",
    lb: "Här",
    ja: "様",
    ko: "님",
  },
  "女士": {
    en: "Ms.",
    es: "Sra.",
    fr: "Mme",
    de: "Frau",
    it: "Sig.ra",
    pt: "Sra.",
    ru: "Г-жа",
    uk: "Пані",
    pl: "Pani",
    tr: "Hanım",
    nl: "Mevr.",
    ro: "Dna.",
    cs: "Paní",
    sv: "Fru",
    hu: "Hölgy",
    da: "Fru",
    fi: "Rouva",
    no: "Fru",
    sk: "Pani",
    hr: "Gđa.",
    bs: "Gđa.",
    sr: "Gđa.",
    bg: "Г-жа",
    el: "Κα",
    sq: "Znj.",
    lt: "Ponia",
    sl: "Ga.",
    lv: "Kdze.",
    et: "Pr.",
    mk: "Г-ѓа",
    ca: "Sra.",
    eu: "And.",
    gl: "Sra.",
    cy: "Ms.",
    is: "Frú",
    ga: "Bean Uas.",
    mt: "Sinjura",
    lb: "Madamm",
    ja: "様",
    ko: "님",
  },
  "会话": {
    en: "Chat",
    es: "Chat",
    fr: "Chat",
    de: "Chat",
    it: "Chat",
    pt: "Chat",
    ru: "Чат",
    uk: "Чат",
    pl: "Chat",
    tr: "Sohbet",
    nl: "Chat",
    ro: "Chat",
    cs: "Chat",
    sv: "Chatt",
    hu: "Csevegés",
    da: "Chat",
    fi: "Chat",
    no: "Chat",
    sk: "Chat",
    hr: "Chat",
    bs: "Chat",
    sr: "Chat",
    bg: "Чат",
    el: "Chat",
    sq: "Chat",
    lt: "Chat",
    sl: "Chat",
    lv: "Chat",
    et: "Chat",
    mk: "Чат",
    ca: "Xat",
    eu: "Txata",
    gl: "Chat",
    cy: "Sgwrs",
    is: "Spjall",
    ga: "Comhrá",
    mt: "Chat",
    lb: "Chat",
    ja: "チャット",
    ko: "채팅",
    "zh-tw": "會話",
  },
  "会话，有新消息": {
    en: "Chat, new messages",
    es: "Chat, con mensajes nuevos",
    fr: "Chat, nouveaux messages",
    de: "Chat, neue Nachrichten",
    it: "Chat, nuovi messaggi",
    pt: "Chat, novas mensagens",
    ru: "Чат, новые сообщения",
    uk: "Чат, нові повідомлення",
    pl: "Chat, nowe wiadomości",
    tr: "Sohbet, yeni mesajlar",
    nl: "Chat, nieuwe berichten",
    ro: "Chat, mesaje noi",
    cs: "Chat, nové zprávy",
    sv: "Chatt, nya meddelanden",
    hu: "Csevegés, új üzenetek",
    da: "Chat, nye beskeder",
    fi: "Chat, uusia viestejä",
    no: "Chat, nye meldinger",
    sk: "Chat, nové správy",
    hr: "Chat, nove poruke",
    bs: "Chat, nove poruke",
    sr: "Chat, nove poruke",
    bg: "Чат, нови съобщения",
    el: "Chat, νέα μηνύματα",
    sq: "Chat, mesazhe të reja",
    lt: "Chat, naujos žinutės",
    sl: "Chat, nova sporočila",
    lv: "Chat, jaunas ziņas",
    et: "Chat, uued sõnumid",
    mk: "Чат, нови пораки",
    ca: "Xat, missatges nous",
    eu: "Txata, mezu berriak",
    gl: "Chat, novas mensaxes",
    cy: "Sgwrs, negeseuon newydd",
    is: "Spjall, ný skilaboð",
    ga: "Comhrá, teachtaireachtaí nua",
    mt: "Chat, messaġġi ġodda",
    lb: "Chat, nei Messagen",
    ja: "チャット、新着メッセージ",
    ko: "채팅, 새 메시지",
    "zh-tw": "會話，有新訊息",
  },
  "名片夹": {
    en: "Cards",
    es: "Tarjetero",
    fr: "Cartes",
    de: "Karten",
    it: "Biglietti",
    pt: "Cartões",
    ru: "Визитки",
    uk: "Візитки",
    pl: "Wizytówki",
    tr: "Kartlar",
    nl: "Kaarten",
    ro: "Cărți",
    cs: "Vizitky",
    sv: "Kort",
    hu: "Kártyák",
    da: "Kort",
    fi: "Kortit",
    no: "Kort",
    sk: "Vizitky",
    hr: "Vizitke",
    bs: "Vizitke",
    sr: "Vizitke",
    bg: "Визитки",
    el: "Κάρτες",
    sq: "Kartat",
    lt: "Kortelės",
    sl: "Vizitke",
    lv: "Kartītes",
    et: "Kaardid",
    mk: "Визитки",
    ca: "Targetes",
    eu: "Txartelak",
    gl: "Tarxetas",
    cy: "Cardiau",
    is: "Spjöld",
    ga: "Cártaí",
    mt: "Karti",
    lb: "Kaarten",
    ja: "名刺",
    ko: "명함",
    "zh-tw": "名片夾",
  },
  "我的名片夹": {
    en: "My cards",
    es: "Mi tarjetero",
    fr: "Mes cartes",
    de: "Meine Karten",
    it: "I miei biglietti",
    pt: "Meus cartões",
    ru: "Мои визитки",
    uk: "Мої візитки",
    pl: "Moje wizytówki",
    tr: "Kartlarım",
    nl: "Mijn kaarten",
    ro: "Cărțile mele",
    cs: "Moje vizitky",
    sv: "Mina kort",
    hu: "Kártyáim",
    da: "Mine kort",
    fi: "Omat kortit",
    no: "Mine kort",
    sk: "Moje vizitky",
    hr: "Moje vizitke",
    bs: "Moje vizitke",
    sr: "Moje vizitke",
    bg: "Моите визитки",
    el: "Οι κάρτες μου",
    sq: "Kartat e mia",
    lt: "Mano kortelės",
    sl: "Moje vizitke",
    lv: "Manas kartītes",
    et: "Minu kaardid",
    mk: "Моите визитки",
    ca: "Les meves targetes",
    eu: "Nire txartelak",
    gl: "As miñas tarxetas",
    cy: "Fy nghardiau",
    is: "Mín spjöld",
    ga: "Mo chártaí",
    mt: "Il-karti tiegħi",
    lb: "Meng Kaarten",
    ja: "マイ名刺",
    ko: "내 명함",
    "zh-tw": "我的名片夾",
  },
  "待确认": {
    es: "Pendiente",
  },
  "已确认": {
    es: "Confirmada",
  },
  "已完成": {
    es: "Completada",
  },
  "已取消": {
    es: "Cancelada",
  },
  "全部": {
    es: "Todas",
  },
  "确认预约": {
    es: "Confirmar",
  },
  "完成预约": {
    es: "Completar",
  },
  "取消预约": {
    es: "Cancelar",
  },
  "恢复预约": {
    es: "Restaurar",
  },
  "取消确认": {
    es: "Revertir",
  },
  "取消完成": {
    es: "Deshacer",
  },
  "关闭": {
    en: "Close",
    es: "Cerrar",
    fr: "Fermer",
    de: "Schließen",
    it: "Chiudi",
    pt: "Fechar",
    ru: "Закрыть",
    uk: "Закрити",
    pl: "Zamknij",
    tr: "Kapat",
    nl: "Sluiten",
    ro: "Închide",
    cs: "Zavřít",
    sv: "Stäng",
    hu: "Bezár",
    da: "Luk",
    fi: "Sulje",
    no: "Lukk",
    sk: "Zavrieť",
    hr: "Zatvori",
    bs: "Zatvori",
    sr: "Zatvori",
    bg: "Затвори",
    el: "Κλείσε",
    sq: "Mbyll",
    lt: "Uždaryti",
    sl: "Zapri",
    lv: "Aizvērt",
    et: "Sulge",
    mk: "Затвори",
    ca: "Tanca",
    eu: "Itxi",
    gl: "Pechar",
    cy: "Cau",
    is: "Loka",
    ga: "Dún",
    mt: "Agħlaq",
    lb: "Zoumaachen",
    ja: "閉じる",
    ko: "닫기",
  },
  "称谓": {
    en: "Title",
    es: "Tratamiento",
    fr: "Civilité",
    de: "Anrede",
    it: "Titolo",
    pt: "Tratamento",
    ru: "Обращение",
    uk: "Звертання",
    pl: "Tytuł",
    tr: "Hitap",
    nl: "Aanhef",
    ro: "Formula",
    cs: "Oslovení",
    sv: "Tilltal",
    hu: "Megszólítás",
    da: "Tiltale",
    fi: "Puhuttelu",
    no: "Tiltale",
    sk: "Oslovenie",
    hr: "Oslovljavanje",
    bs: "Oslovljavanje",
    sr: "Oslovljavanje",
    bg: "Обръщение",
    el: "Προσφώνηση",
    sq: "Titulli",
    lt: "Kreipinys",
    sl: "Nagovor",
    lv: "Uzruna",
    et: "Pöördumine",
    mk: "Обраќање",
    ca: "Tractament",
    eu: "Tratamendua",
    gl: "Tratamento",
    cy: "Cyfarchiad",
    is: "Ávarp",
    ga: "Teideal",
    mt: "Titlu",
    lb: "Uried",
    ja: "敬称",
    ko: "호칭",
    "zh-tw": "稱謂",
  },
  "保存": {
    en: "Save",
    es: "Guardar",
    fr: "Enregistrer",
    de: "Speichern",
    it: "Salva",
    pt: "Guardar",
    ru: "Сохранить",
    uk: "Зберегти",
    pl: "Zapisz",
    tr: "Kaydet",
    nl: "Opslaan",
    ro: "Salvează",
    cs: "Uložit",
    sv: "Spara",
    hu: "Mentés",
    da: "Gem",
    fi: "Tallenna",
    no: "Lagre",
    sk: "Uložiť",
    hr: "Spremi",
    bs: "Sačuvaj",
    sr: "Sačuvaj",
    bg: "Запази",
    el: "Αποθήκευση",
    sq: "Ruaj",
    lt: "Išsaugoti",
    sl: "Shrani",
    lv: "Saglabāt",
    et: "Salvesta",
    mk: "Зачувај",
    ca: "Desa",
    eu: "Gorde",
    gl: "Gardar",
    cy: "Cadw",
    is: "Vista",
    ga: "Sábháil",
    mt: "Issejvja",
    lb: "Späicheren",
    ja: "保存",
    ko: "저장",
  },
};

function getUiGlossaryRow(source: UiGlossarySource | string): Record<string, string> {
  const key = String(source) as UiGlossarySource;
  const baseRow = UI_GLOSSARY_TRANSLATIONS[key] ? { ...UI_GLOSSARY_TRANSLATIONS[key] } : {};
  const overrideRow = UI_GLOSSARY_OVERRIDES[key] ?? {};
  return { ...baseRow, ...overrideRow };
}

export function getUiGlossaryLocale(locale: string | null | undefined) {
  const normalized = resolveSupportedLocale(locale).toLowerCase();
  if (normalized === "zh-cn" || normalized === "zh-tw") return normalized;
  return normalized.split("-")[0] || "en";
}

export function getUiGlossaryText(source: UiGlossarySource | string, locale: string | null | undefined) {
  const normalizedLocale = getUiGlossaryLocale(locale);
  if (normalizedLocale === "zh-cn") return String(source);
  const row = getUiGlossaryRow(source);
  if (!Object.keys(row).length) return String(source);
  return row[normalizedLocale] ?? row.en ?? String(source);
}

export function findUiGlossarySource(translated: string, locale: string | null | undefined) {
  const normalizedLocale = getUiGlossaryLocale(locale);
  const sourceKeys = new Set<string>([
    ...Object.keys(UI_GLOSSARY_TRANSLATIONS),
    ...Object.keys(UI_GLOSSARY_OVERRIDES),
  ]);
  for (const source of sourceKeys) {
    const row = getUiGlossaryRow(source);
    const candidate = row[normalizedLocale] ?? row.en;
    if (candidate === translated) return source;
  }
  return null;
}
