// Synthetic HTTP only: real authorization and routing source proof remain SQL.
import test from "node:test";
import assert from "node:assert/strict";
import type { User } from "@supabase/supabase-js";
import { handleReviewRouting,reviewRoutingDependencies } from "./route-handler";
import { reviewRoutingQueryString,type ReviewRoutingQuery } from "@/lib/merchantAttendanceReviewRouting";
import type { ReviewRoutingServiceInput } from "@/lib/merchantAttendanceReviewRouting.server";
import { MerchantAttendanceError } from "@/lib/merchantAttendanceTime";
import { routingSite,routingOwner,routingId,routingDetail,routingCommand,routingResult,routingReceipt } from "../../../../../../scripts/fixtures/attendance-review-routing-model";
const origin="https://www.faolla.com",url=origin+"/api/merchant-enterprise/attendance/review-routing",get=(q:ReviewRoutingQuery)=>new Request(url+"?"+reviewRoutingQueryString(q),{headers:{origin}}),post=(body:unknown,headers:Record<string,string>={})=>new Request(url,{method:"POST",headers:{origin,"content-type":"application/json",...headers},body:JSON.stringify(body)});
function setup(){const calls:ReviewRoutingServiceInput[]=[],eligible:string[]=[];const deps:typeof reviewRoutingDependencies={allow:()=>true,enabled:()=>true,timeoutMs:12000,bodyTimeoutMs:5000,authenticate:async()=>({user:{id:routingOwner}as User,accessToken:"synthetic",authenticationMethods:["password"]}),entitlement:async site=>{eligible.push(site);return{permissionConfig:{allowEnterpriseManagement:true,allowEmployeeAttendance:true}}as Awaited<ReturnType<typeof reviewRoutingDependencies.entitlement>>;},execute:async input=>{calls.push(input);if(input.command)return routingResult({kind:"receipt"},routingReceipt(routingDetail().query,input.command));if(input.query.mode==="recover")return routingResult({kind:"receipt"});if(input.query.mode==="self")return routingResult({kind:"self",family:input.query.family,requestId:input.query.requestId,submittedAt:"2026-10-08T08:00:00.000000Z",route:"unregistered",handoverNeeded:false,capturedAt:null});return routingDetail().wire;}};return{deps,calls,eligible};}
test("198 strict same-origin/password gate precedes dispatch and ignores caller-supplied actor",async()=>{const s=setup(),body={query:routingDetail().query,command:routingCommand()},headers:Record<string,string>[]=[{origin:"https://foreign.invalid"},{"sec-fetch-site":"same-site"},{"sec-fetch-site":"cross-site"}];for(const h of headers)assert.equal((await handleReviewRouting(post(body,h),s.deps)).status,403);assert.equal((await handleReviewRouting(post(body),{...s.deps,authenticate:async()=>({user:{id:routingOwner}as User,accessToken:"synthetic",authenticationMethods:["recovery"]})})).status,403);assert.equal((await handleReviewRouting(post({...body,authUserId:routingId(99)}),s.deps)).status,400);assert.equal(s.calls.length,0);});
test("198 actual flag and entitlement only admit fresh writes; safe historical read/recovery remains reachable",async()=>{const s=setup(),q=routingDetail().query,r=await handleReviewRouting(post({query:q,command:routingCommand()}),s.deps);assert.equal(r.status,200);assert.match(r.headers.get("cache-control")!,/private.*no-store/);assert.equal(s.calls[0].authUserId,routingOwner);assert.equal(s.calls[0].allowWrite,true);await handleReviewRouting(get(q),{...s.deps,enabled:()=>false});assert.equal(s.calls[1].allowWrite,false);const safe={...s.deps,enabled:()=>false,entitlement:async()=>{assert.fail("safe path no entitlement");}};assert.equal((await handleReviewRouting(get({...q,mode:"self"}),safe)).status,200);assert.equal((await handleReviewRouting(get({siteId:routingSite,mode:"recover",family:q.family,operationId:routingId(300)}),safe)).status,200);});
test("198 off POST reaches SQL with false to permit only exact old receipt replay",async()=>{const s=setup();let count=0;const r=await handleReviewRouting(post({query:routingDetail().query,command:routingCommand()}),{...s.deps,enabled:()=>false,execute:async input=>{count++;assert.equal(input.allowWrite,false);throw new MerchantAttendanceError("attendance_review_routing_disabled");}});assert.equal(r.status,403);assert.equal(count,1);});
test("198 strict byte/body/query/result limits reject malformed JSON and foreign identity",async()=>{const s=setup();assert.equal((await handleReviewRouting(post({x:"x".repeat(8192)}),s.deps)).status,422);for(const bytes of['{"query":null,"query":null}',new Uint8Array([0xff])])assert.equal((await handleReviewRouting(new Request(url,{method:"POST",headers:{origin,"content-type":"application/json"},body:bytes}),s.deps)).status,400);assert.equal((await handleReviewRouting(new Request(url+"?siteId=99990001&siteId=99990002",{headers:{origin}}),s.deps)).status,400);assert.equal(s.calls.length,0);assert.equal((await handleReviewRouting(get(routingDetail().query),{...s.deps,execute:async()=>({...routingDetail().wire,actorId:routingId(99)})})).status,503);});
test("198 body and total deadlines cancel stalled work and prevent late SQL dispatch",async()=>{const s=setup();let cancelled=false,finish!:()=>void;const stream=new ReadableStream<Uint8Array>({start(c){c.enqueue(new TextEncoder().encode("{"));},cancel(){cancelled=true;}});const request=new Request(url,{method:"POST",headers:{origin,"content-type":"application/json"},body:stream,duplex:"half"}as RequestInit);assert.equal((await handleReviewRouting(request,{...s.deps,bodyTimeoutMs:10})).status,400);assert.equal(cancelled,true);const hold=new Promise<void>(r=>{finish=r;});assert.equal((await handleReviewRouting(get(routingDetail().query),{...s.deps,timeoutMs:10,authenticate:async r=>{await hold;return s.deps.authenticate(r);}})).status,503);finish();await new Promise<void>(r=>setImmediate(r));assert.equal(s.calls.length,0);});
