import test from "node:test";
import assert from "node:assert/strict";
import {
  findShareOwnerMerchantIdInSnapshotPayload,
  isStorageObjectMissingError,
} from "@/app/api/business-card-share/route";
import { normalizeMerchantBusinessCardSharePayload } from "@/lib/merchantBusinessCardShare";

test("share delete treats common not-found storage errors as idempotent misses", () => {
  assert.equal(isStorageObjectMissingError("The resource was not found"), true);
  assert.equal(isStorageObjectMissingError("Object does not exist"), true);
  assert.equal(isStorageObjectMissingError("storage responded with status code 404"), true);
});

test("share delete does not hide unrelated storage failures", () => {
  assert.equal(isStorageObjectMissingError("row level security policy violation"), false);
  assert.equal(isStorageObjectMissingError("bucket unavailable"), false);
});

test("share owner lookup resolves merchant ids from snapshot business cards by share key", () => {
  assert.equal(
    findShareOwnerMerchantIdInSnapshotPayload(
      {
        revision: "snapshot-test-revision",
        defaultSortRule: "created_desc",
        merchantConfigHistoryBySiteId: {},
        snapshot: [
          {
            id: "12345678",
            merchantName: "Merchant A",
            signature: "",
            domainPrefix: "merchant-a",
            domainSuffix: "merchant-a",
            name: "Merchant A",
            domain: "merchant-a",
            category: "",
            industry: "",
            location: {
              countryCode: "",
              country: "",
              provinceCode: "",
              province: "",
              city: "",
            },
            contactAddress: "",
            contactName: "",
            contactPhone: "",
            contactEmail: "",
            merchantCardImageUrl: "",
            chatAvatarImageUrl: "",
            contactVisibility: {
              phoneHidden: false,
              emailHidden: false,
              businessCardHidden: false,
            },
            permissionConfig: {
              bookingEnabled: false,
              bookingsEnabled: false,
              shoppingEnabled: false,
              musicEnabled: false,
              productsEnabled: false,
              businessCardEnabled: false,
            },
            merchantCardImageOpacity: 1,
            businessCards: [
              {
                id: "card-1",
                createdAt: "2026-04-05T00:00:00.000Z",
                mode: "link",
                name: "Merchant Card",
                title: "",
                targetUrl: "https://merchant-a.faolla.com",
                imageUrl: "https://faolla.com/storage/v1/object/public/page-assets/card-a.png",
                shareImageUrl: "https://faolla.com/storage/v1/object/public/page-assets/card-a.png",
                contactPageImageUrl: "",
                contactPagePublicImageUrl: "",
                shareKey: "card-owner-a",
                backgroundImageUrl: "",
                backgroundImageOpacity: 1,
                backgroundColor: "#fff",
                backgroundColorOpacity: 1,
                width: 680,
                height: 432,
                ratioMode: "85:54",
                showWebsiteUrl: true,
                showQr: true,
                websiteLabel: "",
                contacts: {
                  contactName: "Felix",
                  phone: "633130577",
                  phones: ["633130577"],
                  email: "owner@example.com",
                  address: "",
                  wechat: "",
                  whatsapp: "",
                  twitter: "",
                  weibo: "",
                  telegram: "",
                  linkedin: "",
                  discord: "",
                  facebook: "",
                  instagram: "",
                  tiktok: "",
                  douyin: "",
                  xiaohongshu: "",
                },
                contactFieldOrder: ["contactName", "phone", "email", "address", "wechat", "whatsapp", "twitter", "weibo", "facebook", "instagram", "tiktok", "xiaohongshu", "douyin", "telegram", "linkedin", "discord"],
                contactOnlyFields: {
                  contactName: false,
                  phone: false,
                  email: false,
                  address: false,
                  wechat: false,
                  whatsapp: false,
                  twitter: false,
                  weibo: false,
                  telegram: false,
                  linkedin: false,
                  discord: false,
                  facebook: false,
                  instagram: false,
                  tiktok: false,
                  douyin: false,
                  xiaohongshu: false,
                },
                customTexts: [],
                textLayout: {
                  merchantName: { x: 0, y: 0 },
                  title: { x: 0, y: 0 },
                  website: { x: 0, y: 0 },
                  contactName: { x: 0, y: 0 },
                  phone: { x: 0, y: 0 },
                  email: { x: 0, y: 0 },
                  address: { x: 0, y: 0 },
                  wechat: { x: 0, y: 0 },
                  whatsapp: { x: 0, y: 0 },
                  twitter: { x: 0, y: 0 },
                  weibo: { x: 0, y: 0 },
                  telegram: { x: 0, y: 0 },
                  linkedin: { x: 0, y: 0 },
                  discord: { x: 0, y: 0 },
                  facebook: { x: 0, y: 0 },
                  instagram: { x: 0, y: 0 },
                  tiktok: { x: 0, y: 0 },
                  douyin: { x: 0, y: 0 },
                  xiaohongshu: { x: 0, y: 0 },
                },
                qr: { x: 0, y: 0, size: 120 },
                typography: {
                  name: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  title: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  website: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  info: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                },
                fieldTypography: {
                  merchantName: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  title: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  website: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  contactName: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  phone: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  email: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  address: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  wechat: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  whatsapp: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  twitter: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  weibo: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  telegram: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  linkedin: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  discord: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  facebook: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  instagram: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  tiktok: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  douyin: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  xiaohongshu: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                },
              },
            ],
            chatBusinessCard: null,
            status: "online",
            serviceExpiresAt: null,
            sortConfig: {
              recommendedCountryRank: null,
              recommendedProvinceRank: null,
              recommendedCityRank: null,
              industryCountryRank: null,
              industryProvinceRank: null,
              industryCityRank: null,
            },
            createdAt: "2026-04-05T00:00:00.000Z",
          },
        ],
      },
      {
        shareKey: "card-owner-a",
        preferredOrigin: "https://faolla.com",
      },
    ),
    "12345678",
  );
});

test("share owner lookup resolves legacy fingerprints from snapshot business cards", () => {
  const legacyPayload = normalizeMerchantBusinessCardSharePayload(
    {
      name: "Merchant Card",
      imageUrl: "https://faolla.com/storage/v1/object/public/page-assets/card-a.png",
      imageWidth: 680,
      imageHeight: 432,
      targetUrl: "https://merchant-a.faolla.com",
      contact: {
        displayName: "Felix",
        organization: "Merchant Card",
        phone: "633130577",
        phones: ["633130577"],
        contactFieldOrder: ["contactName", "phone", "email", "address", "wechat", "whatsapp", "twitter", "weibo", "facebook", "instagram", "tiktok", "xiaohongshu", "douyin", "telegram", "linkedin", "discord"],
        email: "owner@example.com",
        websiteUrl: "https://merchant-a.faolla.com",
      },
    },
    "https://faolla.com",
  );

  assert.equal(
    findShareOwnerMerchantIdInSnapshotPayload(
      {
        revision: "snapshot-test-revision",
        defaultSortRule: "created_desc",
        merchantConfigHistoryBySiteId: {},
        snapshot: [
          {
            id: "12345678",
            merchantName: "Merchant A",
            signature: "",
            domainPrefix: "merchant-a",
            domainSuffix: "merchant-a",
            name: "Merchant A",
            domain: "merchant-a",
            category: "",
            industry: "",
            location: {
              countryCode: "",
              country: "",
              provinceCode: "",
              province: "",
              city: "",
            },
            contactAddress: "",
            contactName: "",
            contactPhone: "",
            contactEmail: "",
            merchantCardImageUrl: "",
            chatAvatarImageUrl: "",
            contactVisibility: {
              phoneHidden: false,
              emailHidden: false,
              businessCardHidden: false,
            },
            permissionConfig: {
              bookingEnabled: false,
              bookingsEnabled: false,
              shoppingEnabled: false,
              musicEnabled: false,
              productsEnabled: false,
              businessCardEnabled: false,
            },
            merchantCardImageOpacity: 1,
            businessCards: [
              {
                id: "card-1",
                createdAt: "2026-04-05T00:00:00.000Z",
                mode: "link",
                name: "Merchant Card",
                title: "",
                targetUrl: "https://merchant-a.faolla.com",
                imageUrl: "https://faolla.com/storage/v1/object/public/page-assets/card-a.png",
                shareImageUrl: "https://faolla.com/storage/v1/object/public/page-assets/card-a.png",
                contactPageImageUrl: "",
                contactPagePublicImageUrl: "",
                shareKey: "",
                backgroundImageUrl: "",
                backgroundImageOpacity: 1,
                backgroundColor: "#fff",
                backgroundColorOpacity: 1,
                width: 680,
                height: 432,
                ratioMode: "85:54",
                showWebsiteUrl: true,
                showQr: true,
                websiteLabel: "",
                contacts: {
                  contactName: "Felix",
                  phone: "633130577",
                  phones: ["633130577"],
                  email: "owner@example.com",
                  address: "",
                  wechat: "",
                  whatsapp: "",
                  twitter: "",
                  weibo: "",
                  telegram: "",
                  linkedin: "",
                  discord: "",
                  facebook: "",
                  instagram: "",
                  tiktok: "",
                  douyin: "",
                  xiaohongshu: "",
                },
                contactFieldOrder: ["contactName", "phone", "email", "address", "wechat", "whatsapp", "twitter", "weibo", "facebook", "instagram", "tiktok", "xiaohongshu", "douyin", "telegram", "linkedin", "discord"],
                contactOnlyFields: {
                  contactName: false,
                  phone: false,
                  email: false,
                  address: false,
                  wechat: false,
                  whatsapp: false,
                  twitter: false,
                  weibo: false,
                  telegram: false,
                  linkedin: false,
                  discord: false,
                  facebook: false,
                  instagram: false,
                  tiktok: false,
                  douyin: false,
                  xiaohongshu: false,
                },
                customTexts: [],
                textLayout: {
                  merchantName: { x: 0, y: 0 },
                  title: { x: 0, y: 0 },
                  website: { x: 0, y: 0 },
                  contactName: { x: 0, y: 0 },
                  phone: { x: 0, y: 0 },
                  email: { x: 0, y: 0 },
                  address: { x: 0, y: 0 },
                  wechat: { x: 0, y: 0 },
                  whatsapp: { x: 0, y: 0 },
                  twitter: { x: 0, y: 0 },
                  weibo: { x: 0, y: 0 },
                  telegram: { x: 0, y: 0 },
                  linkedin: { x: 0, y: 0 },
                  discord: { x: 0, y: 0 },
                  facebook: { x: 0, y: 0 },
                  instagram: { x: 0, y: 0 },
                  tiktok: { x: 0, y: 0 },
                  douyin: { x: 0, y: 0 },
                  xiaohongshu: { x: 0, y: 0 },
                },
                qr: { x: 0, y: 0, size: 120 },
                typography: {
                  name: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  title: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  website: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  info: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                },
                fieldTypography: {
                  merchantName: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  title: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  website: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  contactName: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  phone: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  email: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  address: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  wechat: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  whatsapp: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  twitter: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  weibo: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  telegram: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  linkedin: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  discord: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  facebook: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  instagram: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  tiktok: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  douyin: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                  xiaohongshu: { fontFamily: "", fontSize: 16, fontColor: "#000", fontWeight: "normal", fontStyle: "normal", textDecoration: "none" },
                },
              },
            ],
            chatBusinessCard: null,
            status: "online",
            serviceExpiresAt: null,
            sortConfig: {
              recommendedCountryRank: null,
              recommendedProvinceRank: null,
              recommendedCityRank: null,
              industryCountryRank: null,
              industryProvinceRank: null,
              industryCityRank: null,
            },
            createdAt: "2026-04-05T00:00:00.000Z",
          },
        ],
      },
      {
        legacyPayload,
        preferredOrigin: "https://faolla.com",
      },
    ),
    "12345678",
  );
});
