import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import test from "node:test";
import { Script } from "node:vm";
import ts from "typescript";
import * as products from "@/lib/productBlock";
import * as orders from "@/lib/merchantOrders";

// The actual component and product derivation functions run here. Effects are
// registered but not executed: this suite covers render/interaction derivation,
// not catalog transport, persistence, authentication, or order submission.
const source = readFileSync(new URL("./ProductBlock.tsx", import.meta.url), "utf8").replaceAll("\r\n", "\n");
const BASELINE_COMMIT = "498acfbc";
const BASELINE_SHA256 = "da708edbfcd3cf78272f7238e7a4925f749c81a03683b4ee15e1bac12793d200";
// These exact declarations were captured from the actual pre-change component
// at BASELINE_COMMIT, not generated by copying the new memoized decision logic.
// Reconstruct only these four changes; the complete original-file hash guards
// every other rendering, cart, effect, ordering and submission statement.
const frozenDeclarations: Record<string, string> = {
  searchMatchedProducts: "const searchMatchedProducts = productSearchEnabled ? filterProductItemsByKeyword(arrangedProducts, searchKeyword) : arrangedProducts;",
  filteredProducts: "const filteredProducts =\n    tagHideUnselected && selectedTag ? searchMatchedProducts.filter((item) => item.tag === selectedTag) : searchMatchedProducts;",
  pagedProducts: 'const pagedProducts = containerMode === "paged" ? filteredProducts.slice(pageStart, pageStart + itemsPerPage) : filteredProducts;',
};
type Replacement = { start: number; end: number; text: string };
function replaceRanges(input: string, replacements: Replacement[]) {
  return replacements.sort((a, b) => b.start - a.start).reduce((value, replacement) =>
    value.slice(0, replacement.start) + replacement.text + value.slice(replacement.end), input);
}
function legacySource() {
  const parsed = ts.createSourceFile("ProductBlock.tsx", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const replacements: Replacement[] = [];
  function visit(node: ts.Node) {
    if (ts.isVariableStatement(node) && node.declarationList.declarations.length === 1) {
      const name = node.declarationList.declarations[0].name.getText(parsed);
      if (Object.hasOwn(frozenDeclarations, name)) replacements.push({ start: node.getStart(parsed), end: node.end, text: frozenDeclarations[name] });
      if (name === "productGroups") replacements.push({ start: node.getFullStart(), end: node.end, text: "" });
    }
    ts.forEachChild(node, visit);
  }
  visit(parsed); assert.equal(replacements.length, 4);
  const reconstructed = replaceRanges(source, replacements)
    .replace('if (groupedByTag) {\n      return (', 'if (groupedByTag) {\n      const groups = groupArrangedProductItemsByTag(pagedProducts);\n      return (')
    .replace('{productGroups.map((group, index) => (', '{groups.map((group, index) => (');
  assert.equal(createHash("sha256").update(reconstructed).digest("hex"), BASELINE_SHA256,
    `legacy oracle must remain the actual complete ${BASELINE_COMMIT} component`);
  return reconstructed;
}
type DerivedName = "searchMatchedProducts" | "filteredProducts" | "pagedProducts" | "productGroups";
function instrument(input: string) {
  const parsed = ts.createSourceFile("ProductBlock.tsx", input, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const replacements: Replacement[] = [];
  function visit(node: ts.Node) {
    if (ts.isVariableDeclaration(node) && node.initializer) {
      const name = node.name.getText(parsed);
      if (["searchMatchedProducts", "filteredProducts", "pagedProducts", "productGroups", "groups"].includes(name)) {
        const initializer = node.initializer;
        const expression = ts.isCallExpression(initializer) && initializer.expression.getText(parsed) === "useMemo"
          ? (initializer.arguments[0] as ts.ArrowFunction).body : initializer;
        assert.ok(!ts.isBlock(expression));
        replacements.push({ start: expression.getStart(parsed), end: expression.end,
          text: `__derive(${JSON.stringify(name === "groups" ? "productGroups" : name)}, () => (${expression.getText(parsed)}))` });
      }
    }
    ts.forEachChild(node, visit);
  }
  visit(parsed); assert.equal(replacements.length, 4);
  return ts.transpileModule(replaceRanges(input, replacements), {
    compilerOptions: { target: ts.ScriptTarget.ES2020, module: ts.ModuleKind.CommonJS, jsx: ts.JsxEmit.ReactJSX },
  }).outputText;
}
const compiled = instrument(source);
const oldCompiled = instrument(legacySource());
type Element = { type: string; props: Record<string, unknown> };
const fixture = [
  { id: "tea-1", name: "Café one", code: "A1", description: "hot drink", tag: "Tea", price: "12" },
  { id: "food-1", name: "Bread", code: "B1", description: "fresh", tag: "Food", price: "5" },
  { id: "tea-2", name: "Cafe two", code: "A2", description: "cold drink", tag: "Tea", price: "13" },
  { id: "tea-3", name: "Cafe three", code: "A3", description: "hot drink", tag: "Tea", price: "14" },
  { id: "food-2", name: "Cake", code: "B2", description: "cocoa", tag: "Food", price: "8" },
  { id: "none", name: "Water", code: "W1", description: "still", tag: "", price: "2" },
];

function harness(initial: Record<string, unknown> = {}, legacy = false) {
  let props: Record<string, unknown> = {
    products: structuredClone(fixture), productTagOptions: ["Food", "Tea"], productGroupByTag: true,
    productContainerMode: "paged", productItemsPerPage: 2,
    runtimeSiteId: "99990001", runtimeBlockId: "synthetic-products", runtimeOrderManagementEnabled: true,
    runtimeInteractiveOverlayWithinBlock: true, ...initial,
  };
  const slots: unknown[] = [];
  let cursor = 0;
  let hookCount: number | undefined;
  let searchCalls = 0;
  let groupCalls = 0;
  const derivationCalls: Record<DerivedName, number> = { searchMatchedProducts: 0, filteredProducts: 0, pagedProducts: 0, productGroups: 0 };
  const derivedValues: Partial<Record<DerivedName, unknown>> = {};
  let tree: Element;
  let timerId = 0;
  const timers = new Map<number, { callback: () => void; delay: number }>();
  const frames: Array<() => void> = [];
  const groupInputs: products.ProductItem[][] = [];
  const memoSlots = new Set<number>();
  const memo = (compute: () => unknown, deps: unknown[]) => {
    const index = cursor++;
    memoSlots.add(index);
    const previous = slots[index] as { deps: unknown[]; value: unknown } | undefined;
    if (!previous || deps.length !== previous.deps.length || deps.some((value, i) => !Object.is(value, previous.deps[i]))) {
      slots[index] = { deps: [...deps], value: compute() };
    }
    return (slots[index] as { value: unknown }).value;
  };
  const react = {
    useState: (initialState: unknown) => {
      const index = cursor++;
      if (!(index in slots)) slots[index] = typeof initialState === "function" ? initialState() : initialState;
      return [slots[index], (next: unknown) => { slots[index] = typeof next === "function" ? next(slots[index]) : next; }];
    },
    useRef: (initialValue: unknown) => { const index = cursor++; if (!(index in slots)) slots[index] = { current: initialValue }; return slots[index]; },
    useMemo: memo,
    useCallback: (callback: unknown, deps: unknown[]) => memo(() => callback, deps),
    useEffect: () => { cursor++; },
  };
  const jsx = (type: string, elementProps: Record<string, unknown>) => ({ type, props: elementProps });
  const sandboxModule = { exports: {} as { default: (input: Record<string, unknown>) => Element } };
  const setTimer = (callback: () => void, delay: number) => { timers.set(++timerId, { callback, delay }); return timerId; };
  new Script(legacy ? oldCompiled : compiled).runInNewContext({
    module: sandboxModule, exports: sandboxModule.exports,
    __derive: (name: DerivedName, compute: () => unknown) => {
      derivationCalls[name]++;
      const value = compute(); derivedValues[name] = value; return value;
    },
    require: (name: string) => {
      if (name === "react") return react;
      if (name === "react/jsx-runtime") return { jsx, jsxs: jsx, Fragment: "Fragment" };
      if (name === "react-dom") return { createPortal: (element: Element) => element };
      if (name === "next/image") return { default: "Image" };
      if (name === "@/components/PublicTrafficProvider") return { usePublicTraffic: () => null, usePublicTrafficExposure: () => undefined };
      if (name === "@/components/I18nProvider") return { useI18n: () => ({ locale: "zh" }) };
      if (name === "@/lib/productBlock") return {
        ...products,
        filterProductItemsByKeyword: (items: products.ProductItem[], query: string) => { searchCalls++; return products.filterProductItemsByKeyword(items, query); },
        groupArrangedProductItemsByTag: (items: products.ProductItem[]) => { groupCalls++; groupInputs.push(items); return products.groupArrangedProductItemsByTag(items); },
      };
      if (name === "@/lib/merchantOrders") return orders;
      if (name === "@/lib/publicAssetUrl") return { normalizePublicAssetUrl: (value: string) => value };
      if (name === "./backgroundStyle") return { getBackgroundStyle: () => ({}) };
      if (name === "./borderStyle") return { getBlockBorderClass: () => "", getBlockBorderInlineStyle: () => ({}) };
      if (name === "./mobileFrame") return { resolveMobileFitCardClass: (value: string) => value, resolveMobileFitSectionClass: (value: string) => value };
      if (name === "./richText") return { toRichHtml: (value: string) => value };
      if (name === "@/lib/editorSystemDefaults") return { resolveLocalizedSystemDefaultText: (value: string, fallback: string) => value || fallback };
      if (name === "@/lib/mobileSwipeBack") return { MOBILE_SWIPE_BACK_EVENT: "synthetic-swipe" };
      throw new Error(`Unexpected import: ${name}`);
    },
    window: { setTimeout: setTimer, innerHeight: 800 },
    document: { getElementById: () => null, querySelector: () => null },
    requestAnimationFrame: (callback: () => void) => { frames.push(callback); return frames.length; },
  });
  const render = () => {
    cursor = 0; tree = sandboxModule.exports.default(props);
    hookCount ??= cursor; assert.equal(cursor, hookCount); return tree;
  };
  const elements = () => {
    const result: Element[] = [];
    const visit = (value: unknown) => {
      if (Array.isArray(value)) { value.forEach(visit); return; }
      if (!value || typeof value !== "object") return;
      const element = value as Element;
      if (element.type) result.push(element);
      visit(element.props?.children);
    };
    visit(tree); return result;
  };
  const find = (predicate: (element: Element) => boolean) => { const element = elements().find(predicate); assert.ok(element); return element; };
  const event = { preventDefault() {}, stopPropagation() {}, currentTarget: { getBoundingClientRect: () => ({ left: 0, top: 0, width: 40, height: 40 }) } };
  const click = (element: Element) => { (element.props.onClick as (event: unknown) => void)(event); render(); };
  return {
    render, elements, find, click,
    counts: () => ({ searchCalls, groupCalls }),
    derivationCounts: () => ({ ...derivationCalls }),
    derived: () => ({ ...derivedValues }),
    snapshot: () => JSON.parse(JSON.stringify(tree, (_key, value: unknown) => typeof value === "function" ? "[function]" : value)) as unknown,
    discardMemoCache() { for (const index of memoSlots) slots[index] = undefined; render(); },
    lastGroupedPage: () => groupInputs[groupInputs.length - 1],
    setProps(next: Record<string, unknown>) { props = { ...props, ...next }; render(); },
    search(value: string) { (find((element) => element.type === "input" && element.props.type === "search").props.onChange as (event: unknown) => void)({ target: { value } }); render(); },
    tag(value: string) { click(find((element) => element.type === "button" && textOf(element) === value)); },
    button(value: string) { click(find((element) => element.type === "button" && (element.props["aria-label"] === value || textOf(element) === value))); },
    customer(value: string) { (find((element) => element.type === "input" && element.props.type === "text" && typeof element.props.value === "string").props.onChange as (event: unknown) => void)({ target: { value } }); render(); },
    runAnimations() { for (const delay of [440, 380, 720]) { for (const [id, timer] of [...timers]) if (timer.delay === delay) { timers.delete(id); timer.callback(); } while (frames.length) frames.shift()!(); render(); } },
  };
}

function textOf(value: unknown): string {
  if (Array.isArray(value)) return value.map(textOf).join("");
  if (value && typeof value === "object") return textOf((value as Element).props?.children);
  return typeof value === "string" || typeof value === "number" ? String(value) : "";
}
function visibleIds(h: ReturnType<typeof harness>) {
  return h.elements().filter((element) => element.props.role === "button" && String(element.props.id).startsWith("product-card-")).map((element) => String(element.props.id).slice("product-card-".length));
}
function catalog(input: Record<string, unknown> = {}) {
  return { status: "ready", catalog: {
    products: structuredClone(fixture), categories: [{ id: "food", name: "Food" }, { id: "tea", name: "Tea" }],
    revision: 1, updatedAt: "2026-09-26T00:00:00.000Z", pricePrefix: "€", ...input,
  } };
}

test("actual cart/customer handlers and animation renders reuse searched, tagged, paged and grouped products", () => {
  const h = harness(); h.render(); h.search("cafe"); h.tag("Tea");
  assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]);
  const page = h.lastGroupedPage(); const counts = h.counts();
  const derivations = h.derivationCounts(); const values = h.derived();
  h.button("增加购买数量"); h.runAnimations(); h.button("打开购物车"); h.button("客户信息");
  h.customer("Synthetic customer"); h.customer("Changed synthetic customer");
  h.setProps({ heading: "Unrelated heading" }); h.render();
  assert.deepEqual(h.counts(), counts); assert.strictEqual(h.lastGroupedPage(), page);
  assert.deepEqual(h.derivationCounts(), derivations);
  for (const name of Object.keys(values) as DerivedName[]) assert.strictEqual(h.derived()[name], values[name]);
  assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]);
});

test("search, category, page size and container changes preserve exact existing filter/order semantics", () => {
  const h = harness(); h.render();
  assert.deepEqual(visibleIds(h), ["food-1", "food-2"]);
  h.button("下一页"); assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]);
  h.search("CAFÉ hot"); assert.deepEqual(visibleIds(h), ["tea-1", "tea-3"]);
  h.tag("Food"); assert.deepEqual(visibleIds(h), []);
  h.tag("全部"); h.search(""); h.setProps({ productItemsPerPage: 1 });
  assert.deepEqual(visibleIds(h), ["food-1"]);
  h.setProps({ productContainerMode: "scroll" });
  const normalized = products.normalizeProductItems(fixture).filter(products.isMeaningfulProductItem);
  const expected = products.arrangeProductItemsByTag(normalized, ["Food", "Tea"], true);
  assert.deepEqual(visibleIds(h), expected.map((item) => item.id));
  h.setProps({ productGroupByTag: false });
  assert.deepEqual(visibleIds(h), normalized.map((item) => item.id));
});

test("new same-ID product arrays and tag order replace memoized results without cross-instance retention", () => {
  const h = harness(); h.render(); h.search("new-revision"); assert.deepEqual(visibleIds(h), []);
  const next = fixture.map((item) => ({ ...item, name: `New-revision ${item.name}` }));
  h.setProps({ products: next }); assert.deepEqual(visibleIds(h), ["food-1", "food-2"]);
  h.setProps({ productTagOptions: ["Tea", "Food"] }); assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]);
  const second = harness({ products: [{ id: "tea-1", name: "Separate row", tag: "Other" }] }); second.render();
  second.search("new-revision"); assert.deepEqual(visibleIds(second), []);
  assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]);
});

test("operating catalog browsing rules override props and invalidate each affected derivation", () => {
  const h = harness({ runtimeUseOperatingCatalog: true, runtimeCatalogOverride: catalog() }); h.render(); h.search("missing");
  assert.deepEqual(visibleIds(h), []);
  h.setProps({ runtimeCatalogOverride: catalog({ browsingRules: { searchEnabled: false, groupByCategory: false, hideUnselectedCategory: false } }) });
  assert.deepEqual(visibleIds(h), ["tea-1", "food-1"]);
  const disabledCounts = h.counts(); h.tag("Tea");
  assert.deepEqual(visibleIds(h), ["tea-1", "food-1"]); assert.equal(h.counts().searchCalls, disabledCounts.searchCalls);
  h.setProps({ runtimeCatalogOverride: catalog({ browsingRules: { searchEnabled: false, groupByCategory: true, hideUnselectedCategory: true } }) });
  assert.deepEqual(visibleIds(h), ["tea-1", "tea-2"]); // Existing selected-category/page behavior is deliberately retained.
  h.setProps({ runtimeCatalogOverride: catalog({ products: [{ id: "tea-1", name: "New only", tag: "Tea" }], browsingRules: { searchEnabled: false, groupByCategory: true, hideUnselectedCategory: true } }) });
  assert.deepEqual(visibleIds(h), ["tea-1"]);
});

test("loading/error/empty/ungrouped states do not run grouping and readiness resumes correct rows", () => {
  const h = harness({ runtimeUseOperatingCatalog: true, runtimeCatalogOverride: { status: "loading", catalog: null } }); h.render();
  assert.equal(h.counts().groupCalls, 0); assert.deepEqual(visibleIds(h), []);
  h.setProps({ runtimeCatalogOverride: { status: "error", catalog: null } });
  assert.equal(h.counts().groupCalls, 0); assert.deepEqual(visibleIds(h), []);
  h.setProps({ runtimeCatalogOverride: catalog() }); assert.deepEqual(visibleIds(h), ["food-1", "food-2"]);
  const counts = h.counts(); h.search("unmatched"); assert.equal(h.counts().groupCalls, counts.groupCalls);
  h.setProps({ productGroupByTag: false }); h.search(""); assert.equal(h.counts().groupCalls, counts.groupCalls);
  h.setProps({ productGroupByTag: true }); assert.equal(h.counts().groupCalls, counts.groupCalls + 1);
});

test("memo dependency sets are exact and every added hook precedes the component's return", () => {
  const parsed = ts.createSourceFile("ProductBlock.tsx", source, ts.ScriptTarget.Latest, true, ts.ScriptKind.TSX);
  const component = parsed.statements.find((node): node is ts.FunctionDeclaration => ts.isFunctionDeclaration(node) && node.name?.text === "ProductBlock")!;
  const returned = component.body!.statements.find(ts.isReturnStatement)!;
  const expected: Record<string, string[]> = {
    searchMatchedProducts: ["arrangedProducts", "productSearchEnabled", "searchKeyword"],
    filteredProducts: ["searchMatchedProducts", "selectedTag", "tagHideUnselected"],
    pagedProducts: ["containerMode", "filteredProducts", "itemsPerPage", "pageStart"],
    productGroups: ["filteredProducts.length", "groupedByTag", "pagedProducts", "runtimeCatalogError", "runtimeCatalogLoading"],
  };
  const seen = new Set<string>();
  for (const statement of component.body!.statements) {
    if (!ts.isVariableStatement(statement)) continue;
    for (const declaration of statement.declarationList.declarations) {
      const name = declaration.name.getText(parsed);
      if (!Object.hasOwn(expected, name)) continue;
      seen.add(name); assert.ok(statement.end < returned.getStart(parsed));
      const initializer = declaration.initializer!; assert.ok(ts.isCallExpression(initializer));
      assert.equal(initializer.expression.getText(parsed), "useMemo");
      const dependencies = initializer.arguments[1]; assert.ok(ts.isArrayLiteralExpression(dependencies));
      assert.deepEqual(dependencies.elements.map((element) => element.getText(parsed)), expected[name]);
    }
  }
  assert.equal(seen.size, 4);
  assert.equal(createHash("sha256").update(legacySource()).digest("hex"), BASELINE_SHA256);
});

test("query, tag, page, page-size and rule changes rerun only their affected derivation stages", () => {
  const h = harness(); h.render();
  function changed(action: () => void, expected: Partial<Record<DerivedName, number>>) {
    const before = h.derivationCounts(); action(); const after = h.derivationCounts();
    for (const name of Object.keys(before) as DerivedName[]) assert.equal(after[name] - before[name], expected[name] ?? 0, name);
  }
  changed(() => h.search("cafe"), { searchMatchedProducts: 1, filteredProducts: 1, pagedProducts: 1, productGroups: 1 });
  changed(() => h.tag("Tea"), { filteredProducts: 1, pagedProducts: 1, productGroups: 1 });
  changed(() => h.button("下一页"), { pagedProducts: 1, productGroups: 1 });
  changed(() => h.setProps({ productItemsPerPage: 1 }), { pagedProducts: 1, productGroups: 1 });
  changed(() => h.setProps({ productTagHideUnselected: false }), { filteredProducts: 1, pagedProducts: 1, productGroups: 1 });
  const searches = h.counts().searchCalls;
  changed(() => h.setProps({ productSearchEnabled: false }), { searchMatchedProducts: 1, filteredProducts: 1, pagedProducts: 1, productGroups: 1 });
  assert.equal(h.counts().searchCalls, searches, "disabled search must not invoke the search helper");
  changed(() => h.setProps({ heading: "Unrelated", productCardBgColor: "#102030" }), {});
  changed(() => h.render(), {});
});

test("actual old component repeats derivations on unrelated/cart redraws while memoized output stays identical", () => {
  const current = harness(); const legacy = harness({}, true);
  for (const app of [current, legacy]) { app.render(); app.search("cafe"); app.tag("Tea"); }
  assert.deepEqual(current.snapshot(), legacy.snapshot());
  const currentBefore = current.derivationCounts(); const oldBefore = legacy.derivationCounts();
  for (const app of [current, legacy]) {
    app.button("增加购买数量"); app.runAnimations(); app.button("打开购物车"); app.button("客户信息");
    app.customer("Synthetic customer"); app.customer("Changed synthetic customer"); app.setProps({ heading: "Unrelated" }); app.render();
  }
  assert.deepEqual(current.snapshot(), legacy.snapshot());
  assert.deepEqual(current.derivationCounts(), currentBefore);
  for (const name of Object.keys(oldBefore) as DerivedName[]) {
    assert.ok(legacy.derivationCounts()[name] > oldBefore[name] + 5, `old ${name} must exhibit actual repeated work`);
  }
});

test("frozen old-module parity covers query/tag/paging/layout changes and changed same-ID product data", () => {
  for (const layout of ["grid", "list", "spotlight"]) {
    const current = harness({ productLayoutPreset: layout }); const legacy = harness({ productLayoutPreset: layout }, true);
    const compareStep = (action: (app: ReturnType<typeof harness>) => void) => {
      action(current); action(legacy); assert.deepEqual(current.snapshot(), legacy.snapshot(), layout);
    };
    compareStep((app) => { app.render(); });
    compareStep((app) => app.button("下一页"));
    compareStep((app) => app.search("CAFÉ hot"));
    compareStep((app) => app.tag("Food"));
    compareStep((app) => app.tag("全部"));
    compareStep((app) => app.search(""));
    compareStep((app) => app.setProps({ productItemsPerPage: 1 }));
    compareStep((app) => app.setProps({ productTagOptions: ["Tea", "Food"] }));
    compareStep((app) => app.setProps({ productContainerMode: "scroll" }));
    compareStep((app) => app.setProps({ productGroupByTag: false, productTagHideUnselected: false }));
    compareStep((app) => app.search("new-only"));
    compareStep((app) => app.setProps({ products: fixture.map((item) => ({ ...item, name: `New-only ${item.name}`, price: "99" })) }));
    compareStep((app) => app.setProps({ products: [] }));
  }
});

test("frozen old-module parity covers loading/error/empty and operating browsing-rule/catalog changes", () => {
  const options = { runtimeUseOperatingCatalog: true, runtimeCatalogOverride: { status: "loading", catalog: null } };
  const current = harness(options); const legacy = harness(options, true);
  const compareStep = (action: (app: ReturnType<typeof harness>) => void) => {
    action(current); action(legacy); assert.deepEqual(current.snapshot(), legacy.snapshot());
  };
  compareStep((app) => { app.render(); });
  compareStep((app) => app.setProps({ runtimeCatalogOverride: { status: "error", catalog: null } }));
  assert.equal(current.counts().groupCalls, 0); assert.equal(legacy.counts().groupCalls, 0);
  compareStep((app) => app.setProps({ runtimeCatalogOverride: catalog() }));
  compareStep((app) => app.search("missing"));
  compareStep((app) => app.setProps({ runtimeCatalogOverride: catalog({ browsingRules: { searchEnabled: false, groupByCategory: false, hideUnselectedCategory: false } }) }));
  compareStep((app) => app.tag("Tea"));
  compareStep((app) => app.setProps({ runtimeCatalogOverride: catalog({ browsingRules: { searchEnabled: false, groupByCategory: true, hideUnselectedCategory: true } }) }));
  compareStep((app) => app.setProps({ runtimeCatalogOverride: catalog({ products: [{ id: "tea-1", name: "Changed same ID", tag: "Tea", price: "77" }] }) }));
  compareStep((app) => app.setProps({ runtimeCatalogOverride: catalog({ products: [] }) }));
});

test("discarding memo caches recomputes safely without mutating frozen product inputs or changing cart state", () => {
  const frozenProducts = Object.freeze(fixture.map((item) => Object.freeze({ ...item })));
  const before = JSON.stringify(frozenProducts);
  const h = harness({ products: frozenProducts }); h.render(); h.search("cafe"); h.tag("Tea");
  h.button("增加购买数量"); h.runAnimations(); h.button("打开购物车");
  const rendered = h.snapshot(); const counts = h.derivationCounts();
  h.discardMemoCache(); assert.deepEqual(h.snapshot(), rendered);
  for (const name of Object.keys(counts) as DerivedName[]) assert.equal(h.derivationCounts()[name], counts[name] + 1);
  assert.equal(JSON.stringify(frozenProducts), before);
});
