"use client";
import { useCallback,useEffect,useMemo,useRef,useState,useSyncExternalStore } from "react";
import { flushSync } from "react-dom";
import type { AttendanceApiFetch } from "@/lib/merchantAttendanceSelfClient";
import { AttendanceReviewRoutingClient } from "@/lib/merchantAttendanceReviewRoutingClient";
import { REVIEW_ROUTING_FAMILIES,type ReviewRoutingFamily,type ReviewRoutingEntry,type ReviewRoutingRequest } from "@/lib/merchantAttendanceReviewRouting";
const button="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-semibold disabled:opacity-40",field="mt-1 block w-full min-w-0 rounded-xl border p-3";
const currentAuth=()=>true;
export const reviewRoutingFamilyName:Record<ReviewRoutingFamily,string>={correction:"首次补正",correction_revision:"补正修订",missing:"整段漏卡",missing_revision:"漏卡修订",leave:"请假",work_arrangement:"工作安排"};
const reasonName={no_grant:"没有当前可用授权",ambiguous_grant:"存在多个可用授权",candidate_limit:"候选超过自动核验上限",source_scope_unavailable:"来源范围暂时不可核实",owner_changed:"负责人已变化",grant_unavailable:"原办理授权现已不可用",binding_changed:"原员工身份绑定已变化"};
export type ReviewRoutingPanelProps={siteId:string;authUserId:string;apiFetch:AttendanceApiFetch;enabled?:boolean;isCurrentAuth?:()=>boolean;onClose:()=>void;registerLeaveGuard?:(guard:(()=>boolean)|null)=>void;onOpenOriginal?:(request:ReviewRoutingRequest)=>boolean};
export function ReviewRoutingEntryView({entry}:{entry:ReviewRoutingEntry}){const a=entry.assignment;return <div className="min-w-0 space-y-1 rounded-xl border p-3 text-sm"><p>责任版本 {entry.revision} · {entry.action==="capture"?"提交时固定":entry.action==="register"?"明确登记":"负责人接手"} · {entry.recordedAt}</p><p>{a.kind==="owner"?"由当时负责人协调":a.kind==="delegate"?"已分派至有授权的办理人":reasonName[a.reason]}</p>{entry.reason&&<p className="whitespace-pre-wrap break-words">说明：{entry.reason}</p>}<p className="break-all">原编号：{entry.operationId}</p></div>;}
export default function MerchantAttendanceReviewRoutingPanel({siteId,authUserId,apiFetch,enabled=process.env.NEXT_PUBLIC_FAOLLA_ATTENDANCE_REVIEW_ROUTING_ENABLED==="1",isCurrentAuth=currentAuth,onClose,registerLeaveGuard,onOpenOriginal}:ReviewRoutingPanelProps){
  const marker=useMemo(()=>({siteId,authUserId,apiFetch,enabled,isCurrentAuth}),[siteId,authUserId,apiFetch,enabled,isCurrentAuth]),liveMarker=useRef(marker),mounted=useRef(false);liveMarker.current=marker;
  const live=useCallback(()=>mounted.current&&liveMarker.current===marker&&isCurrentAuth()===true,[marker,isCurrentAuth]);
  const client=useMemo(()=>new AttendanceReviewRoutingClient({...marker,isCurrentAuth:live,storage:()=>{if(!live())throw Error("scope_changed");return sessionStorage;}}),[marker,live]);
  const state=useSyncExternalStore(client.subscribe,client.getSnapshot,client.getSnapshot),[draft,setDraft]=useState({marker,reason:"",ack:false}),[lookup,setLookup]=useState({marker,family:"correction" as ReviewRoutingFamily,requestId:""}),[selection,setSelection]=useState({marker,grantId:"",requestScope:""}),[message,setMessage]=useState({marker,value:""}),dirty=useRef(false);
  const currentDraft=draft.marker===marker?draft:{marker,reason:"",ack:false},currentLookup=lookup.marker===marker?lookup:{marker,family:"correction" as ReviewRoutingFamily,requestId:""};
  const clear=useCallback(()=>{dirty.current=false;setDraft({marker,reason:"",ack:false});setMessage({marker,value:""});},[marker]);
  const leave=useCallback(()=>{if((dirty.current||client.hasLeaveRisk())&&!window.confirm("离开会清除未提交说明；待确认原编号保留。确定离开？"))return false;client.pause();clear();return true;},[client,clear]);
  useEffect(()=>{registerLeaveGuard?.(leave);return()=>registerLeaveGuard?.(null);},[leave,registerLeaveGuard]);
  useEffect(()=>{mounted.current=true;void client.initialize();const hide=()=>{if(document.hidden)flushSync(()=>{client.pause();clear();setSelection({marker,grantId:"",requestScope:""});});else void client.initialize();},pagehide=()=>{client.pause();clear();setSelection({marker,grantId:"",requestScope:""});},unload=(e:BeforeUnloadEvent)=>{if(dirty.current||client.hasLeaveRisk()){e.preventDefault();e.returnValue="";}};document.addEventListener("visibilitychange",hide);window.addEventListener("pagehide",pagehide);window.addEventListener("beforeunload",unload);return()=>{mounted.current=false;client.pause();document.removeEventListener("visibilitychange",hide);window.removeEventListener("pagehide",pagehide);window.removeEventListener("beforeunload",unload);};},[client,clear,marker]);
  const busy=state.phase==="loading"||state.phase==="saving",d=state.result?.data,detail=d?.kind==="detail"?d:null;
  const selected=selection.marker===marker&&!!selection.grantId&&!!detail&&selection.requestScope===detail.request.family+detail.request.requestId;
  const read=async(work:()=>Promise<void>)=>{if(!live()||document.hidden||busy||state.pending||dirty.current&&!window.confirm("读取其他资料会清除未提交说明，是否继续？"))return;clear();try{await work();}catch{if(live())setMessage({marker,value:"申请编号不符合要求，请检查。"});}};
  const valid=currentDraft.reason===currentDraft.reason.trim()&&[...currentDraft.reason].length>=1&&[...currentDraft.reason].length<=200&&!/[\u0000-\u001f\u007f-\u009f]/u.test(currentDraft.reason),canAct=enabled&&!busy&&!state.pending&&valid&&currentDraft.ack;
  const submit=async(action:"register"|"take_over")=>{if(!live()||document.hidden||!canAct||action==="register"&&!selected||!window.confirm(action==="take_over"?"确认由当前负责人接手协调？原申请仍需按当前审批权限核验。":"确认将该申请登记给已明确选择的授权办理人？"))return;try{await client.act(action,currentDraft.reason);if(live()&&(client.getSnapshot().pending||client.getSnapshot().result?.data.kind==="receipt")){clear();setSelection({marker,grantId:"",requestScope:""});}}catch{if(live())setMessage({marker,value:"请检查说明与最新读取结果；没有自动重试。"});}};
  const original=async()=>{if(!detail||!onOpenOriginal||busy||state.pending||dirty.current)return;const ref=await client.freshOriginal(detail.request);if(!ref||!live()||document.hidden||!leave())return;if(onOpenOriginal(ref))onClose();else if(live())setMessage({marker,value:"请先完成或关闭原申请工作区，再重新读取。"});};
  const next=d?.kind==="list"||d?.kind==="grants"?!!d.nextCursor:d?.kind==="history"?d.nextBeforeRevision!==null:false;
  return <section aria-label="办理责任工作区" className="min-w-0 max-w-full space-y-4 rounded-2xl border bg-white p-4 text-slate-900"><header className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-xl font-bold">办理责任</h2><button className={button} type="button" onClick={()=>{if(leave())onClose();}}>关闭办理责任</button></header><p className="text-sm">查看申请交由谁办理，并明确登记或接手协调。审批资格仍由原申请核验。</p>{!enabled&&<p>新的责任变更未开放；已保存责任和原号仍可核验。</p>}<p role="status" className="break-words text-sm">{message.marker===marker&&message.value||state.message}</p>
    {state.pending?<div className="space-y-2"><p className="break-all">待确认原编号：{state.pending.command.operationId}</p><button className={button} type="button" disabled={busy} onClick={()=>void client.recover()}>仅 GET 核验办理原编号</button></div>:<><button className={button} type="button" disabled={busy} onClick={()=>void read(client.list)}>读取办理责任列表</button><div className="grid min-w-0 gap-3 sm:grid-cols-[minmax(0,1fr)_minmax(0,2fr)]"><label>申请类型<select className={field} value={currentLookup.family} onChange={e=>setLookup({...currentLookup,family:e.target.value as ReviewRoutingFamily})}>{REVIEW_ROUTING_FAMILIES.map(f=><option key={f} value={f}>{reviewRoutingFamilyName[f]}</option>)}</select></label><label>申请编号<input aria-label="办理责任申请编号" className={field} value={currentLookup.requestId} onChange={e=>setLookup({...currentLookup,requestId:e.target.value})}/></label></div><button className={button} type="button" disabled={busy} onClick={()=>void read(()=>client.detail(currentLookup.family,currentLookup.requestId))}>读取指定申请办理详情</button></>}
    {d?.kind==="list"&&<div className="space-y-2"><p className="text-sm">每页最多 25 条；含已结束申请，实际待审以原目录为准。</p>{d.items.map(i=><div className="min-w-0 rounded-xl border p-3" key={i.request.family+i.request.requestId}><p>{reviewRoutingFamilyName[i.request.family]} · {i.observation.routeState==="closed"?"原申请已结束":i.observation.routeState==="handover_needed"?"需要接手协调":i.observation.routeState==="needs_assignment"?"需要明确分派":"已有办理责任"}</p><p className="break-all text-xs">{i.request.requestId}</p><button className={button} type="button" disabled={busy} onClick={()=>void read(()=>client.detail(i.request.family,i.request.requestId))}>读取此申请办理详情</button></div>)}</div>}
    {d?.kind==="grants"&&<div className="space-y-2"><p>明确选择一名当前可办理的授权人员，再重新读取申请确认。</p>{d.items.map(g=><div className="rounded-xl border p-3" key={g.grantId}><p>{g.delegateName} · {g.usable?"本次核验可办理":"当前不可办理"}</p><button className={button} type="button" disabled={busy||!g.usable} onClick={()=>{if(client.selectGrant(g.grantId)){setSelection({marker,grantId:g.grantId,requestScope:d.request.family+d.request.requestId});void read(()=>client.detail(d.request.family,d.request.requestId));}}}>选择此授权并重读申请</button></div>)}{!d.items.length&&<p>没有本页可选择的授权。</p>}</div>}
    {d?.kind==="history"&&<div className="space-y-2">{d.items.map(e=><ReviewRoutingEntryView key={e.operationId} entry={e}/>)}</div>}{next&&<button className={button} type="button" disabled={busy} onClick={()=>void read(client.nextPage)}>读取下一页</button>}
    {detail&&<div className="min-w-0 space-y-3"><p className="break-all">{reviewRoutingFamilyName[detail.request.family]} · 申请 {detail.request.requestId}</p><p className="break-all text-xs">原考勤人员：{detail.request.workerId} · 原员工：{detail.request.employeeId}</p>{detail.current?<ReviewRoutingEntryView entry={detail.current}/>:<p>此申请尚未登记办理责任。</p>}<p>{detail.observation.reason?reasonName[detail.observation.reason]:detail.observation.routeState==="closed"?"原申请已结束":"当前观察已核验"}</p><div className="flex flex-wrap gap-2"><button className={button} type="button" disabled={busy} onClick={()=>void read(()=>client.history(detail.request.family,detail.request.requestId))}>读取责任历史</button>{detail.canRegister&&<button className={button} type="button" disabled={busy} onClick={()=>void read(()=>client.grants(detail.request.family,detail.request.requestId))}>读取可选择办理授权</button>}{onOpenOriginal&&<button className={button} type="button" disabled={busy||!!state.pending||dirty.current} onClick={()=>void original()}>重新核验并打开原申请</button>}</div>
      {enabled&&(detail.canRegister||detail.canTakeOver)&&<fieldset disabled={busy||!!state.pending} className="min-w-0 space-y-3 rounded-xl border p-3"><legend>明确处理办理责任</legend>{selected&&<p className="break-all text-xs">已选授权：{selection.grantId}</p>}<label>登记／接手说明<textarea aria-label="办理责任说明" className={field} rows={3} value={currentDraft.reason} onChange={e=>{dirty.current=true;setDraft({...currentDraft,reason:e.target.value,ack:false});}}/></label><label className="block text-sm"><input type="checkbox" checked={currentDraft.ack} onChange={e=>{dirty.current=true;setDraft({...currentDraft,ack:e.target.checked});}}/> 我已核对原申请，理解责任登记不授予审批权限。</label><div className="flex flex-wrap gap-2">{detail.canRegister&&<button className={button} type="button" disabled={!canAct||!selected} onClick={()=>void submit("register")}>确认登记所选办理人</button>}{detail.canTakeOver&&<button className={button} type="button" disabled={!canAct} onClick={()=>void submit("take_over")}>负责人明确接手协调</button>}</div></fieldset>}</div>}
    {d?.kind==="receipt"&&<p className="break-all rounded-xl bg-slate-50 p-3">{state.result?.receipt?`已核实原编号 ${state.result.receipt.operationId}，责任版本 ${state.result.receipt.revision}。请重读申请后继续。`:"尚未找到原号回执，原编号继续保留。"}</p>}
  </section>;
}
