"use client";
import type { ReactNode } from "react";
import { OPERATIONAL_RULE_KEYS, OPERATIONAL_RULE_CHANNELS, OPERATIONAL_RULE_REVIEW_CATEGORIES, OPERATIONAL_RULE_REMINDER_KINDS,
  parseOperationalRules, type OperationalRules, type OperationalRuleKey, type OperationalRuleValues, type OperationalReminder } from "@/lib/merchantAttendanceOperationalRules";

export const operationalRuleNames: Record<OperationalRuleKey, string> = { allowedChannels: "允许打卡渠道", locationScope: "地点范围", shiftSource: "班次来源", breakTypes: "休息类型",
  correctionWindow: "补正窗口", reviewRouting: "审核路由", timesheetCycle: "周期方式", reminders: "提醒配置" };
export const operationalReviewNames = { correction: "首次补正", missing: "整段漏卡", leave: "请假", work_arrangement: "工作安排" } as const;
export const operationalReminderNames = { open_session: "未闭合班次", pending_review: "待审核", period_due: "周期待办" } as const;
const channelNames = { self: "普通网页", location: "定位", pin: "PIN", onsite: "现场" } as const;
const input = "mt-1 w-full min-w-0 rounded-xl border border-slate-300 bg-white p-2 text-sm";
const button = "rounded-xl border border-slate-300 bg-white px-3 py-2 text-sm disabled:opacity-40";
export const emptyOperationalRules = (): OperationalRules => parseOperationalRules(Object.fromEntries(OPERATIONAL_RULE_KEYS.map(k => [k, { mode: "inherit" }])));
export const operationalRuleReasonValid = (v: string) => v === v.trim() && [...v].length > 0 && [...v].length <= 200 && !/[\u0000-\u001f\u007f-\u009f]/.test(v);
export function operationalRuleFormValid(rules: OperationalRules, reason: string) { try { parseOperationalRules(rules); return operationalRuleReasonValid(reason); } catch { return false; } }
export function operationalRuleDefault<K extends OperationalRuleKey>(key: K): OperationalRuleValues[K] {
  const values: OperationalRuleValues = { allowedChannels: ["self"], locationScope: [], shiftSource: "published_selection", breakTypes: { allowed: ["unpaid"], selection: "fixed" },
    correctionWindow: { days: 0 }, reviewRouting: { correction: "owner", missing: "owner", leave: "owner", work_arrangement: "owner" }, timesheetCycle: { kind: "manual" },
    reminders: { open_session: { mode: "disabled" }, pending_review: { mode: "disabled" }, period_due: { mode: "disabled" } } };
  return values[key];
}
export type OperationalRouteChoice = { employeeId: string; employeeName: string; employeeAuthUserId: string };
export type OperationalLocationChoice = { id: string; name: string; active: boolean };
export function OperationalRulesFields({ rules, disabled, onChange, locations = [], routes = [], readLocations, nextLocations, readRoutes, nextRoutes }: {
  rules: OperationalRules; disabled: boolean; onChange: (rules: OperationalRules) => void; locations?: readonly OperationalLocationChoice[];
  routes?: readonly OperationalRouteChoice[]; readLocations?: () => void; nextLocations?: () => void; readRoutes?: () => void; nextRoutes?: () => void;
}) {
  const value = <K extends OperationalRuleKey,>(key: K, v: OperationalRuleValues[K]) => onChange({ ...rules, [key]: { mode: "value", value: v } });
  const number = (label: string, v: number, min: number, max: number, change: (v: number) => void) => <label className="block min-w-0 text-sm">{label}<input aria-label={label} type="number" className={input} min={min} max={max} step={1} value={Number.isNaN(v) ? "" : v} onChange={e => change(e.target.value === "" ? NaN : Number(e.target.value))}/></label>;
  const fields: Partial<Record<OperationalRuleKey, ReactNode>> = {};
  if (rules.allowedChannels.mode === "value") { const v = rules.allowedChannels.value;
    fields.allowedChannels = <div className="flex flex-wrap gap-3">{OPERATIONAL_RULE_CHANNELS.map(k => <label className="flex gap-2 text-sm" key={k}><input type="checkbox" aria-label={`允许${channelNames[k]}渠道`} checked={v.includes(k)} onChange={e => value("allowedChannels", OPERATIONAL_RULE_CHANNELS.filter(x => x === k ? e.target.checked : v.includes(x)))}/>{channelNames[k]}</label>)}</div>; }
  if (rules.locationScope.mode === "value") { const v = rules.locationScope.value;
    fields.locationScope = <div className="space-y-2"><p className="text-xs">从同商户分页目录明确选择 1–25 个地点；停用地点不代表可以发布。只保存引用，不授予地点访问。</p>
      {readLocations && <button type="button" className={button} onClick={readLocations}>读取地点目录</button>}
      <ul className="space-y-2">{locations.map(l => <li key={l.id}><label className="flex min-w-0 gap-2 text-sm"><input aria-label={`选择地点 ${l.name}`} type="checkbox" checked={v.includes(l.id)} disabled={!v.includes(l.id) && v.length >= 25} onChange={e => value("locationScope", (e.target.checked ? [...v, l.id] : v.filter(id => id !== l.id)).sort())}/><span className="break-words">{l.name} · {l.active ? "启用" : "停用"}</span></label></li>)}</ul>
      {nextLocations && <button type="button" className={button} onClick={nextLocations}>下一页地点</button>}
      <p className="text-xs">已选 {v.length} / 25；以下为保存的精确编号，不推断历史名称。</p><ul>{v.map(id => <li key={id} className="flex min-w-0 flex-wrap items-center gap-2"><span className="break-all text-xs">{id}</span>{!disabled && <button type="button" className={button} aria-label={`移除地点 ${id}`} onClick={() => value("locationScope", v.filter(x => x !== id))}>移除</button>}</li>)}</ul></div>; }
  if (rules.shiftSource.mode === "value") fields.shiftSource = <label className="block text-sm">班次来源值<select aria-label="班次来源值" className={input} value={rules.shiftSource.value} onChange={e => value("shiftSource", e.target.value as "published_selection" | "unplanned")}><option value="published_selection">已发布班次选择</option><option value="unplanned">无计划班次</option></select></label>;
  if (rules.breakTypes.mode === "value") { const v = rules.breakTypes.value; fields.breakTypes = <div className="space-y-2"><label className="block text-sm">休息选择方式<select className={input} aria-label="休息选择方式" value={v.selection} onChange={e => value("breakTypes", { ...v, selection: e.target.value as "fixed" | "explicit" })}><option value="fixed">固定一种（必须仅选一项）</option><option value="explicit">明确选择</option></select></label><div className="flex flex-wrap gap-3">{(["paid", "unpaid"] as const).map(k => <label key={k} className="flex gap-2 text-sm"><input aria-label={k === "paid" ? "允许带薪休息" : "允许无薪休息"} type="checkbox" checked={v.allowed.includes(k)} onChange={e => value("breakTypes", { ...v, allowed: (["paid", "unpaid"] as const).filter(x => x === k ? e.target.checked : v.allowed.includes(x)) })}/>{k === "paid" ? "带薪" : "无薪"}</label>)}</div></div>; }
  if (rules.correctionWindow.mode === "value") fields.correctionWindow = number("补正窗口天数（0–365）", rules.correctionWindow.value.days, 0, 365, days => value("correctionWindow", { days }));
  if (rules.reviewRouting.mode === "value") { const v = rules.reviewRouting.value; fields.reviewRouting = <div className="space-y-3"><p className="text-xs">路由不是审批授权；选中成员仍须在未来业务中另验具体委托。不会因此自动发送提醒。</p>{readRoutes && <button type="button" className={button} onClick={readRoutes}>读取路由成员目录</button>}
      {OPERATIONAL_RULE_REVIEW_CATEGORIES.map(k => { const target = v[k], selected = target === "owner" ? "owner" : JSON.stringify([target.delegateEmployeeId, target.delegateAuthUserId]);
        const available = routes.some(r => JSON.stringify([r.employeeId, r.employeeAuthUserId]) === selected);
        return <label className="block min-w-0 text-sm" key={k}>{operationalReviewNames[k]}路由<select aria-label={`${operationalReviewNames[k]}路由`} className={input} value={selected} onChange={e => { const next = e.target.value === "owner" ? "owner" : routes.find(r => JSON.stringify([r.employeeId, r.employeeAuthUserId]) === e.target.value); if (next) value("reviewRouting", { ...v, [k]: next === "owner" ? "owner" : { delegateEmployeeId: next.employeeId, delegateAuthUserId: next.employeeAuthUserId } }); }}><option value="owner">业务当时的负责人</option>{target !== "owner" && !available && <option value={selected}>保存的成员身份（非本页目录）</option>}{routes.map(r => <option key={r.employeeId} value={JSON.stringify([r.employeeId, r.employeeAuthUserId])}>{r.employeeName}</option>)}</select>{target !== "owner" && <span className="mt-1 block break-all text-xs">员工 {target.delegateEmployeeId} · Auth {target.delegateAuthUserId}</span>}</label>; })}
      {nextRoutes && <button type="button" className={button} onClick={nextRoutes}>下一页路由成员</button>}</div>; }
  if (rules.timesheetCycle.mode === "value") { const v = rules.timesheetCycle.value; fields.timesheetCycle = <div className="space-y-2"><label className="block text-sm">周期方式值<select aria-label="周期方式值" className={input} value={v.kind} onChange={e => { const k = e.target.value; value("timesheetCycle", k === "weekly" ? { kind: k, weekStartsOn: 1 } : k === "fortnightly" ? { kind: k, anchorDate: "" } : { kind: k as "monthly" | "manual" }); }}><option value="manual">手动</option><option value="weekly">每周</option><option value="fortnightly">每两周</option><option value="monthly">每月</option></select></label>{v.kind === "weekly" && number("每周起始日（1=周一，7=周日）", v.weekStartsOn, 1, 7, weekStartsOn => value("timesheetCycle", { ...v, weekStartsOn }))}{v.kind === "fortnightly" && <label className="block text-sm">两周周期锚点日期<input aria-label="两周周期锚点日期" type="date" min="0001-01-01" max="9999-12-31" className={input} value={v.anchorDate} onChange={e => value("timesheetCycle", { ...v, anchorDate: e.target.value })}/></label>}<p className="text-xs">只保存方式，不自动创建周期。</p></div>; }
  if (rules.reminders.mode === "value") { const v = rules.reminders.value; fields.reminders = <div className="space-y-3">{OPERATIONAL_RULE_REMINDER_KINDS.map(k => { const r = v[k], change = (next: OperationalReminder) => value("reminders", { ...v, [k]: next }); return <section key={k} className="space-y-2 rounded-xl bg-slate-50 p-3"><label className="block text-sm">{operationalReminderNames[k]}提醒<select aria-label={`${operationalReminderNames[k]}提醒`} className={input} value={r.mode} onChange={e => change(e.target.value === "disabled" ? { mode: "disabled" } : { mode: "enabled", afterMinutes: 60, repeatMinutes: 60, maxOccurrences: 1 })}><option value="disabled">停用</option><option value="enabled">配置</option></select></label>{r.mode === "enabled" && <div className="grid min-w-0 gap-2 sm:grid-cols-3">{number(`${operationalReminderNames[k]}首次等待分钟`, r.afterMinutes, 1, 44640, afterMinutes => change({ ...r, afterMinutes }))}{number(`${operationalReminderNames[k]}重复间隔分钟`, r.repeatMinutes, 60, 44640, repeatMinutes => change({ ...r, repeatMinutes }))}{number(`${operationalReminderNames[k]}最多次数`, r.maxOccurrences, 1, 10, maxOccurrences => change({ ...r, maxOccurrences }))}</div>}</section>; })}<p className="text-xs">这是提醒配置，不是已经启动自动提醒。</p></div>; }
  return <div className="min-w-0 space-y-3">{OPERATIONAL_RULE_KEYS.map(key => <fieldset disabled={disabled} key={key} className="min-w-0 space-y-3 rounded-xl border border-slate-200 p-3"><legend className="px-1 text-sm font-semibold">{operationalRuleNames[key]}</legend><label className="block text-sm">{operationalRuleNames[key]}处理方式<select aria-label={`${operationalRuleNames[key]}处理方式`} className={input} value={rules[key].mode} onChange={e => onChange({ ...rules, [key]: e.target.value === "value" ? { mode: "value", value: operationalRuleDefault(key) } : { mode: e.target.value as "inherit" | "disabled" } })}><option value="inherit">继承（本层不覆盖）</option><option value="disabled">明确停用</option><option value="value">配置具体值</option></select></label>{fields[key]}</fieldset>)}</div>;
}
