import assert from "node:assert/strict";
import {
  access,
  mkdir,
  mkdtemp,
  readFile,
  realpath,
  rm,
  writeFile,
} from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import test from "node:test";

import {
  ProductionDatabaseMigrationError,
  applyProductionDatabaseMigrations,
  discoverProductionDatabaseMigrations,
  parseProductionMigrationArguments,
  runProductionMigrationCli,
} from "./apply-production-database-migrations.mjs";

const VERSIONS = [
  "202607250001",
  "202607250002",
  "202607310001",
];
const VERSION_NAMES = new Map([
  [VERSIONS[0], "core_transaction_foundation"],
  [VERSIONS[1], "order_shadow_write_rpc"],
  [VERSIONS[2], "merchant_enterprise_foundation"],
]);

function migrationSource(version, name) {
  return `begin;
create table if not exists public.fixture_${version} (
  id bigint generated by default as identity primary key
);
insert into public.faolla_schema_migrations (version, name)
values (${version}, '${name}')
on conflict (version) do nothing;
commit;
`;
}

async function createFixture(t, definitions = null) {
  const root = await mkdtemp(
    path.join(os.tmpdir(), "faolla-production-migration-test-"),
  );
  t.after(() => rm(root, { recursive: true, force: true }));
  const directory = path.join(root, "scripts", "supabase-migrations");
  await mkdir(directory, { recursive: true });

  const items =
    definitions ??
    [
      [VERSIONS[2], "merchant_enterprise_foundation"],
      [VERSIONS[0], "core_transaction_foundation"],
      [VERSIONS[1], "order_shadow_write_rpc"],
    ];
  const sources = new Map();
  for (const [version, name] of items) {
    const fileName = `${version}_${name}.sql`;
    const source = migrationSource(version, name);
    await writeFile(path.join(directory, fileName), source, "utf8");
    sources.set(version, source);
  }
  return { root, directory, sources };
}

function selfHostedTopology(name = "supabase-db") {
  return {
    available: true,
    containerCount: 1,
    databaseCandidates: [
      {
        name,
        image: "supabase/postgres:15",
        probeSucceeded: true,
        tools: {
          psql: true,
          databaseConfigured: true,
          userConfigured: true,
        },
        mounts: [],
      },
    ],
    storageCandidates: [],
    error: null,
  };
}

function createRegistryCommandRunner(input = {}) {
  const applied = new Set(input.applied ?? []);
  const registeredNames = new Map(
    [...applied].map((version) => [
      version,
      VERSION_NAMES.get(version) ?? "unknown_migration",
    ]),
  );
  for (const [version, name] of Object.entries(
    input.registeredNames ?? {},
  )) {
    registeredNames.set(version, name);
  }
  let registryExists = input.registryExists ?? applied.size > 0;
  const calls = [];
  const runner = async (command, args, options = {}) => {
    calls.push({ command, args, options });
    assert.equal(command, "docker");
    assert.deepEqual(args.slice(0, 3), ["exec", "-i", "supabase-db"]);
    assert.equal(typeof options.input, "string");

    if (options.input.includes("__FAOLLA_REGISTRY__")) {
      const versions = [...applied].sort();
      return {
        status: 0,
        stdout: [
          `__FAOLLA_REGISTRY__ ${registryExists ? "true" : "false"}`,
          ...versions.map((version) =>
            JSON.stringify({
              version,
              name: registeredNames.get(version),
            }),
          ),
          "",
        ].join("\n"),
        stderr: "",
        timedOut: false,
      };
    }

    const registration = options.input.match(
      /values\s*\(\s*(\d{12})\s*,\s*'([a-z0-9_]+)'/i,
    );
    const version = registration?.[1];
    assert.match(version ?? "", /^\d{12}$/);
    if (version === input.failVersion) {
      return {
        status: 1,
        stdout: "",
        stderr: input.failureStderr ?? "simulated psql failure",
        stderrTruncated: input.failureStderrTruncated ?? false,
        timedOut: false,
      };
    }
    applied.add(version);
    registeredNames.set(version, registration[2]);
    registryExists = true;
    return {
      status: 0,
      stdout: "",
      stderr: "",
      timedOut: false,
    };
  };
  return { applied, calls, runner };
}

async function exists(filePath) {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

function assertMigrationError(error, code) {
  assert.equal(error instanceof ProductionDatabaseMigrationError, true);
  assert.equal(error.code, code);
  return true;
}

test("CLI arguments default to a read-only dry run and require explicit --apply", () => {
  assert.deepEqual(parseProductionMigrationArguments([]), {
    apply: false,
    dryRun: true,
    explicitDryRun: false,
    json: false,
    through: null,
  });
  assert.deepEqual(
    parseProductionMigrationArguments([
      "--apply",
      "--through=202607310001",
      "--json",
    ]),
    {
      apply: true,
      dryRun: false,
      explicitDryRun: false,
      json: true,
      through: "202607310001",
    },
  );
  assert.deepEqual(
    parseProductionMigrationArguments([
      "--dry-run",
      "--through",
      "202607250002",
    ]),
    {
      apply: false,
      dryRun: true,
      explicitDryRun: true,
      json: false,
      through: "202607250002",
    },
  );
  assert.throws(
    () => parseProductionMigrationArguments(["--apply", "--dry-run"]),
    (error) =>
      assertMigrationError(error, "migration_apply_and_dry_run_conflict"),
  );
  assert.throws(
    () => parseProductionMigrationArguments(["--through=not-a-version"]),
    (error) => assertMigrationError(error, "migration_through_invalid"),
  );
  assert.throws(
    () => parseProductionMigrationArguments(["--unexpected"]),
    (error) => assertMigrationError(error, "migration_argument_unknown"),
  );
});

test("migration discovery validates, sorts, and stops at an exact --through version", async (t) => {
  const fixture = await createFixture(t);
  const discovery = await discoverProductionDatabaseMigrations({
    rootDir: fixture.root,
    through: VERSIONS[1],
  });

  assert.deepEqual(
    discovery.migrations.map((migration) => migration.version),
    VERSIONS,
  );
  assert.deepEqual(
    discovery.selected.map((migration) => migration.version),
    VERSIONS.slice(0, 2),
  );
  assert.equal(discovery.through, VERSIONS[1]);
  assert.equal(discovery.directory, await realDirectory(fixture.directory));

  await assert.rejects(
    discoverProductionDatabaseMigrations({
      rootDir: fixture.root,
      through: "202607300999",
    }),
    (error) => assertMigrationError(error, "migration_through_not_found"),
  );
});

async function realDirectory(directory) {
  return realpath(directory);
}

test("migration discovery fails closed for malformed SQL filenames and psql meta commands", async (t) => {
  const malformed = await createFixture(t);
  await writeFile(
    path.join(malformed.directory, "202607310002_Bad_Name.SQL"),
    migrationSource("202607310002", "bad_name"),
    "utf8",
  );
  await assert.rejects(
    discoverProductionDatabaseMigrations({ rootDir: malformed.root }),
    (error) => assertMigrationError(error, "migration_filename_invalid"),
  );

  const metaCommand = await createFixture(t, [
    ["202607310002", "meta_command"],
  ]);
  const filePath = path.join(
    metaCommand.directory,
    "202607310002_meta_command.sql",
  );
  await writeFile(
    filePath,
    migrationSource("202607310002", "meta_command").replace(
      "create table",
      "\\echo forbidden\ncreate table",
    ),
    "utf8",
  );
  await assert.rejects(
    discoverProductionDatabaseMigrations({ rootDir: metaCommand.root }),
    (error) =>
      assertMigrationError(error, "migration_psql_meta_command_forbidden"),
  );
});

test("default execution is dry-run, treats a missing registry as empty, and never sends a migration", async (t) => {
  const fixture = await createFixture(t);
  const lockPath = path.join(fixture.root, "migration.lock");
  const secret = "container-password-must-never-leak";
  const commands = createRegistryCommandRunner({
    registryExists: false,
  });

  const report = await applyProductionDatabaseMigrations({
    rootDir: fixture.root,
    through: VERSIONS[2],
    env: {
      POSTGRES_PASSWORD: secret,
    },
    selfHostedTopology: selfHostedTopology(),
    runCommand: commands.runner,
    lockPath,
  });

  assert.equal(report.status, "dry_run");
  assert.equal(report.mode, "dry_run");
  assert.equal(report.registryExists, false);
  assert.deepEqual(
    report.pending.map((migration) => migration.version),
    VERSIONS,
  );
  assert.deepEqual(report.executed, []);
  assert.equal(commands.calls.length, 1);
  assert.match(commands.calls[0].options.input, /json_build_object/);
  assert.match(commands.calls[0].options.input, /'name', name/);
  assert.equal(await exists(lockPath), false);

  const serializedCommands = JSON.stringify(commands.calls);
  assert.equal(serializedCommands.includes(secret), false);
  const shellScript = commands.calls[0].args.at(-1);
  assert.match(shellScript, /POSTGRES_PASSWORD/);
  assert.match(shellScript, /PGPASSWORD/);
  assert.match(shellScript, /supabase_admin/);
  assert.match(shellScript, /POSTGRES_DB/);
  assert.match(shellScript, /ON_ERROR_STOP=1/);
  assert.match(
    shellScript,
    /PGOPTIONS='-c lock_timeout=5s -c statement_timeout=900s'/,
  );
  assert.equal(JSON.stringify(report).includes(secret), false);
});

test("apply mode executes only unregistered migrations in filename order through stdin", async (t) => {
  const fixture = await createFixture(t);
  const commands = createRegistryCommandRunner({
    applied: [VERSIONS[0]],
    registryExists: true,
  });

  const report = await applyProductionDatabaseMigrations({
    apply: true,
    rootDir: fixture.root,
    through: VERSIONS[2],
    selfHostedTopology: selfHostedTopology(),
    runCommand: commands.runner,
    lockPath: path.join(fixture.root, "migration.lock"),
  });

  assert.equal(report.status, "applied");
  assert.deepEqual(
    report.pending.map((migration) => migration.version),
    VERSIONS.slice(1),
  );
  assert.deepEqual(
    report.executed.map((migration) => migration.version),
    VERSIONS.slice(1),
  );
  assert.deepEqual([...commands.applied].sort(), VERSIONS);

  const migrationCalls = commands.calls.filter(
    (call) => !call.options.input.includes("__FAOLLA_REGISTRY__"),
  );
  assert.deepEqual(
    migrationCalls.map(
      (call) =>
        call.options.input.match(/values\s*\(\s*(\d{12})\s*,/i)?.[1],
    ),
    VERSIONS.slice(1),
  );
  for (const [index, call] of migrationCalls.entries()) {
    const source = fixture.sources.get(VERSIONS[index + 1]);
    const lockIndex = call.options.input.indexOf(
      "SELECT pg_advisory_lock(20260731, 1);",
    );
    const sourceIndex = call.options.input.indexOf(source.trimEnd());
    const unlockIndex = call.options.input.indexOf(
      "SELECT pg_advisory_unlock(20260731, 1);",
    );
    assert.equal(lockIndex >= 0, true);
    assert.equal(sourceIndex > lockIndex, true);
    assert.equal(unlockIndex > sourceIndex, true);
  }
  assert.equal(
    migrationCalls.every(
      (call) =>
        !call.args.some((argument) =>
          argument.includes(call.options.input.slice(0, 20)),
        ),
    ),
    true,
  );
});

test("registered versions must be a known continuous prefix of local migrations", async (t) => {
  const fixture = await createFixture(t);
  const unknown = createRegistryCommandRunner({
    applied: ["202607310099"],
    registryExists: true,
  });
  await assert.rejects(
    applyProductionDatabaseMigrations({
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: unknown.runner,
      lockPath: path.join(fixture.root, "unknown.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_registry_version_unknown"),
  );

  const gap = createRegistryCommandRunner({
    applied: [VERSIONS[0], VERSIONS[2]],
    registryExists: true,
  });
  await assert.rejects(
    applyProductionDatabaseMigrations({
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: gap.runner,
      lockPath: path.join(fixture.root, "gap.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_registry_not_contiguous"),
  );
});

test("registered migration names must be present and match local filename suffixes", async (t) => {
  const fixture = await createFixture(t);
  const mismatch = createRegistryCommandRunner({
    applied: [VERSIONS[0]],
    registryExists: true,
    registeredNames: {
      [VERSIONS[0]]: "wrong_foundation",
    },
  });
  await assert.rejects(
    applyProductionDatabaseMigrations({
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: mismatch.runner,
      lockPath: path.join(fixture.root, "name-mismatch.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_registry_name_mismatch"),
  );

  const missing = createRegistryCommandRunner({
    applied: [VERSIONS[0]],
    registryExists: true,
    registeredNames: {
      [VERSIONS[0]]: null,
    },
  });
  await assert.rejects(
    applyProductionDatabaseMigrations({
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: missing.runner,
      lockPath: path.join(fixture.root, "name-missing.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_registry_name_missing"),
  );
});

test("apply mode verifies every migration registration and fails closed", async (t) => {
  const fixture = await createFixture(t, [
    [VERSIONS[0], "core_transaction_foundation"],
  ]);
  let queryCount = 0;
  const runner = async (command, args, options) => {
    assert.equal(command, "docker");
    if (options.input.includes("__FAOLLA_REGISTRY__")) {
      queryCount += 1;
      return {
        status: 0,
        stdout: "__FAOLLA_REGISTRY__ false\n",
        stderr: "",
        timedOut: false,
      };
    }
    return { status: 0, stdout: "", stderr: "", timedOut: false };
  };

  await assert.rejects(
    applyProductionDatabaseMigrations({
      apply: true,
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: runner,
      lockPath: path.join(fixture.root, "migration.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_registration_missing"),
  );
  assert.equal(queryCount, 2);
});

test("psql failure is non-success, does not expose stderr, and releases the mutex", async (t) => {
  const fixture = await createFixture(t, [
    ["202608190040", "merchant_acl_contract_hardening"],
  ]);
  const lockPath = path.join(fixture.root, "migration.lock");
  const secret = "password-printed-by-a-broken-command";
  const failureStderr =
    "psql: ERROR: P0001: " +
    "merchant_acl_contract_hardening_prerequisite_missing\n" +
    `DETAIL: ${secret}\n`;
  const failing = createRegistryCommandRunner({
    registryExists: false,
    failVersion: "202608190040",
    failureStderr,
  });

  let caught;
  try {
    await applyProductionDatabaseMigrations({
      apply: true,
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: failing.runner,
      lockPath,
    });
  } catch (error) {
    caught = error;
  }
  assertMigrationError(caught, "migration_apply_failed");
  assert.equal(JSON.stringify(caught).includes(secret), false);
  assert.deepEqual(caught.details.diagnostic, {
    schemaVersion: 1,
    phase: "migration_apply",
    fileName: "202608190040_merchant_acl_contract_hardening.sql",
    status: 1,
    timedOut: false,
    sqlState: "P0001",
    databaseErrorCode: "merchant_acl_contract_hardening_prerequisite_missing",
  });
  assert.equal(await exists(lockPath), false);

  const healthy = createRegistryCommandRunner({ registryExists: false });
  const report = await applyProductionDatabaseMigrations({
    rootDir: fixture.root,
    selfHostedTopology: selfHostedTopology(),
    runCommand: healthy.runner,
    lockPath,
  });
  assert.equal(report.status, "dry_run");
});

test("database error classification is bound to the exact 040 ERROR header", async (t) => {
  const cases = [
    {
      label: "allowlisted marker only in DETAIL",
      stderr:
        "psql: ERROR: P0001: unrelated_database_failure\n" +
        "DETAIL: merchant_acl_contract_hardening_prerequisite_missing\n",
      sqlState: "P0001",
      databaseErrorCode: null,
    },
    {
      label: "a truncated stderr tail cannot establish a unique header",
      stderr:
        "psql: ERROR: P0001: " +
        "merchant_acl_contract_hardening_prerequisite_missing\n",
      stderrTruncated: true,
      sqlState: null,
      databaseErrorCode: null,
    },
    {
      label: "DETAIL cannot masquerade as an ERROR header",
      stderr:
        "psql: ERROR: P0001: unrelated failure with spaces\n" +
        "DETAIL: ERROR: P0001: " +
        "merchant_acl_contract_hardening_prerequisite_missing\n",
      sqlState: "P0001",
      databaseErrorCode: null,
    },
    {
      label: "allowlisted marker with a different SQLSTATE",
      stderr:
        "psql: ERROR: XX000: " +
        "merchant_acl_contract_hardening_prerequisite_missing\n",
      sqlState: "XX000",
      databaseErrorCode: null,
    },
    {
      label: "ambiguous ERROR headers",
      stderr:
        "psql: ERROR: P0001: " +
        "merchant_acl_contract_hardening_prerequisite_missing\n" +
        "psql: ERROR: P0001: " +
        "merchant_acl_contract_hardening_prerequisite_missing\n",
      sqlState: null,
      databaseErrorCode: null,
    },
  ];

  for (const item of cases) {
    await t.test(item.label, async (subtest) => {
      const fixture = await createFixture(subtest, [
        ["202608190040", "merchant_acl_contract_hardening"],
      ]);
      const failing = createRegistryCommandRunner({
        registryExists: false,
        failVersion: "202608190040",
        failureStderr: item.stderr,
        failureStderrTruncated: item.stderrTruncated,
      });
      let caught;
      try {
        await applyProductionDatabaseMigrations({
          apply: true,
          rootDir: fixture.root,
          selfHostedTopology: selfHostedTopology(),
          runCommand: failing.runner,
          lockPath: path.join(fixture.root, "migration.lock"),
        });
      } catch (error) {
        caught = error;
      }
      assertMigrationError(caught, "migration_apply_failed");
      assert.equal(caught.details.diagnostic.sqlState, item.sqlState);
      assert.equal(
        caught.details.diagnostic.databaseErrorCode,
        item.databaseErrorCode,
      );
    });
  }

  const otherMigration = await createFixture(t, [
    ["202608190041", "other_migration"],
  ]);
  const otherFailure = createRegistryCommandRunner({
    registryExists: false,
    failVersion: "202608190041",
    failureStderr:
      "psql: ERROR: P0001: " +
      "merchant_acl_contract_hardening_prerequisite_missing\n",
  });
  let otherCaught;
  try {
    await applyProductionDatabaseMigrations({
      apply: true,
      rootDir: otherMigration.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: otherFailure.runner,
      lockPath: path.join(otherMigration.root, "migration.lock"),
    });
  } catch (error) {
    otherCaught = error;
  }
  assertMigrationError(otherCaught, "migration_apply_failed");
  assert.equal(otherCaught.details.diagnostic.sqlState, "P0001");
  assert.equal(otherCaught.details.diagnostic.databaseErrorCode, null);
});

test("an existing migration lock prevents concurrent database access", async (t) => {
  const fixture = await createFixture(t, [
    [VERSIONS[0], "core_transaction_foundation"],
  ]);
  const lockPath = path.join(fixture.root, "migration.lock");
  await writeFile(lockPath, "held by another process\n", "utf8");
  let commandCalls = 0;

  await assert.rejects(
    applyProductionDatabaseMigrations({
      apply: true,
      rootDir: fixture.root,
      selfHostedTopology: selfHostedTopology(),
      runCommand: async () => {
        commandCalls += 1;
        return { status: 0, stdout: "", stderr: "", timedOut: false };
      },
      lockPath,
    }),
    (error) => assertMigrationError(error, "migration_already_running"),
  );
  assert.equal(commandCalls, 0);
  assert.equal(await readFile(lockPath, "utf8"), "held by another process\n");
});

test("ambiguous self-hosted database topology fails closed", async (t) => {
  const fixture = await createFixture(t, [
    [VERSIONS[0], "core_transaction_foundation"],
  ]);
  const topology = selfHostedTopology();
  topology.databaseCandidates.push({
    ...topology.databaseCandidates[0],
    name: "supabase-db-restore",
  });

  await assert.rejects(
    applyProductionDatabaseMigrations({
      rootDir: fixture.root,
      selfHostedTopology: topology,
      runCommand: async () => {
        throw new Error("must not run");
      },
      lockPath: path.join(fixture.root, "migration.lock"),
    }),
    (error) =>
      assertMigrationError(error, "migration_database_container_ambiguous"),
  );
});

test("CLI returns nonzero structured errors and preserves default dry-run mode", async () => {
  let received;
  let stdout = "";
  const successCode = await runProductionMigrationCli({
    argv: ["--through=202607310001", "--json"],
    execute: async (options) => {
      received = options;
      return {
        schemaVersion: 1,
        status: "dry_run",
        mode: "dry_run",
        databaseContainer: "supabase-db",
        selected: [],
        pending: [],
        executed: [],
        effectiveThrough: "202607310001",
      };
    },
    writeStdout: (value) => {
      stdout += value;
    },
  });
  assert.equal(successCode, 0);
  assert.equal(received.apply, false);
  assert.equal(received.dryRun, true);
  assert.equal(JSON.parse(stdout).ok, true);

  let stderr = "";
  const failureCode = await runProductionMigrationCli({
    argv: ["--apply", "--through=202607310001", "--json"],
    execute: async () => {
      throw new ProductionDatabaseMigrationError("migration_apply_failed");
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.equal(failureCode, 1);
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "migration_apply_failed",
  });
});

test("CLI emits only an exact bounded database failure diagnostic", async () => {
  const diagnostic = {
    schemaVersion: 1,
    phase: "migration_apply",
    fileName: "202608190040_merchant_acl_contract_hardening.sql",
    status: 1,
    timedOut: false,
    sqlState: "P0001",
    databaseErrorCode: "merchant_acl_contract_hardening_prerequisite_missing",
  };
  let stderr = "";
  const code = await runProductionMigrationCli({
    argv: ["--apply", "--through=202608190040", "--json"],
    execute: async () => {
      throw new ProductionDatabaseMigrationError("migration_apply_failed", {
        diagnostic,
        rawStderr: "must-not-appear",
      });
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.equal(code, 1);
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "migration_apply_failed",
    diagnostic,
  });
  assert.equal(stderr.includes("must-not-appear"), false);

  stderr = "";
  await runProductionMigrationCli({
    argv: ["--apply", "--through=202608190040", "--json"],
    execute: async () => {
      throw new ProductionDatabaseMigrationError("migration_apply_failed", {
        diagnostic: { ...diagnostic, leaked: "must-not-appear" },
      });
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "migration_apply_failed",
  });

  for (const invalidDiagnostic of [
    { ...diagnostic, phase: "registry_query" },
    { ...diagnostic, fileName: "202608190041_other_migration.sql" },
    { ...diagnostic, sqlState: "XX000" },
    { ...diagnostic, status: 0 },
    { ...diagnostic, status: null },
    { ...diagnostic, timedOut: true },
    {
      ...diagnostic,
      databaseErrorCode: null,
      fileName: `202608190040_${"a".repeat(256)}.sql`,
    },
  ]) {
    stderr = "";
    await runProductionMigrationCli({
      argv: ["--apply", "--through=202608190040", "--json"],
      execute: async () => {
        throw new ProductionDatabaseMigrationError(
          "migration_apply_failed",
          { diagnostic: invalidDiagnostic },
        );
      },
      writeStderr: (value) => {
        stderr += value;
      },
    });
    assert.deepEqual(JSON.parse(stderr), {
      ok: false,
      error: "migration_apply_failed",
    });
  }

  stderr = "";
  await runProductionMigrationCli({
    argv: ["--apply", "--through=202608190040", "--json"],
    execute: async () => {
      throw new ProductionDatabaseMigrationError("migration_lock_failed", {
        diagnostic,
      });
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "migration_lock_failed",
  });

  const secret = "diagnostic-secret-must-not-appear";
  const nonEnumerableToJson = { ...diagnostic };
  Object.defineProperty(nonEnumerableToJson, "toJSON", {
    value: () => ({ secret }),
  });
  const inheritedToJson = Object.assign(
    Object.create({ toJSON: () => ({ secret }) }),
    diagnostic,
  );
  for (const hostileDiagnostic of [nonEnumerableToJson, inheritedToJson]) {
    stderr = "";
    await runProductionMigrationCli({
      argv: ["--apply", "--through=202608190040", "--json"],
      execute: async () => {
        throw new ProductionDatabaseMigrationError(
          "migration_apply_failed",
          { diagnostic: hostileDiagnostic },
        );
      },
      writeStderr: (value) => {
        stderr += value;
      },
    });
    assert.deepEqual(JSON.parse(stderr), {
      ok: false,
      error: "migration_apply_failed",
    });
    assert.equal(stderr.includes(secret), false);
  }

  stderr = "";
  await runProductionMigrationCli({
    argv: ["--apply", "--through=202608190040", "--json"],
    execute: async () => {
      const error = new ProductionDatabaseMigrationError(
        "migration_apply_failed",
      );
      Object.defineProperty(error.details, "diagnostic", {
        get() {
          throw new Error(secret);
        },
      });
      throw error;
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "migration_apply_failed",
  });
  assert.equal(stderr.includes(secret), false);

  stderr = "";
  await runProductionMigrationCli({
    argv: ["--apply", "--through=202608190040", "--json"],
    execute: async () => {
      const error = new ProductionDatabaseMigrationError(
        "migration_apply_failed",
      );
      error.code = { toJSON: () => secret };
      throw error;
    },
    writeStderr: (value) => {
      stderr += value;
    },
  });
  assert.deepEqual(JSON.parse(stderr), {
    ok: false,
    error: "production_database_migration_failed",
  });
  assert.equal(stderr.includes(secret), false);
});
