import assert from "node:assert/strict";
import test from "node:test";
import { captureNftFirewall, validateNftFirewall, planNftFirewall, installNftFirewall, checkNftFirewall, verifyNftFirewall, restoreNftFirewall } from "./production-maintenance-nft.mjs";

// Pure synthetic command bridge. These tests do not execute nft or certify a
// kernel datapath; the separate Linux network-namespace acceptance does that.
const ROLES = ["kong", "db", "rest", "auth", "realtime", "storage", "meta", "studio", "functions", "analytics", "vector", "imgproxy", "supavisor"];
const input = { operationId: "11111111-2222-4333-8444-555555555555", appPort: 3000 };
const docker = { bridge: "faolla_br0", containers: ROLES.map((service, i) => ({ service, address: `172.30.0.${i + 2}`,
  publishedPorts: service === "kong" ? [8000, 8443] : service === "supavisor" ? [5432, 6543] : [] })) };
const match = (left, right, op = "==") => ({ match: { op, left, right } });
const meta = (key) => ({ meta: { key } });
const payload = (protocol, field) => ({ payload: { protocol, field } });
const save = (tool, count = 7, date = "Mon Sep  1 00:00:00 2026") => `# Generated by ${tool} v1.8.4 (nf_tables) on ${date}\n*filter\n:INPUT ACCEPT [${count}:${count}]\n:FORWARD ACCEPT [${count}:${count}]\n:OUTPUT ACCEPT [0:0]\n[${count}:${count}] -A INPUT -m comment --comment "do not strip -c 12 13 here" -j ACCEPT\nCOMMIT\n# Completed on ${date}\n`;
function base() {
  return { nftables: [
    { metainfo: { version: "0.9.3", release_name: "Topsy", json_schema_version: 1 } },
    { table: { family: "ip", name: "filter", handle: 1 } },
    { chain: { family: "ip", table: "filter", name: "INPUT", handle: 1, type: "filter", hook: "input", prio: 0, policy: "accept" } },
    { rule: { family: "ip", table: "filter", chain: "INPUT", handle: 2, expr: [{ counter: { packets: 10, bytes: 500 } }, { xt: null }, { accept: null }] } },
    { table: { family: "inet", name: "firewalld", handle: 2 } },
    { chain: { family: "inet", table: "firewalld", name: "filter_FORWARD", handle: 1, type: "filter", hook: "forward", prio: 10, policy: "accept" } },
    { rule: { family: "inet", table: "firewalld", chain: "filter_FORWARD", handle: 2,
      expr: [match({ ct: { key: "state" } }, { set: ["established", "related"] }, "in"), { accept: null }] } },
    { table: { family: "bridge", name: "filter", handle: 3 } },
    { chain: { family: "bridge", table: "filter", name: "FORWARD", handle: 1, type: "filter", hook: "forward", prio: -200, policy: "accept" } },
  ] };
}
function installedRows(plan) {
  let handle = 1;
  const rows = [{ table: { family: "inet", name: plan.tableName, handle: handle++ } }];
  const address = (role) => plan.containers.find((row) => row.service === role).address;
  const add = (chain, expr) => rows.push({ rule: { family: "inet", table: plan.tableName, chain, handle: handle++, expr } });
  rows.push({ chain: { family: "inet", table: plan.tableName, name: "input", handle: handle++, type: "filter", hook: "input", prio: 200, policy: "accept" } });
  for (const n of plan.inputPorts) add("input", [match(meta("iifname"), "lo", "!="), match(meta("l4proto"), "tcp"), match(payload("tcp", "dport"), n), { drop: null }]);
  rows.push({ chain: { family: "inet", table: plan.tableName, name: "forward", handle: handle++, type: "filter", hook: "forward", prio: 200, policy: "accept" } });
  for (const [from, to] of [["kong", "rest"], ["kong", "auth"], ["rest", "db"], ["auth", "db"]]) {
    const ports = [match(meta("iifname"), plan.bridge), match(meta("oifname"), plan.bridge)];
    add("forward", [...ports, match(payload("ip", "saddr"), address(from)), match(payload("ip", "daddr"), address(to)), { accept: null }]);
    add("forward", [...ports, match(payload("ip", "saddr"), address(to)), match(payload("ip", "daddr"), address(from)),
      match({ ct: { key: "state" } }, "established", "in"), match({ ct: { key: "direction" } }, "reply"), { accept: null }]);
  }
  for (const row of plan.containers) add("forward", [match(payload("ip", "daddr"), row.address), { drop: null }]);
  return rows;
}
function fixture() {
  const plan = planNftFirewall({ input, docker });
  const state = { nft: base(), saves: { "iptables-save": save("iptables-save"), "ip6tables-save": save("ip6tables-save"), "ebtables-save": save("ebtables-save") },
    mutations: [], calls: [], bridge: "1", beforeWrite: null, afterWrite: null, throwWrite: false, suppressWrite: false, versions: {} };
  const d = { readText(path) { assert.match(path, /^\/proc\/sys\/net\/bridge\/bridge-nf-call-ip(?:6)?tables$/); return state.bridge; },
    run(command, args, options) {
      state.calls.push({ command, args, options });
      if (args.join(" ") === "--version") return { stdout: state.versions[command] ?? (command === "nft" ? "nftables v0.9.3 (Topsy)" : `${command} v1.8.4 (nf_tables)`), stderr: "" };
      if (command === "nft" && args.join(" ") === "-j -a -n list ruleset") return { stdout: JSON.stringify(state.nft), stderr: "" };
      if (Object.hasOwn(state.saves, command)) { assert.deepEqual(args, command === "ebtables-save" ? [] : ["-c"]); return { stdout: state.saves[command], stderr: "" }; }
      assert.equal(command, "nft"); assert.deepEqual(args, ["-f", "-"]); assert.deepEqual(Object.keys(options), ["input"]);
      state.beforeWrite?.(); state.mutations.push(options.input);
      if (!state.suppressWrite) {
        if (options.input === plan.script) state.nft.nftables.push(...installedRows(plan));
        else {
          assert.equal(options.input, `delete table inet ${plan.tableName}\n`);
          state.nft.nftables = state.nft.nftables.filter((entry) => {
            const item = entry.table || entry.chain || entry.rule;
            return !item || item.family !== "inet" || (entry.table ? item.name : item.table) !== plan.tableName;
          });
        }
      }
      state.afterWrite?.();
      if (state.throwWrite) throw new Error("synthetic-private-command-error");
      return { stdout: "", stderr: "" };
    } };
  return { state, plan, d, frozen: captureNftFirewall(d) };
}

test("strictly retains the real firewalld FIB reverse-path expression", () => {
  const { state, d } = fixture();
  const expression = match({ fib: { result: "oif", flags: ["saddr", "iif"] } }, false);
  state.nft.nftables[3].rule.expr.unshift(expression);
  const frozen = captureNftFirewall(d);
  assert.deepEqual(frozen.baseline.nftables[3].rule.expr[0], expression);
  for (const fib of [
    { result: "route-update", flags: ["saddr"] },
    { result: "oif", flags: ["saddr", "saddr"] },
    { result: "oif", flags: ["saddr", "daddr"] },
    { result: "oif", flags: ["saddr", "oif"] },
    { result: "type", flags: ["saddr", "iif", "oif"] },
    { result: "oif", flags: ["saddr", "unknown"] },
    { result: "oif", flags: ["iif"] },
    { result: "oif", flags: ["saddr"], ignored: true },
  ]) {
    state.nft.nftables[3].rule.expr[0] = match({ fib }, false);
    assert.throws(() => captureNftFirewall(d), /production_maintenance_nft_/);
  }
  state.nft.nftables[3].rule.expr[0] = match({ fib: { result: "oif", flags: ["daddr", "iif"] } }, false);
  assert.throws(() => checkNftFirewall(frozen, planNftFirewall({ input, docker }), d), /baseline_changed/);
  assert.equal(state.mutations.length, 0);
});

test("real ebtables-save table completion without COMMIT is bridge-only and still complete", () => {
  const { state, d } = fixture();
  const bridge = save("ebtables-save").replace("COMMIT\n", "") + save("ebtables-save").replace("*filter", "*nat").replace("COMMIT\n", "");
  state.saves["ebtables-save"] = bridge;
  const frozen = captureNftFirewall(d);
  assert.equal(frozen.legacyBridge.includes("COMMIT"), false);
  assert.deepEqual(validateNftFirewall(frozen), frozen);
  state.saves["ebtables-save"] = bridge.replace(/# Completed[^\n]*\n$/, "");
  assert.throws(() => captureNftFirewall(d), /production_maintenance_nft_/);
  state.saves["ebtables-save"] = bridge;
  state.saves["iptables-save"] = save("iptables-save").replace("COMMIT\n", "");
  assert.throws(() => captureNftFirewall(d), /production_maintenance_nft_/);
  assert.equal(state.mutations.length, 0);
});

test("captures nf_tables plus all three full compatibility saves without a write", () => {
  const { frozen, state } = fixture();
  assert.equal(frozen.backend, "nft"); assert.equal(state.mutations.length, 0);
  assert.equal(frozen.baseline.nftables[3].rule.expr[0].counter.packets, 0);
  assert.match(frozen.legacy4, /--comment "do not strip -c 12 13 here"/);
  assert.doesNotMatch(frozen.legacy4, /Mon Sep|\[7:7\]/);
  assert.deepEqual(validateNftFirewall(frozen), frozen);
});
test("fixed additive plan only targets owned ports, thirteen destinations and four directional pairs", () => {
  const { plan } = fixture();
  assert.deepEqual(plan.inputPorts, [3000, 5432, 6543, 8000, 8443]);
  assert.match(plan.script, /^create table inet FAOM_[a-f0-9]{16}\n/);
  assert.equal((plan.script.match(/priority 200/g) || []).length, 2);
  assert.equal((plan.script.match(/ct state established ct direction reply accept/g) || []).length, 4);
  assert.equal((plan.script.match(/add rule inet \S+ forward ip daddr \S+ drop/g) || []).length, 13);
  assert.doesNotMatch(plan.script, /flush|policy drop|DOCKER-USER|output|related|ct state established accept/);
});
test("one create batch exact readback and own-table-only restore preserve original baseline", () => {
  const { frozen, plan, d, state } = fixture(), original = structuredClone(state.nft);
  assert.deepEqual(checkNftFirewall(frozen, plan, d), { installed: false });
  assert.equal(state.mutations.length, 0);
  assert.deepEqual(installNftFirewall(frozen, plan, d), { verified: true });
  assert.deepEqual(checkNftFirewall(frozen, plan, d), { installed: true });
  assert.deepEqual(verifyNftFirewall(frozen, plan, d), { verified: true });
  assert.equal(state.mutations.length, 1);
  assert.deepEqual(installNftFirewall(frozen, plan, d), { verified: true });
  assert.equal(state.mutations.length, 1, "existing exact table is only observed, never replayed");
  assert.deepEqual(restoreNftFirewall(frozen, plan, d), { restored: true });
  assert.deepEqual(state.mutations, [plan.script, `delete table inet ${plan.tableName}\n`]);
  assert.deepEqual(state.nft, original);
});
test("counter/header time movement does not alter baseline while quoted counter-like content does", () => {
  const { frozen, plan, d, state } = fixture();
  state.nft.nftables[3].rule.expr[0].counter = { packets: 1e20, bytes: 2e20 };
  for (const key of Object.keys(state.saves)) state.saves[key] = save(key, 99, "Tue Sep  2 01:00:00 2026");
  installNftFirewall(frozen, plan, d);
  state.saves["iptables-save"] = state.saves["iptables-save"].replace("strip -c 12 13", "strip -c 22 23");
  assert.throws(() => verifyNftFirewall(frozen, plan, d));
});
test("opaque xt requires stable full save content even when nft JSON is identical", () => {
  for (const tool of ["iptables-save", "ip6tables-save", "ebtables-save"]) {
    const { frozen, plan, d, state } = fixture();
    state.saves[tool] = state.saves[tool].replace("-j ACCEPT", "-j DROP");
    assert.throws(() => checkNftFirewall(frozen, plan, d));
    assert.throws(() => installNftFirewall(frozen, plan, d)); assert.equal(state.mutations.length, 0);
  }
});
test("unknown/offload objects, statements, nested expressions and unsafe xt reject", () => {
  for (const change of [
    (s) => s.nft.nftables.push({ flowtable: { family: "inet", table: "firewalld", name: "f" } }),
    (s) => s.nft.nftables.push({ set: { family: "inet", table: "firewalld", name: "dynamic" } }),
    (s) => s.nft.nftables[3].rule.expr.push({ flow: { op: "add", flowtable: "f" } }),
    (s) => s.nft.nftables[3].rule.expr.push({ queue: { num: 0 } }),
    (s) => s.nft.nftables[3].rule.expr.push({ mangle: { key: payload("ip", "daddr"), value: "172.30.0.3" } }),
    (s) => s.nft.nftables[3].rule.expr.push(match({ unknown: { key: "danger" } }, 1)),
    (s) => s.nft.nftables[3].rule.expr[1] = { xt: { type: "target", name: "FLOWOFFLOAD" } },
    (s) => s.saves["iptables-save"] = s.saves["iptables-save"].replace("-j ACCEPT", "-j TEE"),
    (s) => s.saves["ebtables-save"] = s.saves["ebtables-save"].replace("-j ACCEPT", "-m bpf -j ACCEPT"),
  ]) {
    const { d, state } = fixture(); change(state);
    assert.throws(() => captureNftFirewall(d)); assert.equal(state.mutations.length, 0);
  }
});
test("priority collision or later base chain, disabled bridge, backend/tool drift reject", () => {
  for (const change of [
    (s) => s.nft.nftables[5].chain.prio = 200,
    (s) => s.nft.nftables[5].chain.prio = 300,
    (s) => s.bridge = "0",
    (s) => s.versions["iptables"] = "iptables v1.8.4 (legacy)",
    (s) => s.versions["ebtables-save"] = "ebtables-save v1.8.4 (legacy)",
    (s) => s.versions.nft = "nftables v9.0.0 (unknown)",
  ]) { const { d, state } = fixture(); change(state); assert.throws(() => captureNftFirewall(d)); }
});
test("explicit newer CI profile is bound honestly and cannot drift after capture", () => {
  const { d, state, plan } = fixture();
  state.versions.nft = "nftables v1.0.9 (Old Doc Yak)"; state.nft.nftables[0].metainfo.version = "1.0.9";
  for (const tool of ["iptables", "ip6tables", "iptables-save", "ip6tables-save", "ebtables-save"]) state.versions[tool] = `${tool} v1.8.10 (nf_tables)`;
  const frozen = captureNftFirewall(d); assert.equal(frozen.nftVersion, state.versions.nft);
  state.versions.nft = "nftables v1.0.8 (Old Doc Yak)"; state.nft.nftables[0].metainfo.version = "1.0.8";
  assert.throws(() => installNftFirewall(frozen, plan, d));
});

function numericCompactOwnRows(plan) {
  return installedRows(plan).map((entry) => {
    if (!entry.rule) return entry;
    const expr = entry.rule.expr.filter(item => !(entry.rule.chain === "input" && item.match?.left?.meta?.key === "l4proto"));
    for (const item of expr) {
      if (item.match?.left?.ct?.key === "state") item.match.right = 2;
      if (item.match?.left?.ct?.key === "direction") item.match.right = 1;
    }
    return { rule: { ...entry.rule, expr } };
  });
}

test("real nft numeric conntrack and implicit typed TCP readback verify without changing foreign baseline", () => {
  const { state, frozen, plan, d } = fixture();
  const before = structuredClone(frozen);
  state.afterWrite = () => {
    state.nft.nftables = state.nft.nftables.filter(row => (row.table?.name ?? row.chain?.table ?? row.rule?.table) !== plan.tableName);
    state.nft.nftables.push(...numericCompactOwnRows(plan));
  };
  assert.deepEqual(installNftFirewall(frozen, plan, d), { verified: true });
  assert.deepEqual(checkNftFirewall(frozen, plan, d), { installed: true });
  assert.deepEqual(verifyNftFirewall(frozen, plan, d), { verified: true });
  assert.deepEqual(frozen, before);
  state.afterWrite = null;
  assert.deepEqual(restoreNftFirewall(frozen, plan, d), { restored: true });
  assert.equal(state.mutations.length, 2);
});

test("numeric representation never accepts different conntrack state direction type or predicate", () => {
  for (const change of [
    (expr) => { expr[4].match.right = 6; },
    (expr) => { expr[4].match.right = "2"; },
    (expr) => { expr[4].match.op = "=="; },
    (expr) => { expr[4].match.left.ct.unknown = true; },
    (expr) => { expr[5].match.right = 0; },
    (expr) => { expr[5].match.right = "1"; },
    (expr) => { expr[5].match.op = "!="; },
    (expr) => { expr.splice(4, 1); },
    (expr) => { [expr[4], expr[5]] = [expr[5], expr[4]]; },
    (expr) => { expr.push({ accept: null }); },
  ]) {
    const { state, frozen, plan, d } = fixture();
    const own = numericCompactOwnRows(plan), reply = own.find(row => row.rule?.expr.some(item => item.match?.left?.ct?.key === "state"));
    change(reply.rule.expr); state.nft.nftables.push(...own);
    assert.throws(() => checkNftFirewall(frozen, plan, d), /owned_table_changed|nft_unverified/);
    assert.equal(state.mutations.length, 0);
  }
});

test("implicit TCP is exact typed input rule only, never missing DROP or broad raw transport", () => {
  for (const change of [
    (expr) => { expr[1].match.left.payload.protocol = "udp"; },
    (expr) => { expr[1].match.left.payload.protocol = "th"; },
    (expr) => { expr[1].match.left.payload = { base: "th", offset: 16, len: 16 }; },
    (expr) => { expr[1].match.right = 65535; },
    (expr) => { expr[1].match.op = "!="; },
    (expr) => { expr[2] = { accept: null }; },
    (expr) => { expr.pop(); },
    (expr) => { expr[0].match.op = "=="; },
    (expr) => { expr.splice(1, 0, match(meta("l4proto"), "udp")); },
    (expr) => { expr.splice(1, 0, match(meta("l4proto"), 17)); },
  ]) {
    const { state, frozen, plan, d } = fixture();
    const own = numericCompactOwnRows(plan), input = own.find(row => row.rule?.chain === "input");
    change(input.rule.expr); state.nft.nftables.push(...own);
    assert.throws(() => checkNftFirewall(frozen, plan, d), /owned_table_changed/);
    assert.equal(state.mutations.length, 0);
  }
});

test("equivalent spelling changes in an existing third-party rule still invalidate its frozen baseline", () => {
  const { state, plan, d } = fixture();
  state.nft.nftables[3].rule.expr = [match({ ct: { key: "state" } }, "established", "in"), { accept: null }];
  const frozen = captureNftFirewall(d);
  state.nft.nftables[3].rule.expr[0].match.right = 2;
  assert.throws(() => checkNftFirewall(frozen, plan, d), /baseline_changed/);
  assert.equal(state.mutations.length, 0);
});
test("suppressed mutation and unknown ACK fail without automatic replay", () => {
  for (const kind of ["suppressWrite", "throwWrite"]) {
    const { frozen, plan, d, state } = fixture(); state[kind] = true;
    assert.throws(() => installNftFirewall(frozen, plan, d)); assert.equal(state.mutations.length, 1);
  }
});
test("post-write unrelated change is detected without restoring or flushing others", () => {
  const { frozen, plan, d, state } = fixture();
  state.afterWrite = () => { state.nft.nftables[2].chain.policy = "drop"; };
  assert.throws(() => installNftFirewall(frozen, plan, d));
  assert.deepEqual(state.mutations, [plan.script]);
});
test("foreign or incomplete same-name table never gets adopted, appended to, or deleted", () => {
  for (const change of [
    (rows) => rows.slice(0, 1),
    (rows) => { rows[1].chain.policy = "drop"; return rows; },
    (rows) => { rows.find((row) => row.rule?.chain === "input").rule.expr.at(-1).drop = "not-null"; return rows; },
    (rows) => { rows.find((row) => row.rule?.chain === "forward").rule.expr.pop(); return rows; },
    (rows) => { rows.push(structuredClone(rows.at(-1))); return rows; },
  ]) {
    const { frozen, plan, d, state } = fixture(); state.nft.nftables.push(...change(installedRows(plan)));
    assert.throws(() => installNftFirewall(frozen, plan, d));
    assert.throws(() => restoreNftFirewall(frozen, plan, d)); assert.equal(state.mutations.length, 0);
  }
});
test("same-chain rule reordering rejects even though different chain display ordering is harmless", () => {
  const { frozen, plan, d, state } = fixture(); installNftFirewall(frozen, plan, d);
  const indices = state.nft.nftables.map((entry, i) => entry.rule?.table === plan.tableName && entry.rule.chain === "forward" ? i : -1).filter((i) => i >= 0);
  [state.nft.nftables[indices[0]], state.nft.nftables[indices[1]]] = [state.nft.nftables[indices[1]], state.nft.nftables[indices[0]]];
  assert.throws(() => verifyNftFirewall(frozen, plan, d));
});
test("restore deletion is verified and never retries an unknown result", () => {
  const { frozen, plan, d, state } = fixture(); installNftFirewall(frozen, plan, d);
  state.suppressWrite = true;
  assert.throws(() => restoreNftFirewall(frozen, plan, d)); assert.equal(state.mutations.length, 2);
});
test("mutated plan, reserved ports, duplicate addresses, injected identifiers reject before commands", () => {
  const { frozen, plan, d, state } = fixture();
  for (const field of ["script", "tableName", "priority", "bridge"]) {
    const altered = { ...plan, [field]: field === "priority" ? 10 : "untrusted" };
    assert.throws(() => installNftFirewall(frozen, altered, d));
  }
  for (const appPort of [22, 80, 443, -1, 65536]) assert.throws(() => planNftFirewall({ input: { ...input, appPort }, docker }));
  const bad = structuredClone(docker); bad.containers[0].address = bad.containers[1].address;
  assert.throws(() => planNftFirewall({ input, docker: bad }));
  assert.throws(() => planNftFirewall({ input, docker: { ...docker, bridge: "x;flush ruleset" } }));
  assert.equal(state.mutations.length, 0);
});
test("getter/prototype/array-hole boundaries do not execute caller accessors", () => {
  let touched = false;
  const { frozen } = fixture();
  const value = { ...frozen }; Object.defineProperty(value, "baseline", { enumerable: true, get() { touched = true; return frozen.baseline; } });
  assert.throws(() => validateNftFirewall(value)); assert.equal(touched, false);
  const hostile = structuredClone(frozen);
  Object.defineProperty(hostile.baseline.nftables, "0", { enumerable: true, get() { touched = true; return frozen.baseline.nftables[0]; } });
  assert.throws(() => validateNftFirewall(hostile)); assert.equal(touched, false);
  assert.throws(() => validateNftFirewall(Object.assign(Object.create({}), frozen)));
  const hole = structuredClone(frozen); delete hole.baseline.nftables[1]; assert.throws(() => validateNftFirewall(hole));
});
