-- merchant-space baseline schema for self-hosted Supabase / new Supabase project
-- Run in Supabase SQL Editor as project owner.

begin;

create extension if not exists pgcrypto;

create or replace function public.set_current_timestamp_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create table if not exists public.merchants (
  id text primary key,
  name text,
  email text,
  user_id uuid,
  auth_user_id uuid,
  owner_user_id uuid,
  owner_id uuid,
  auth_id uuid,
  created_by uuid,
  created_by_user_id uuid,
  owner_email text,
  contact_email text,
  user_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_merchants_updated_at on public.merchants;
create trigger set_merchants_updated_at
before update on public.merchants
for each row
execute function public.set_current_timestamp_updated_at();

create table if not exists public.pages (
  id uuid primary key default gen_random_uuid(),
  merchant_id text null,
  slug text not null default 'home',
  blocks jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

drop trigger if exists set_pages_updated_at on public.pages;
create trigger set_pages_updated_at
before update on public.pages
for each row
execute function public.set_current_timestamp_updated_at();

create table if not exists public.page_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  channel text null,
  page_path text null,
  success boolean null,
  payload_bytes integer null,
  changed_blocks integer null,
  reason text null,
  created_at timestamptz not null default now()
);

create index if not exists merchants_user_id_idx on public.merchants(user_id);
create index if not exists merchants_auth_user_id_idx on public.merchants(auth_user_id);
create index if not exists merchants_owner_user_id_idx on public.merchants(owner_user_id);
create index if not exists merchants_owner_id_idx on public.merchants(owner_id);
create index if not exists merchants_auth_id_idx on public.merchants(auth_id);
create index if not exists merchants_created_by_idx on public.merchants(created_by);
create index if not exists merchants_created_by_user_id_idx on public.merchants(created_by_user_id);
create index if not exists merchants_email_idx on public.merchants(lower(email));
create index if not exists merchants_owner_email_idx on public.merchants(lower(owner_email));
create index if not exists merchants_contact_email_idx on public.merchants(lower(contact_email));
create index if not exists merchants_user_email_idx on public.merchants(lower(user_email));

create index if not exists pages_slug_idx on public.pages(slug);
create index if not exists pages_merchant_id_idx on public.pages(merchant_id);
create index if not exists pages_updated_at_idx on public.pages(updated_at desc);
create unique index if not exists pages_public_home_unique_idx on public.pages(slug) where merchant_id is null and slug = 'home';
create unique index if not exists pages_merchant_slug_unique_idx on public.pages(merchant_id, slug) where merchant_id is not null;

create index if not exists page_events_created_at_idx on public.page_events(created_at desc);
create index if not exists page_events_event_type_idx on public.page_events(event_type);
create index if not exists page_events_channel_idx on public.page_events(channel);

grant usage on schema public to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;
grant select on public.pages to anon;
grant select, insert, update, delete on public.pages to authenticated;
grant select, insert, update on public.merchants to authenticated;
grant select on public.page_events to authenticated;
grant insert on public.page_events to anon, authenticated;

alter table public.merchants enable row level security;
alter table public.pages enable row level security;
alter table public.page_events enable row level security;

drop policy if exists merchants_select_own on public.merchants;
create policy merchants_select_own on public.merchants
for select
to authenticated
using (
  (
    auth.uid() is not null
    and (
      id = auth.uid()::text
      or user_id = auth.uid()
      or auth_user_id = auth.uid()
      or owner_user_id = auth.uid()
      or owner_id = auth.uid()
      or auth_id = auth.uid()
      or created_by = auth.uid()
      or created_by_user_id = auth.uid()
    )
  )
  or (
    nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
    and (
      lower(coalesce(email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
    )
  )
);

drop policy if exists merchants_insert_self on public.merchants;
create policy merchants_insert_self on public.merchants
for insert
to authenticated
with check (
  id = auth.uid()::text
  or user_id = auth.uid()
  or auth_user_id = auth.uid()
);

drop policy if exists merchants_update_own on public.merchants;
create policy merchants_update_own on public.merchants
for update
to authenticated
using (
  (
    auth.uid() is not null
    and (
      id = auth.uid()::text
      or user_id = auth.uid()
      or auth_user_id = auth.uid()
      or owner_user_id = auth.uid()
      or owner_id = auth.uid()
      or auth_id = auth.uid()
      or created_by = auth.uid()
      or created_by_user_id = auth.uid()
    )
  )
  or (
    nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
    and (
      lower(coalesce(email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
    )
  )
)
with check (
  (
    auth.uid() is not null
    and (
      id = auth.uid()::text
      or user_id = auth.uid()
      or auth_user_id = auth.uid()
      or owner_user_id = auth.uid()
      or owner_id = auth.uid()
      or auth_id = auth.uid()
      or created_by = auth.uid()
      or created_by_user_id = auth.uid()
    )
  )
  or (
    nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
    and (
      lower(coalesce(email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
      or lower(coalesce(user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
    )
  )
);

drop policy if exists pages_public_home_read on public.pages;
create policy pages_public_home_read on public.pages
for select
to anon
using (merchant_id is null and slug = 'home');

drop policy if exists pages_public_site_home_read on public.pages;
create policy pages_public_site_home_read on public.pages
for select
to anon
using (merchant_id is not null and slug = 'home');

drop policy if exists pages_owner_read on public.pages;
create policy pages_owner_read on public.pages
for select
to authenticated
using (
  (merchant_id is null and slug = 'home')
  or exists (
    select 1
    from public.merchants m
    where m.id = pages.merchant_id
      and (
        (
          auth.uid() is not null
          and (
            m.id = auth.uid()::text
            or m.user_id = auth.uid()
            or m.auth_user_id = auth.uid()
            or m.owner_user_id = auth.uid()
            or m.owner_id = auth.uid()
            or m.auth_id = auth.uid()
            or m.created_by = auth.uid()
            or m.created_by_user_id = auth.uid()
          )
        )
        or (
          nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
          and (
            lower(coalesce(m.email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
          )
        )
      )
  )
);

drop policy if exists pages_owner_insert on public.pages;
create policy pages_owner_insert on public.pages
for insert
to authenticated
with check (
  merchant_id is not null
  and exists (
    select 1
    from public.merchants m
    where m.id = pages.merchant_id
      and (
        (
          auth.uid() is not null
          and (
            m.id = auth.uid()::text
            or m.user_id = auth.uid()
            or m.auth_user_id = auth.uid()
            or m.owner_user_id = auth.uid()
            or m.owner_id = auth.uid()
            or m.auth_id = auth.uid()
            or m.created_by = auth.uid()
            or m.created_by_user_id = auth.uid()
          )
        )
        or (
          nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
          and (
            lower(coalesce(m.email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
          )
        )
      )
  )
);

drop policy if exists pages_owner_update on public.pages;
create policy pages_owner_update on public.pages
for update
to authenticated
using (
  merchant_id is not null
  and exists (
    select 1
    from public.merchants m
    where m.id = pages.merchant_id
      and (
        (
          auth.uid() is not null
          and (
            m.id = auth.uid()::text
            or m.user_id = auth.uid()
            or m.auth_user_id = auth.uid()
            or m.owner_user_id = auth.uid()
            or m.owner_id = auth.uid()
            or m.auth_id = auth.uid()
            or m.created_by = auth.uid()
            or m.created_by_user_id = auth.uid()
          )
        )
        or (
          nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
          and (
            lower(coalesce(m.email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
          )
        )
      )
  )
)
with check (
  merchant_id is not null
  and exists (
    select 1
    from public.merchants m
    where m.id = pages.merchant_id
      and (
        (
          auth.uid() is not null
          and (
            m.id = auth.uid()::text
            or m.user_id = auth.uid()
            or m.auth_user_id = auth.uid()
            or m.owner_user_id = auth.uid()
            or m.owner_id = auth.uid()
            or m.auth_id = auth.uid()
            or m.created_by = auth.uid()
            or m.created_by_user_id = auth.uid()
          )
        )
        or (
          nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
          and (
            lower(coalesce(m.email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
          )
        )
      )
  )
);

drop policy if exists pages_owner_delete on public.pages;
create policy pages_owner_delete on public.pages
for delete
to authenticated
using (
  merchant_id is not null
  and exists (
    select 1
    from public.merchants m
    where m.id = pages.merchant_id
      and (
        (
          auth.uid() is not null
          and (
            m.id = auth.uid()::text
            or m.user_id = auth.uid()
            or m.auth_user_id = auth.uid()
            or m.owner_user_id = auth.uid()
            or m.owner_id = auth.uid()
            or m.auth_id = auth.uid()
            or m.created_by = auth.uid()
            or m.created_by_user_id = auth.uid()
          )
        )
        or (
          nullif(lower(coalesce(auth.jwt()->>'email', '')), '') is not null
          and (
            lower(coalesce(m.email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.owner_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.contact_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
            or lower(coalesce(m.user_email, '')) = lower(coalesce(auth.jwt()->>'email', ''))
          )
        )
      )
  )
);

drop policy if exists page_events_insert_any on public.page_events;
create policy page_events_insert_any on public.page_events
for insert
to anon, authenticated
with check (true);

drop policy if exists page_events_select_authenticated on public.page_events;
create policy page_events_select_authenticated on public.page_events
for select
to authenticated
using (true);

insert into storage.buckets (id, name, public)
values ('page-assets', 'page-assets', true)
on conflict (id) do update set public = excluded.public;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'page_assets_public_read'
  ) then
    create policy page_assets_public_read
      on storage.objects
      for select
      to anon, authenticated
      using (bucket_id = 'page-assets');
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'page_assets_auth_upload'
  ) then
    create policy page_assets_auth_upload
      on storage.objects
      for insert
      to authenticated
      with check (bucket_id = 'page-assets');
  end if;
end
$$;

commit;

-- Seed default portal row only when missing.
insert into public.pages (merchant_id, slug, blocks)
select null, 'home', '[]'::jsonb
where not exists (
  select 1 from public.pages where merchant_id is null and slug = 'home'
);
